### PR TITLE
Hide repo description when it's empty

### PR DESCRIPTION
**Pull request by pablopunk**
# Issue

This is an attempt to solve https://github.com/sindresorhus/refined-github/issues/549

# Code

I tried doing it with jQuery but [you do notice the jump](https://github.com/sindresorhus/refined-github/issues/549#issuecomment-311532819) from visible to hidden.

The only thing I could come up with in css is a rule to hide the empty message.

# Results

## Admins with empty description

The problem here is that it hides the message even for admins, so it's a little weird after the change:

description-admin

arr1

empty-admin

## Non-admins with empty description

Here we can see that the UI is much cleaner after the change:

description-non-admin

arr2

empty-non-admin

### CODE REVIEW

**Comment by hkdobrev** [comment]
We could probably try the following and see if there would be much jumping:

- add a class to the body or the repo container if you're an admin of the repo (have Settings tab) as soon as possible with JavaScript
- based on that class show/hide the empty description

**Comment by paulmolluzzo** [comment]
Looks like people with edit rights have a `margin` class applied to a parent to account for the lack of "Add Topics" link.

Try `.mb-3 > .repository-meta-content > em { display: none !important}`

**Comment by hkdobrev** [comment]
> Looks like people without edit rights have a margin class applied to a parent element to account for the lack of "Add Topics" link.

I thought I had looked closely, but obviously, I've missed that. I even went so far to see if there's any support already for previous selector in CSS 4 😆

**Comment by pablopunk** [comment]
>I even went so far to see if there's any support already for previous selector in CSS 4

That's exactly what I've been looking for lol

>Looks like people without edit rights have a margin class applied to a parent element to account for the lack of "Add Topics" link.

Yeah, people "without rights", but that's already covered (see last screenshot)

**Comment by hkdobrev** [comment]
Something like this fixes both cases for me. However, the empty space remains when there's no description and you don't have admin access.

```css
.repository-meta > .repository-meta-content > em {
    display: block !important;
}
.repository-meta.mb-3 > .repository-meta-content > em {
    display: none !important;
}
```

**Comment by hkdobrev** [comment]
Actually, this is enough like @paulmolluzzo posted:

```css
.repository-meta.mb-3 > .repository-meta-content > em {
    display: none !important;
}
```

**Comment by pablopunk** [comment]
Oh, you guys are right, I was confused by the description showing in the repo when I have edit access, but I guess that was the point of the issue.

**Comment by paulmolluzzo** [comment]
@hkdobrev I think the first `.repository-meta` is unnecessary with the direct child selectors. 😉 Could be wrong though.

**Comment by hkdobrev** [comment]
@paulmolluzzo I'm just trying to make it more future-proof. If they move meta class and keep the margin it might break instead of just falling back to the default GitHub behaviour.

**Comment by paulmolluzzo** [comment]
@hkdobrev fair enough. It's pretty specific either way.

**Comment by hkdobrev** [comment]
With this JS I can't see any jumping/flickering:

```js
function hideEmptyMeta() {
	const meta = select('.repository-meta');
	if (select.exists('em', meta) && !select.exists('.js-edit-repo-meta-button')) {
		meta.style.display = 'none';
	}
}
```

What do you think?

**Comment by paulmolluzzo** [comment]
I prefer CSS. Just because you don't see it doesn't mean someone on a thinner connection or older machine won't. Can you try throttling yourself or somehow slow down the runtime?

**Comment by hkdobrev** [comment]
@paulmolluzzo I mean that in addition to the CSS. The JS would just remove the empty space and push the repo contents and readme up. Will try to simulate a slower CPU.

**Comment by paulmolluzzo** [comment]
> @paulmolluzzo I mean that in addition to the CSS. The JS would just remove the empty space and push the repo contents and readme up. Will try to simulate a slower CPU.

@hkdobrev in that case, sure, why not have both? As long as there's no jumping content.

**Comment by pablopunk** [comment]
Should I add that to the PR?

**Comment by paulmolluzzo** [comment]
> Should I add that to the PR?

I approve this as it is now, so I'll leave this for @hkdobrev or someone else to answer. I guess if someone else approves they'll just merge. :man_shrugging:

**Comment by hkdobrev** [comment]
@paulmolluzzo I've tried all combinations of slow/fast network and slow/fast CPU. There's no jumping.

> Should I add that to the PR?

If you can confirm this hides the empty space without any jumping, please do. This is what #549 was actually about.

**Comment by pablopunk** [comment]
Confirmed. It also fixes the repos where the description is empty but it has some tags ([like this one](https://github.com/pablopunk/scripts))

**Comment by hkdobrev** [comment]
> It also fixes the repos where the description is empty but it has some tags

Nice catch, didn't check this case.

**Comment by pablopunk** [comment]
About the code, I added the check `isRepoRoot` cause it shouldn't be executed anywhere else

**Comment by hkdobrev** [comment]
Thanks @pablopunk! 🙌 🎉

**Pull request merged**
