### PR TITLE
Improve feature loading mechanism

### PR DESCRIPTION
**Pull request by fregante**
New attempt at solving this: https://github.com/sindresorhus/refined-github/pull/2925#issuecomment-608541758

WIP: I'll have to review this code again and do a couple of new TODOs

## Why

- Lets you add any number of listeners for AJAXed widget, like `onNewComments`, `onNewsfeedLoad`, etc.
- The listeners themselves can be simplified to avoid having to manage `onAjaxedPages` internally.
- Easier to understand (_what did `onAjaxedPages` mean anyway?_)

## Changes

- By default, run on DOM ready and AJAX pages.
- You can customize this behavior with 3 separate options:

	- `waitForDomReady: true`: ["fast features"](https://github.com/sindresorhus/refined-github/issues/2671) will have to set this to false.
	- `repeatOnAjax: true`:  It's the most common configuration anyway. It only **_has to_** be set to `false` in rare occasions.
	- `repeatOnAjaxEvenOnBackButton: false`: this the equivalent of the old `onAjaxedPagesRaw`. Only used by 3 features.

- Pass additional listeners via `additionalListeners: []` property. These listeners will be run _after_ each page load, whether this is "document start", DOM ready or AJAX.

### CODE REVIEW

**Comment by fregante** [comment]
@sindresorhus @yakov116 it'd be great if you could use this for a few days. It looks like it's working for me, but I haven't change the features that were "updated" the most.

**Comment by yakov116** [comment]
@fregante I have very limited access to a computer over the next week but I will try it and let you know how it goes.

**Comment by yakov116** [comment]
>I haven't specifically tested the features that were "updated" the most.

@fregante what things specifically should i test?

**Comment by fregante** [comment]
> what things specifically should i test?

Any feature that was updated beyond just the drop of the `load` property. 

Example of a feature to test:


test


Example of a feature to skip:


skip

**Comment by yakov116** [comment]
I am having issues with #2992 and this. I am not sure is #2992 is the issue or this PR is. Testing and will let you know.

**Comment by yakov116** [comment]
#2992 is the issue

**Pull request merged**
