### PR TITLE
Avoid clipping descriptions and CI status messages in `dim-bots`

### LINKED ISSUE #3124: CI Job Status hidden behind commits
open a commit stream which contains greyed-out commits, like

grafik

hover the first commit to get it into the foreground and click the "X" for the CI status:

grafik

the checks panel is hidden behind the greyed-out commits

occured on google chrome canary 85.0.4150.0 with refined github 20.5.21

### PR DESCRIPTION
**Pull request by tanettrimas**
Fixes #3124

Solution:
- The overflow-hidden property is moved to not:navigation-focus
- Implemented a scroller for text that exceeds the container, which was not the case before.

Skjermbilde 2020-05-23 kl  19 39 57
Skjermbilde 2020-05-23 kl  19 39 21

**TEST URL**
https://github.com/kulshekhar/ts-jest/commits/master

### CODE REVIEW

**Comment by tanettrimas** [comment]
@fregante Do you want to check this out? :D

**Comment by fregante** [comment]
Can you post a link to test this as suggested by the PR template?

**Comment by tanettrimas** [comment]
> Can you post a link to test this as suggested by the PR template?

Done! :)

**Comment by tanettrimas** [comment]
I saw a small typo in the pr_template file, so I just fixed that in another PR #3129

**Comment by fregante** [comment]
dfddss

As mentioned in the issue, the `overflow: hidden` is **required** during the animation, or else the content will appear outside.

What this PR shows, it's as if `overflow: hidden` was not there at all.

So it should either be dropped, or solved as suggested.

**Comment by tanettrimas** [comment]
@fregante How much delay do you have on? I can't even notice it the difference running in normal mode. Will however try to fix it in another way if it is critical :)

**Comment by fregante** [comment]
I just slowed down the animation to make it more visible. It's _critical_ because currently this PR **adds** code which only **undoes** existing code.

**Comment by tanettrimas** [comment]
That is good to know! I will leave it at this for the time being :)

**Comment by yakov116** [comment]
@tanettrimas you should change the wording to `fixes #3124` in your first post so it closes the issue if/when merged.

**Comment by tanettrimas** [comment]
Done :)

**Comment by fregante** [comment]
The overlay was still clipped if the description is expanded:



With my commit, the commit is not dimmed anymore if the description is expanded, so it's not clipped either:

**Comment by tanettrimas** [comment]
That is better to be fair, so that you dont need to scroll :)

**Comment by fregante** [comment]
Suggestion: Commits and PR titles should always describe what they fix at the highest level possible, not describe the diff itself. So I changed the title

Anyway, thanks for opening this PR Tanet! :)

**Comment by tanettrimas** [comment]
Thanks for all the feedback, this is only my second PR ever so 😅

**Pull request merged**
