### PR TITLE
Rename `src` to `source` and `extension` to `distribution`

### PR DESCRIPTION
**Pull request by sindresorhus**
I often mistake the `extension` directory as the source directory...

### CODE REVIEW

**Comment by busches** [comment]
Why `source` over `src` and `distribution` over `dist`? I know you hate abbreviated words, but those are very common. All for renaming `extension` as I do it myself.

**Comment by ramlmn** [comment]
> I often mistake the `extension` directory as the source directory...

Me too. But changing `src` to `source` won't make a difference. Only renaming `extension` to somethig else, like `dist` should do it.

**Comment by sindresorhus** [comment]
Clear for you, but not for everyone. I don’t see the problem with a few more characters to make it totally clear.

https://stackoverflow.com/questions/23730882/what-is-the-role-of-src-and-dist-folders

**Comment by jgierer12** [comment]
This broke the icon in readme.md. Fixed in https://github.com/sindresorhus/refined-github/commit/d10510f660d4e1393ad01af097f97de36ced680c

**Pull request merged**
