### PR TITLE
WIP: New feature / button to create a new branch from an issue

### PR DESCRIPTION
**Pull request by freguinhas**
Adds a button on the issue page to immediately create a branch based on the issue's name:

Screen Shot 2019-04-13 at 12 05 16

Screen Shot 2019-04-13 at 13 40 47

Based on this (very active) feature request: https://github.com/isaacs/github/issues/1125

### CODE REVIEW

**Comment by bfred-it** [comment]
This sounds backwards and goes against GitHub notion of PR. It’s the PR that should contain all the commits and discussions about the code, not the issue. One issue might have multiple PRs. One PR might close multiple issues. 

Also among all those steps described there there’s a “make commits on your computer” which means you’re in the exact place to write `git checkout -b issue-32` without having to go through all that and then manually fetch and checkout the same branch you created online. 

Am I missing something?

**Comment by robertofrega** [comment]
@bfred-it I see your point and totally agree about the PRs. 

This implementation certainly doesn't seem like the way this should work. I was thinking exclusively from the maintainers' perspective (the button does appear only to maintainers, though).

But I still like the idea of having the Issue Page as the starting point. Somehow enforcing/enabling the git flow seem like a good way to enforce best-practices.

What if the button:
- made sure the user has a fork from the original repository, if not, create it.
- ask the user the type of branch (feature, bug, etc)
- create a branch on the destination fork
- display the git command to checkout the branch from remote

**Comment by bfred-it** [comment]
I still don’t think any of this is worth the hassle. Forking is even more involved because the user can select where to fork *to*

**Comment by sindresorhus** [comment]
I don't think this is worth it either. It's not how I or anyone I know create PRs.

**Comment by bfred-it** [comment]
Considering that many people seem to want this way of doing things, you might have some success publishing it as its own extension

**Comment by freguinhas** [comment]
Sure, no problem. 

Come to think of it, I work like that on GitLab, but even after having the button here on Github I just don't use it... Github is a completely different community.

**Comment by HarisSpahija** [comment]
would this feature be better if there was templating allowed in the settings of the repo? Or what if you are allowed to create a branch from the button but still have to manually type the title of the branch with some predefined parameters (ex. Jira create branch functionality)?

**Comment by HarisSpahija** [comment]
I think this issue should be reopened after seeing the amount of people commenting on https://github.com/isaacs/github/issues/1125
I don't see the harm of having the feature there, even if you are not used to this workflow. Many developers like this feature that are used to the workflow in the bitbucket/jira side of development. 
Could you reopen this issue? @sindresorhus

**Comment by nekenyu** [comment]
New user of github here...  What is a PR?  I don't see it on my project page or on my issue page.  You could tell me to Read The Formal Manual or such, but...  You could also consider.

I am a professional software developer.  I actually understand where you are coming from.  I'm helping out a small project that doesn't know how things work in the real world.

But in the end: The more people have to manually do (create a branch with a name, create a pull request on that branch, link it to that issue), the more things won't get done "right" and the harder it will be.  Further, on a professional project, I still have to deal with consistent naming schemes.

I offer the following concept that may make everyone more happy.  It might also be a little bigger than requested work wise, but might make more people happy:

- Before anything is linked to an issue and it is open: Issue page the following button:
  - Create single branch to fix: Creates branch issue-#
- Until an issue is closed: Issue page gets one button:
  - Create another branch to fix: Creates branch issue-#-<counter> (starting at 1)
  - Note: This works even after issue-# is created
- When a pull request is created for a branch named issue-# or issue-#-counter:
  - If the issue-# is open, automatically link it and put a notice on the pull request it is linked to issue-#
    - If the branch is issue-# and no other branches are linked, set the branch to close the issue and put a notice on the pull-request that completing the pull request will close the issue
    - If the branch is not issue-# or other branches are linked, do not set that setting automatically.  If the setting is not set, also put a notice on the Pull Request that it will not close the issue (in addition to the notice that it is linked).
  - If the issue-# is closed, do not link it and put a notice on the pull request that a closed issue-# and is **not** linked.

Note: The above does not preclude as suggested above: 'git checkout -b issue-# <branch>' or similar with issue-#-<anything>...  The buttons are convenient, especially for the newer users.  You could put a hover over the button with a pro-tip that they can do the command line and push.

I am new to the GitHub Way.  Maybe I got that a little wrong.  I had to piece together some things and hope I captured everything.  The point is: offer ways to automatically do the GitHub Way with less effort, less mess, etc. -- extra points if it can be completely ignored to do it differently.

**Comment by busches** [comment]
PR is a pull request. As other comments have said, this is a specific workflow that doesn't work for all users and doesn't belong in this extension, but as it's own.

**Comment by nekenyu** [comment]
I'm not a developmental politician.  I don't understand what that means.  I've seen a bunch of attempts to get a working feature overdue by many years.  How do people actually get what they need?

**Comment by busches** [comment]
You create it yourself and package it as its own extension.

**Comment by nekenyu** [comment]
Which is even more complicated for the users of the system to have to find and use something that really should be a part of the base system -- leaving GitHub years behind the competition.  Thank you for explaining it.  At least I now understand.

**Comment by busches** [comment]
You do know we are not GitHub or associated with GitHub, correct? You should be sending these ideas to them first.

**Comment by nekenyu** [comment]
Sorry, found this cross-linked from someone at GitHub begging for support.  It wasn't obvious when I left GitHub about GitHub and went to something else on GitHub. 
 Sincerely, sorry to trouble you, and I thank you for providing information.

**Comment by fregante** [comment]
https://github.blog/changelog/2022-03-02-create-a-branch-for-an-issue/

They implemented it

**Pull request closed without merging**
