### PR TITLE
Add quick review buttons

### PR DESCRIPTION
**Pull request by bfred-it**
Related to #883 

Test it on #886 

**One issue:** <kbd>cmd</kbd>+<kbd>enter</kbd> will submit the form correctly when there's only one button (**Comment**), but currently fails when there is more than one button. What should we do in that case? 
- 👉 Default to **Comment** (if a different action was meant, just submit a new comment-less review)
  _**Edit:** I picked this one because GitHub also defaults to "comment", as you can see in the first screenshot_
- ~~Disable <kbd>cmd</kbd>+<kbd>enter</kbd>~~

# Before

# All buttons available

# Only comment available

f

### CODE REVIEW

**Comment by hkdobrev** [comment]
I've noticed a problem - when you have left some review comments and nit yet posted, you have a 4th button to cancel all of your review comments:

image

**Comment by bfred-it** [comment]
Good catch! They don't fit. What do we do? Smaller font? Wider popup?

**Comment by hkdobrev** [comment]
For me, a wider popup with the button "Cancel review" being the left-most one is the preferred option. If we could have some additional space between "Cancel review" and "Request changes" like the other cancel buttons, that would be great.

I thought we could rename "Cancel review" to "Cancel", but it's not really the same meaning and I see why they've called it that.

**Comment by bfred-it** [comment]
Should be fine now.

Buttons alignment

The color is the same as **Comment** but I think that's fine since it asks for confirmation

Cancel confirmation

**Comment by bfred-it** [comment]
Other option:

left-aligned

**Comment by hkdobrev** [comment]
This looks perfect! This is what I meant with additional space, but had the buttons order confused because of my screenshot.

**Comment by hkdobrev** [comment]
Just wanted to mention this approach is a far better progressive enhancement over some of the suggestions in #883. And even though it's not a huge change, it's exactly what RG is about - decluttering the interface from things which are used every hour if not more often by the power users while keeping the things that matter.

**Comment by sindresorhus** [comment]
This is so much better than what GitHub provides.

@bfred-it Can you add it to the readme highlights before merging?

**Comment by hkdobrev** [comment]
Sorry, just merged another CSS-related PR so there's a conflict now. Could you fix the conflict and merge it? I love it and stay on this branch for some time now.

**Comment by sindresorhus** [comment]
I fixed the merge conflict.

**Comment by bfred-it** [comment]
Away from keyboard this week probably. Can anyone take a comparison screenshot and update the readme?

**Comment by bfred-it** [comment]
Readme screenshot

faster github reviews

**Pull request merged**
