### PR TITLE
Add `friendlier-requested-changes` feature

### LINKED ISSUE #1602: More friendly "Changes requested" state in PRs
See: https://twitter.com/ashfurrow/status/1056944193669599233

We could change the color and icon to something more friendly, while still keeping it obvious that it's not approved.

### PR DESCRIPTION
**Pull request by arnaudvalle**
Closes #1602 

# Test

- Go to a PR that has some requested changes from a review (i.e. https://github.com/sindresorhus/refined-github/pull/2667)
- Notice that the colour of the text and icons is now grey rather than red

Before:
Screenshot 2019-12-09 22 23 58

After:
Screenshot 2019-12-09 22 22 43

### CODE REVIEW

**Comment by busches** [comment]
The color contrast isn't there anymore, as a colorblind individual, its now really close to the green now.

**Comment by yohanneshabte** [comment]
hi @busches and @arnaudvalle, what about a blue color since it is very helpful to know when a change is requested on a PR. Currently there is no difference in visual when review is requested or change is requested. Here is a screenshot with a blue(#3f29b9)
Screen Shot 2019-12-09 at 9 54 09 PM

**Comment by fregante** [comment]
Blue looks like a link; perhaps purple?

**Comment by arnaudvalle** [comment]
Alright - here are a few variants taken from your comments:

purple 500:
Screenshot 2019-12-10 22 12 37

pink 600:
Screenshot 2019-12-10 22 14 22

yellow 700 + black text:
Screenshot 2019-12-10 22 17 55

**Comment by jerone** [comment]
My preference goes to "yellow 700 + black text". 

Red is for when something is broken or denied. Green for successes and approvals. The orange color (yellow 700) is already known for pending and waiting status, which this is.

**Comment by arnaudvalle** [comment]
> My preference goes to "yellow 700 + black text".

I agree. Purple and pink seem to come a bit out of nowhere (I don't remember seeing them elsewhere in the interface) and I don't think they're really associated (at least in my mind as a regular user) to a specific message like yellow/warning.

Plus it just feels/flows better with the other items in that area from a UI point of view I reckon.

**Comment by fregante** [comment]
Yeah I think yellow works.

Perhaps save the color as a variable in `content.css`

**Comment by arnaudvalle** [comment]
I made the change to yellow icon + dark text as discussed.

**Comment by fregante** [comment]
I'm not convinced anymore. The moment I opened my first "changes requested PR" I thought that the CI was still running because that's the color that GitHub uses in that case.

**Comment by arnaudvalle** [comment]
Right, I see. Any other suggestion? How about something grey? Similar to when you have merge conflicts:

**Comment by fregante** [comment]
Interesting. GitHub is using gray to show an action needs to be taken, so I wouldn’t mind it for Requested Changes too

**Comment by arnaudvalle** [comment]
Would look like this: Screenshot 2019-12-17 21 27 28

If we go with grey, I'd suggest we also make the main surrounding border grey as well as the main branch icon indicator, like they do on the Draft PRs?
Screenshot 2019-12-17 21 26 09

(oops sorry about the comment in the wrong PR, I posted my message in the one I was testing on because it had requested changes... :()

**Comment by sindresorhus** [comment]
Yeah, gray looks good to me.

**Comment by fregante** [comment]
🎉

**Comment by ProLoser** [comment]
Not a fan of this, think it should be reverted. It was mostly voted down to begin with and it feels a bit confusing and superfluous

**Comment by vpicone** [comment]
I think the most pertinent argument against gray was:

> The color contrast isn't there anymore, as a colorblind individual, its now really close to the green now.

**Comment by fregante** [comment]
Dropping this in https://github.com/sindresorhus/refined-github/pull/2860

**Pull request merged**
