### PR TITLE
Sticky file headers on pull request diff view

### PR DESCRIPTION
**Pull request by stipsan**
The collapse button for each file diff is suddenly more useful with this, as you don't have to scroll hunt for the file header any longer.

Preview:

kapture 2017-07-27 at 19 03 08

Edit: updated the preview gif

### CODE REVIEW

**Comment by stipsan** [comment]
Right, hang on

**Comment by bfred-it** [comment]
I wouldn't mind undoing the red/green indicator position change:

## Native




## Refined

**Comment by bfred-it** [comment]
You can refer to these two issues for the required changes: 

https://github.com/sindresorhus/refined-github/pull/99/files
https://github.com/sindresorhus/refined-github/pull/326/files

**Comment by bfred-it** [comment]
Last change would be to update the first item here in the readme: https://github.com/sindresorhus/refined-github/blob/master/readme.md#more-info-at-a-glance

**Comment by stipsan** [comment]
Thanks for the pointers, I'll update the PR accordingly. Just have to get the dev setup running and familiarize myself a little more with the codebase 😄 

Also noticed I need to undo the position of another sticky as well (the "Subset of changes - View All"):

  
skjermbilde 2017-07-27 kl 16 42 44

Native
skjermbilde 2017-07-27 kl 16 43 50

**Comment by stipsan** [comment]
@bfred-it changes pushed 😄

**Comment by bfred-it** [comment]
This works! Paging Dr. @sindresorhus to double-check since he had implemented the feature we're removing.

**Comment by sindresorhus** [comment]
> since he had implemented the feature we're removing.

Not me.

**Comment by sindresorhus** [comment]
@stipsan This is amazing :)

**Comment by stipsan** [comment]
@sindresorhus thanks! 😄

**Comment by lukehefson** [comment]
Hello friends 💁‍♂️

We just shipped this 'natively' at GitHub: https://github.blog/changelog/2019-03-18-sticky-file-headers-in-pull-requests/ 

As ever we were hugely inspired by you. Thank you thank you!

---

### Bonus behind-the-scenes story:

When we started getting requests for this due to the implementation above ☝️, I initially pushed back on the 'sticky on sticky' idea of attaching it to the sticky title header and we explored some other design routes. We eventually came back to sticky-on-sticky because it was decided that "Luke was wrong" and I shouldn't be allowed to backseat design things 🤣

**Comment by bfred-it** [comment]
If Luke was wrong, your friends'll love this suggestion https://github.com/sindresorhus/refined-github/issues/1857

**Comment by stipsan** [comment]
This is awesome @lukehefson! And thanks for the sharing the behind-the-scenes 😂

**Pull request merged**
