### PR TITLE
Fix selector for hiding pushes and forks

### PR DESCRIPTION
**Pull request by kevva**
I don't know what the selectors for deleting branches and adding someone as a collab is though since I couldn't find any in my news feed.

### CODE REVIEW

**Comment by sindresorhus** [comment]
@kevva I just made a branch and deleted it. Do you see it in your feed?

**Comment by kevva** [comment]
No, maybe they've disabled it.

screen shot 2017-10-17 at 12 54 21

**Comment by bfred-it** [comment]
@sindresorhus  can you update the main gif in the readme?

**Comment by sindresorhus** [comment]
@bfred-it I was planning to, but want to wait a few weeks more to make sure they're not doing more changes. It's a little bit of work to make the GIF, so I don't want to have to do it again soon.

**Comment by yakov116** [comment]
Doesn't this make the feed kind of useless. Since now the only thing that is shown is labels?

**Comment by kevva** [comment]
The feed still shows when issues and pull requests are created or commented on. It also shows what repos other users has starred and created.

**Comment by yakov116** [comment]
@kevva not by me...

**Comment by kevva** [comment]
> The feed still shows when issues and pull requests are created or commented on

Never mind, it seems like GitHub have removed those features and thus made the news feed kinda useless. Seeing a bunch of commits is just noice.

**Comment by bfred-it** [comment]
I've been using the feed essentially to see what other people star, hence the per-repository grouping of my no-longer-compatible [GitHub Clean Feed](https://github.com/bfred-it/github-clean-feed)

![](https://github.com/bfred-it/github-clean-feed/raw/master/screenshot.png]

**Comment by yakov116** [comment]
@kevva So why not remove it all together 😆 

I happen to think that they will bring it back. But by then they will mess even more stuff up.

**Comment by bfred-it** [comment]
New issues, PRs and comments however... I think they were duplicates of notifications? So I can see why they removed those.

**Comment by yakov116** [comment]
@bfred-it I totally disagree. I use notifications to tell me when something is new. But I look at my feed to see if was important.
Now I waist my time looking at useless stuff since I don't know what it is. PLUS if you want to find an issue that was in you notifications you have to go through them all. Before i was able to find is simply in the feed.

What gets me the most mad is that the removed it from the api without telling us.

**Comment by kevva** [comment]
> New issues, PRs and comments however... you still get notifications if you watch the repos. So I can see why they removed those.

I get that too, but I still liked having a preview in the news feed.

**Comment by casz** [comment]
I agree with @yakov116 the feed is completely useless now. So many features I like about refined github but this makes the extension useless to me.

**Comment by yakov116** [comment]
@bfred-it all the feed items returned via api!!

**Pull request merged**
