### PR TITLE
Add navigation to milestone pages

### LINKED ISSUE #366: Add link to all milestones on milestone page
Milestones listing page is currently accessible through the Issues or Pull requests listing page. However, when you open a specific milestone page, there is no link to all milestones. You need to go to issues/PRs to see the link.

Changing the URL manually or clicking back when you have come from the milestones page works, but a link to the index should also be there.

Milestone page: https://github.com/composer/composer/milestone/18
Milestones page: https://github.com/composer/composer/milestones

I think we should add the same navigation buttons which are visible on the Milestones page on the Milestone page as well:

screen shot 2017-03-08 at 16 56 09

### PR DESCRIPTION
**Pull request by jgierer12**
The same labels/milestones navigation buttons that are found on the [milestone list page](https://github.com/composer/composer/milestones) are now also on [single milestone pages](https://github.com/composer/composer/milestone/18).

Before: Before

After: After

Fixes #366

### CODE REVIEW

**Comment by paulmolluzzo** [comment]
Thanks for the PR! This looks really good, but there's a failing build, most of which isn't actually from this PR.

I don't want to get off on a tangent, but the `capitalized-comments` errors could be fixed automatically with `xo --fix`.

The `Unexpected chained assignment. no-multi-assign` can be fixed or we can just ignore the line.

The warning on `complexity` we can leave.

Or someone can open a PR that fixes the issues.

**Comment by jgierer12** [comment]
Thanks, I fixed the linter issues!

**Comment by paulmolluzzo** [comment]
👍 

@hkdobrev? You opened #366, what do you think?

**Comment by paulmolluzzo** [comment]
Any comments on this PR or are we OK to 🚢 ?

**Comment by sindresorhus** [comment]
Looks good :)

**Comment by hkdobrev** [comment]
:raised_hands: Thanks @jgierer12!

**Pull request merged**
