### PR TITLE
Remove `add-co-authored-by` feature

### LINKED ISSUE #2663: GitHub added `add-co-authored-by`
I think we can safely disable/remove the add-coauthored-by feature

This should be handled by the recent change, see the changelog:
https://github.blog/changelog/2019-12-19-improved-attribution-when-squashing-commits/

### PR DESCRIPTION
**Pull request by casz**
as it was introduced by GitHub.

Closes #2663

# Test
Attempt to squash any open PR with a co-author on it.

Tested and worked:
image

### CODE REVIEW

**Comment by casz** [comment]
Not sure what it requires to clean up any config when this feature is removed.

**Comment by fregante** [comment]
Thanks! If you search the feature name in the files you’ll find other mentions (e.g. readme)

In the readme it needs to be moved to the “implemented by GitHub” section and its count needs to be increased.

**Comment by casz** [comment]
@fregante done 👍

**Comment by fregante** [comment]
Thank you!

**Pull request merged**
