### PR TITLE
Fix style conflict caused by `reactions-avatars` on other pages

### LINKED ISSUE #4630: `reactions-avatars` style applied to not implemented pages
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

The reaction count number in a discussion's or a release's reaction gets a gray background in a square around it.

Not only that, those counts also seem to get slightly misaligned and smaller in comparison to without Refined Github.

Find Feature can't find it, so it may be a problem in a global stylesheet.

### Screenshot

With Refined Github:
imagen

Without Refined Github:
imagen

### Console errors

_No response_

### Example URL

https://github.com/github/feedback/discussions/4291
https://github.com/sindresorhus/refined-github/releases/tag/21.8.1

### Browser(s) used

Firefox 90.0.2

### PR DESCRIPTION
**Pull request by kidonng**
Fix #4630

## Test URLs

- Discussions: https://github.com/github/feedback/discussions/4291
- Releases: https://github.com/sindresorhus/refined-github/releases/tag/21.8.1

### CODE REVIEW

**Comment by fregante** [comment]
Why not use a more specific selector instead? If GitHub adds reactions to more places we have to add more exceptions. Is there a comments class that doesn't appear on other pages?

**Comment by altrisi** [comment]
Another solution for most of those selectors would be to add a custom class to reaction avatars so they can be referenced directly instead of relying on them being the only `span` inside the reaction button.

**Comment by fregante** [comment]
Good idea, we can add a class on the `button` and then target the contents via span and img

**Comment by fregante** [comment]
Merging because it’s a fix but hoping for a better fix later. Tagging it as such 👇

**Comment by kidonng** [comment]
I kinda forgot about this PR. IMO it's specific enough because it seems the discussion and release reactions uses the same "newer" markup and I'd expect any (potential) future additional will be the same.

**Comment by fregante** [comment]
Discussions tracked here: https://github.com/sindresorhus/refined-github/issues/3978#issuecomment-835082262

**Comment by fregante** [comment]
Screen Shot

I'm see this on every page now

**Pull request merged**
