### PR TITLE
Improve repo page detection across the board

### LINKED ISSUE #783: Uncaught (in promise) TypeError: Cannot read property 'after' of undefined
When loading any page in settings

```
more-dropdown.js:16 Uncaught (in promise) TypeError: Cannot read property 'after' of undefined
    at more_dropdown (more-dropdown.js:16)
    at safely (utils.js:10)
    at github_injection_default (content.js:557)
    at gitHubInjection (index.js:13)
    at onDomReady (content.js:555)
    at <anonymous>
more_dropdown @ more-dropdown.js:16
safely @ utils.js:10
github_injection_default @ content.js:557
gitHubInjection @ index.js:13
onDomReady @ content.js:555
async function (async)
onDomReady @ content.js:514
init @ content.js:511
__webpack_require__.URL.URL @ content.js:638
__webpack_require__ @ bootstrap fc446b7fa65d86637335:19
(anonymous) @ bootstrap fc446b7fa65d86637335:62
(anonymous) @ bootstrap fc446b7fa65d86637335:62
09:55:17.833 add-releases-tab.js:42 Uncaught (in promise) TypeError: Cannot read property 'before' of null
    at add_releases_tab (add-releases-tab.js:42)
    at safely (utils.js:10)
    at github_injection_default (content.js:558)
    at gitHubInjection (index.js:13)
    at onDomReady (content.js:555)
    at <anonymous>
```

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes #783 again

I decided to put the check in `getRepoPath` because this function kinda implies that it only gets a repo's path, not blindly get whatever happens to be 2 dirs deep.

### CODE REVIEW

**Comment by yakov116** [comment]
@bfred-it tested it looks good! thanks

**Comment by bfred-it** [comment]
No worries, thank you for reporting these issues! We don't have a `tab-handler.js` file though, not our bug.

**Comment by yakov116** [comment]
@bfred-it oops looks like I copied the wrong error

```javascript
chrome-extension://ecnglinljpjkbgmdpeiglonddahpbkeb/content-script.js:37 Uncaught TypeError: Cannot read property 'parentElement' of null
    at removeElement (chrome-extension://ecnglinljpjkbgmdpeiglonddahpbkeb/content-script.js:37)
    at TabHandler._onTabLeave (chrome-extension://ecnglinljpjkbgmdpeiglonddahpbkeb/content-script.js:226)
    at HTMLBodyElement.document.body.addEventListener.e (chrome-extension://ecnglinljpjkbgmdpeiglonddahpbkeb/content-script.js:201)
```

**Comment by bfred-it** [comment]
Still not our file :D

**Comment by bfred-it** [comment]
Our extension ID is `hlepfoohegkhhmjieoechaddaejaokhf`

To help you remember it: it starts with **help fool**: `hlepfooheg...`

**Pull request merged**
