### PR TITLE
Update dashboard style

### PR DESCRIPTION
**Pull request by bfred-it**
# Before

# After

### CODE REVIEW

**Comment by sindresorhus** [comment]
Looks better.

Maybe horizontally align the top of the avatar with the top of the title?

screen shot 2019-03-05 at 12 32 08

**Comment by nesl247** [comment]
I think it looks worse this way. Maybe it would be better to have the whole contents in the white box instead of the title and timestamp outside of it? The text doesn't contrast enough with the background color IMO.

**Comment by bfred-it** [comment]
How about this?

screenshot 2019-03-06 at 10 02 45

**Comment by nesl247** [comment]
@bfred-it That looks really good.

**Comment by bfred-it** [comment]
Also perhaps I should drop the `updated __/__` from new repos.

**Comment by bfred-it** [comment]
Here are some new and comprehensive styles:

screenshot 2019-03-06 at 11 18 22
screenshot 2019-03-06 at 11 18 49
screenshot 2019-03-06 at 11 18 34

**Comment by bfred-it** [comment]
Let's give this a go

**Pull request merged**
