### PR TITLE
Semantically select a head commit for the compare tab

### LINKED ISSUE #267: Feature request - Add compare tab
I often find myself doing comparisons of commits/releases when trying to determine if a bug fix has shipped in a given release.

Currently GitHub doesn't offer a simple way to get to the compare screen.

Similar to how the `Releases` tab was added, I was thinking of adding a compare tab beside that. Clicking on that tab would default to redirecting the the `/compare` url, but if you clicked on it from a commit, diff, or release etc it will make a comparison between that point and `master`.

Is this something that sounds reasonable? I'll be happy to submit a PR in the event that it is

Cheers

### PR DESCRIPTION
**Pull request by jgierer12**
Apart from the "Compare" tab that #399  introduced, #267 also proposes a "semantic" selection of the head commit. Based on the current page type, the head is chosen like this (checked items are implemented):
- [x] PR -> Compare against upstream branch
- [x] Commit -> Compare against that commit
- [x] Comit list -> Compare against latest of these commits
- [x] Non-default branch on repo root or file tree -> Compare against that branch
- [x] Release -> Compare against that release
- [x] Release list -> Compare against latest of these releases

Anything else just points to the default compare page.

Often, it would make more sense to semantically set the base instead and compare against master. Perhaps we can automatically "click" the "switch the base" link (as seen on https://github.com/sindresorhus/refined-github/compare/8778310c6ac7149b707bb55d6b1324650a326b26) if it exists?

Closes #267.

### CODE REVIEW

**Comment by hkdobrev** [comment]
@jgierer12 Do you think we can leave releases improvements for a separate PR? I'd also split my suggestions from https://github.com/sindresorhus/refined-github/issues/267#issuecomment-257043090 in a separate issue.

**Comment by jgierer12** [comment]
I added the head selection functionality for releases in this PR, since it fits thematically. The feature to compare releases I'd leave for another PR/issue.

What do you think about switching head and base? For releases and commit lists it would certainly make sense to switch them, since they're almost always older than `master`. Possible solutions:

- Hard-code setting the base commit dynamically and compare against `master` depending on the current page type (e.g. set releases as base, set PRs as head)
Issues:
    - Default branch isn't always `master` (this issue is not present if we always set the head since GitHub automatically compares against the default branch in that case)
    - For commits and branches, there is no good way to figure out if they need to be base or head
- Always set the head, wait for the page to load and then redirect to the `href` of the "switching the base" link (as seen on https://github.com/sindresorhus/refined-github/compare/8778310c6ac7149b707bb55d6b1324650a326b26)
Issues:
    - Slow
- Just leave it as-is and let the user switch base and head if required
Issues:
    - Slow
    - Not intuitive

**Comment by bfred-it** [comment]
What is this missing to be merged?

**Comment by hkdobrev** [comment]
@jgierer12 Could you please fix the merge conflicts, please? Thanks!

**Comment by bfred-it** [comment]
These are not regular merge conflicts, those files have been moved when the build was added #465 

You're better off re-applying them by hand.

**Comment by jgierer12** [comment]
I currently don't have much time to work on RG, I'll reopen this when I have a bit more free time again.

**Comment by bfred-it** [comment]
No worries, that'll be the case for me soon too :)

**Pull request closed without merging**
