### PR TITLE
Meta: Fix typo in PR template

### PR DESCRIPTION
**Pull request by cheap-glitch**

### CODE REVIEW

**Review by yakov116 — APPROVED** [review]

**Comment by fregante** [comment]
No way, how dare they [add](https://www.treccani.it/vocabolario/dimostrativo/) random `n`s? I blame [the French](https://www.larousse.fr/dictionnaires/francais/démonstratif/23463)

**Comment by fregante** [comment]
@cheap-glitch could you send a PR to add https://github.com/cheap-glitch/devlint as a new job in our test.yml workflow? I'm interested to see what it reports. Funnily enough I'm also working on a linter that reads JSON, but it's pretty basic at this point.

**Comment by cheap-glitch** [comment]
> No way, how dare they [add](https://www.treccani.it/vocabolario/dimostrativo/) random `n`s? I blame [the French](https://www.larousse.fr/dictionnaires/francais/d%C3%A9monstratif/23463)

Hey you're the ones who threw away [a perfectly good "n"](http://www.latin-dictionary.net/definition/16545/demonstrativus-demonstrativa-demonstrativum)! You only have yourselves to blame :wink: 

> could you send a PR to add cheap-glitch/devlint as a new job in our test.yml workflow? 

I'll be glad to, but first it needs way more testing. It's barely at 50% coverage at this point...

> I'm interested to see what it reports

What exactly do you want to lint?

I'm asking because my aim is to make a general-purpose linter for everything "meta": that means config files (not just json but also gitignores, .env files, yaml/toml too at some point), plus stuff like directory structure, git repos, readmes, etc.

**Comment by fregante** [comment]
> > No way, how dare they [add](https://www.treccani.it/vocabolario/dimostrativo/) random `n`s? I blame [the French](https://www.larousse.fr/dictionnaires/francais/d%C3%A9monstratif/23463)
> 
> Hey you're the ones who threw away [a perfectly good "n"](http://www.latin-dictionary.net/definition/16545/demonstrativus-demonstrativa-demonstrativum)! You only have yourselves to blame 😉

Italy's so catholic we do away with demons even from unrelated words.

> > could you send a PR to add cheap-glitch/devlint as a new job in our test.yml workflow?
> 
> I'll be glad to, but first it needs way more testing. It's barely at 50% coverage at this point...

Whenever it's ready, if you'd like

> > I'm interested to see what it reports
> 
> What exactly do you want to lint?

The existing rules already look good. Maybe it should ensure that there's at least one CI file or linter in package.json. Or it should ensure that `license` file matches the `license` field in package.json. There are plenty of rules that _could_ exist. I think at the moment it's best to focus on making it work acceptably since it already has quite a few rules.

**Pull request merged**
