### PR TITLE
Add scoped search on user profile page

### LINKED ISSUE #1011: Limit search to current profile (restore feature)
~~Organization pages already limit searches to the current organization:~~

This organization | Search

User profiles should behave the same:

This user | Search

---

This issue replaces #548

2018 edit: this type of search has been dropped from GitHub, this might not be easily possible

### PR DESCRIPTION
**Pull request by ramlmn**
Fixes #1011.

The code still looks a little bit hacky for me, and I'm open for any suggestions!

### CODE REVIEW

**Comment by sindresorhus** [comment]
@ramlmn Looks good. Can you add it to https://github.com/sindresorhus/refined-github#new-features in the readme?

**Comment by ramlmn** [comment]
Done, added the feature to readme!

**Comment by bfred-it** [comment]
If a feature is visible, we usually add screenshots directly

screen shot 2018-01-20 at 23 09 06

**Comment by bfred-it** [comment]
Thanks for writing this, @ramlmn! :)

**Comment by bfred-it** [comment]
@ramlmn this pops in after the first paint, perhaps we can use `safeElementReady` in `init` to have it appear earlier?

**Comment by ramlmn** [comment]
@bfred-it just a little bit busy for now, will test and send a PR soon

**Pull request merged**
