### PR TITLE
Add “Compare to HEAD” link next to `latest-tag-button`

### LINKED ISSUE #2861: Link `latest-tag-button`’s default branch comparison (#2771) to its changelog
#2771 added this piece of information

<table><td></table>

But I think it could be extracted to be its own button linked to its "changelog" view: https://github.com/sindresorhus/refined-github/compare/20.3.4...master

<table><td></table>

However it doesn't look as neat or clear anymore.

Maybe with the diff icon? It's what we use in `changelog-link` as well

<table><td>

### PR DESCRIPTION
**Pull request by yakov116**
Follows #3199
Closes #2861

Waiting for
>Also we need to wait for https://github.com/sindresorhus/refined-github/pull/3205#issuecomment-641926371
>_Originally posted by @fregante in https://github.com/sindresorhus/refined-github/pull/3199_

### CODE REVIEW

**Comment by fregante** [comment]
> Also we need to wait for [#3205 (comment)](https://github.com/sindresorhus/refined-github/pull/3205#issuecomment-641926371)

Only the screenshot needs to wait (many screenshots need to be updated anyway)

**Comment by fregante** [comment]
> Also we need to wait for [#3205 (comment)](https://github.com/sindresorhus/refined-github/pull/3205#issuecomment-641926371)

Only the screenshot needs to wait (many screenshots need to be updated anyway)

**Comment by FloEdelmann** [comment]
@yakov116 You can update the screenshot now, #3221 is merged.

**Comment by yakov116** [comment]
@FloEdelmann if you have the time and can do that would be awesome. 

if not I will do it later tonight

**Comment by yakov116** [comment]
@FloEdelmann 

image


Something is wrong.

**Pull request merged**
