### PR TITLE
Align newsfeed buttons when  `hide-noisy-newsfeed-events`  is disabled

### PR DESCRIPTION
**Pull request by eungyeole**
Issue Number: #4760 

The button was out of position on the github main page.
Therefore, the issue was resolved.

Please comment if there is a problem.

### CODE REVIEW

**Review by fregante — CHANGES_REQUESTED** [review]
This just overrides an existing CSS rule, which means the previous rule is useless now.

The issue here is that you have `clean-dashboard` enabled but `hide-noisy-newsfeed-events` was disabled. If you want to fix this issue, please ensure your fix does not affect `clean-dashboard`. Screenshots will need to be added in this Pr.

**Comment by eungyeole** [comment]
I tested it simply with the code below.
It doesn't seem to affect anything other than follow.

image


```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="./test.css">
</head>
<body class="rgh-clean-dashboard">
    <div class="dashboard">
        <div class="follow">
            <div class="body">
                <div class="js-news-feed-event-group border-bottom">follow</div>
            </div>
        </div>
        <div class="release">
            <div class="body">
                <div class="js-news-feed-event-group border-bottom">test</div>
            </div>
        </div>
    </div>    
</body>
</html>
```

```css
.rgh-clean-dashboard .dashboard .body > .border-bottom {
	margin: 0;
	padding-left: 16px;
	padding-right: 16px;
}

/* When there are two or more following */
.rgh-clean-dashboard .dashboard .follow > .body > .border-bottom {
	padding-right: 16px !important;
}

.rgh-clean-dashboard .js-news-feed-event-group {
	padding-right: 0 !important;
}
```

**Comment by eungyeole** [comment]
I built it myself.but it appears there is no problem.
image

**Comment by fregante** [comment]
> Is it right to want a screenshot like this?

Screenshots always need to be on GitHub itself. They're useful to reviewers to determine whether a PR works as expected. The last screenshot is right. I'd also like to see the current code working when `hide-noisy-newsfeed-events` is disabled

**Comment by fregante** [comment]
My previous review is not addressed at all. The code still overrides this: https://github.com/sindresorhus/refined-github/blob/239636cea448c11c488490badb83c7060e194e35/source/features/clean-dashboard.css#L72-L75

Instead, it's this line that should be changed, probably to:

```scss
.rgh-clean-dashboard.rgh-hide-low-quality-newsfeed-events .js-news-feed-event-group {
	padding-right: 0 !important;
}
```

Because it should only apply when both features are enabled

**Comment by eungyeole** [comment]
image

I found the option and turned it off, but I don't know if it was applied. Do I just need to uncheck it?

image

**Comment by eungyeole** [comment]
And can I know exactly what function 'hide-noisy-newsfeed-events' is?
It says 'Hides other input new safe events (commits, forks, new followers)', but I think I can see new followers and forks well.

**Comment by eungyeole** [comment]
image

This picture is a screen with all the styles below applied.

```css
.rgh-clean-dashboard.rgh-hide-low-quality-newsfeed-events .js-news-feed-event-group {
	padding-right: 0 !important;
}
```

```css
.rgh-hide-noisy-newsfeed-events .news :is(.push, .fork, .delete, .follow, .release) {
	display: none !important;
}
```

**Comment by fregante** [comment]
So yes I identified two issues on `main`:

- follow buttons appear but shouldn't
- buttons inside grouped events lack spacing


### One event ✅ 

Screen Shot 7

### Grouped events ❌ 

Screen Shot 6


### It also applies to Sponsor buttons

Screen Shot 8

**Comment by fregante** [comment]
I think this has been fixed by https://github.com/sindresorhus/refined-github/pull/4764

Leave a comment on the issue if it hasn't

**Pull request closed without merging**
