### PR TITLE
Mention hide-useless-newsfeed-events in the readme

### PR DESCRIPTION
**Pull request by darkred**
For issue #1336 :
- Added a note that any hidden events in dashboard by default is intended and configurable.
- Corrected a few typos.

### CODE REVIEW

**Comment by yakov116** [comment]
I think it should go here rather than in the readme https://github.com/sindresorhus/refined-github/issues/1137

**Comment by bfred-it** [comment]
It should go in the [Declutter section](https://github.com/sindresorhus/refined-github#declutter), next to the two other similar items
> - The dashboard shows more in less space.
> - News feed items of users starring or forking your repos are removed.

And definitely not as a separate extended section with mentions of other issues.

**Comment by darkred** [comment]
@bfred-it 
I hope it's ok now.

Regarding the "passive-aggressive section" :
you've misunderstood me, that was never my intent with this PR, I only wanted to avoid getting more issues regarding this in the future.
I just copied the wording from https://github.com/sindresorhus/refined-github/issues/822#issuecomment-345519824 ...

**Comment by darkred** [comment]
Rephrased a bit and added the detailed reasoning for the hidden Commit entries (formatted the latter with `<sup>`).

**Pull request merged**
