### PR TITLE
Exclude pre-releases from `latest-tag-button`

### LINKED ISSUE #2239: Differentiate between releases and pre-releases
Releases can be created from tags, which can then be further classified as pre-release or the default of the latest release.
Screen Shot 2019-07-15 at 6 47 35 PM

The latest release widget displays a release marked as pre-release as the latest release.
Screen Shot 2019-07-15 at 6 46 31 PM

The API supports the ability to differentiate between the two.
https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository

### PR DESCRIPTION
**Pull request by fregante**
Fixes #2239 

## Tests

I can't find a repo that has pre-releases right now, but I also **included some automated tests** to make sure the algorithm works.

### CODE REVIEW

**Comment by staabm** [comment]
https://github.com/desktop/desktop Has some recent pre-releases

**Comment by fregante** [comment]
And?

**Comment by staabm** [comment]
Nope, I just wanted to let you know a example repo where the feature can be tested

**Comment by fregante** [comment]
The point of this feature is to tell visitors **“the version you’re using is newer than the one shown here”**

Usually people don’t use pre-releases, especially as dependencies, so it would make sense to exclude them

**Comment by fregante** [comment]
Ah you answered my request. Thank you ☺️

**Comment by fregante** [comment]
My bad, I totally misread that comment 🤦‍♂️

**Pull request merged**
