### PR TITLE
Add quick edit functionality for files

### PR DESCRIPTION
**Pull request by devkhan**
I have found the current edit procedure of first opening a file and clicking the edit(pencil icon) link to be little annoying. So, I have added a little code which replaces the current simple text file icon with an edit icon and links to the edit link of the file. _Hope it helps._

Sidenote: I have applied the file filter but how do we detect whether a file is editable or not, e.g. images, binaries, etc.

### CODE REVIEW

**Comment by devkhan** [comment]
@paulmolluzzo Done. 8ee45626321679e97dd3f0495d610c00f43c6e9e

**Comment by sindresorhus** [comment]
Thanks for your suggestion, but this isn't something I'm interested in having.

I've created a wiki page if you want to add it there as a tip: https://github.com/sindresorhus/refined-github/wiki

**Comment by devkhan** [comment]
@sindresorhus I can't edit the wiki. Can you please mention the tweak(in case someone else likes it) and link it to my fork?

**Comment by sindresorhus** [comment]
If you squash it into one commit I'll link to the diff ;)

**Comment by devkhan** [comment]
Here it is: [Quick Edit functionality diff](https://github.com/devkhan/refined-github/commit/6e71836f967c0e3884cf75f381aff83068bc2c20?diff=split&ts=4)

**Comment by sindresorhus** [comment]
The commit title and message isn't very useful. Fix that. I would also recommend the commit include a link to a screenshot of how it would look like. Remember, users are lazy and have short attention. If you don't want people to dismiss it right away, you need to sell it.

**Comment by devkhan** [comment]
I have added a screenshot, and updated the message. I know about the commit messages , but they're squashed and hence, not much helpful. Anyway, [here](https://github.com/devkhan/refined-github/commit/7eb52c8e406aa30294734343b10d7d8188fd8421?diff=unified&ts=4) is it new diff link.
Thanks.

**Comment by sindresorhus** [comment]
Ok, I think it need to be more explicit:

Title:

```
Add a quick edit button for every file in the repo file browser
```

Message

```
Let's you quickly edit files without first having to open them.
```

And don't include the following junk:

```
Screenshot added.
String concatenation -> Template Strings (ES6).
Single quotes. :\
Move constant declaration to top of the function.
Bugfix: icons were not replaced if coming from a non-tree area of the repo. + Build test fixes.
Edit shortcut: Replace file icon with edit icon.
```

**Comment by devkhan** [comment]
Thank you for your effort. Does [this](https://github.com/devkhan/refined-github/commit/51fdf4998fc9392950e932e18018fda870f34666) seems ok?

**Comment by hkdobrev** [comment]
Just to note I'd like to have this just for the readme file on the repo page. You see the readme, but you need to click through to see the edit button, really frustrating.

@devkhan I'd suggest to have these buttons hidden and to be shown just when you hover on the row of a specific file.

**Comment by sindresorhus** [comment]
> Just to note I'd like to have this just for the readme file on the repo page. You see the readme, but you need to click through to see the edit button, really frustrating.

@hkdobrev Haha, get out of my head 😝 I was going to open an issue about that tomorrow.

**Comment by sindresorhus** [comment]
@devkhan Added :)

**Comment by devkhan** [comment]
That seems a better implementation, I'd get to it in a few days. Anyway, thanks @sindresorhus.

**Pull request closed without merging**
