### PR TITLE
Enable `collapse-markdown-sections` on wikis

### PR DESCRIPTION
**Pull request by kidonng**
Possibly wait for fregante/github-url-detection#64

## Test URLs

https://github.com/lukesampson/scoop/wiki

## Screenshot

image

### CODE REVIEW

**Comment by yakov116** [comment]
https://github.com/fregante/github-url-detection/releases/tag/v4.10.0

**Review by fregante — APPROVED** [review]
Untested but LGTM

**Comment by kidonng** [comment]
I added a screenshot above.

**Review by yakov116 — APPROVED** [review]
Tested

**Pull request merged**
