### PR TITLE
Remove Security and Insights from more-dropdown 

### PR DESCRIPTION
**Pull request by galagora**
"Hide", "Insights", and "Releases" were the first things I searched for in the options page.

### CODE REVIEW

**Comment by busches** [comment]
This now lists all the things we add/move to the dropdown, but we don't move everything, compare for example is added.

**Comment by fregante** [comment]
It hides 2 tabs, but it still **adds** 4 links

**Comment by galagora** [comment]
Wow, I completely glossed over that. The original issue that prompted moving them under the dropdown, #2072, is no longer a problem. So I think it's best to just restore the location of the two tabs.

**Comment by fregante** [comment]
If you don't like this feature as is, it can be disabled.

This feature is much older than #2072. Insights used to be its own dropdown with Pulse, Community, and Graphs inside it as seen here: https://github.com/sindresorhus/refined-github/issues/440

In https://github.com/sindresorhus/refined-github/pull/509 we moved one of our tabs inside it and renamed it to "More". The reason for this feature to still exist is that one of Refined GitHub’s intention is to reduce clutter. I don't think many use the Security tab daily.

**Comment by galagora** [comment]
Well, I, for one, use the Insights tab quite often. Nevertheless, the extra options in the dropdown seem useful; I guess I'll just have to write a userscript.

**Pull request closed without merging**
