### PR TITLE
Simplify CSS for the dashboard

### PR DESCRIPTION
**Pull request by ramlmn**
* Simplify CSS without modifying existing behavior
* Use flex-box for reordering elements

### CODE REVIEW

**Comment by sindresorhus** [comment]
Amazing! This also fixes https://github.com/sindresorhus/refined-github/issues/475 for me. Can anyone else confirm?

**Comment by ramlmn** [comment]
@sindresorhus Yes, I can confirm that it fixes that. I already tested it on those elements.

**Comment by ramlmn** [comment]
The only other annoying thing is `padding-top` to `dashboard-sidebar`. Not every user has an organization switcher which leaves a large gap above sidebar.

**Comment by bfred-it** [comment]
Is that something that could also be fixed by using flexbox/grid instead of position absolute?

**Comment by ramlmn** [comment]
That's not possible with plain CSS, because `.account-switcher` and `.user-repos` have different parents. I've already tried it plain CSS.

**Comment by bfred-it** [comment]
Addressed by https://github.com/sindresorhus/refined-github/pull/605 👍

**Pull request merged**
