### PR TITLE
Update style for merge commits

### LINKED ISSUE #1052: Mark Merge Commits feature broken
GitHub changed the style 

Demo page: https://github.com/babel/babel/commits/master?after=ddd40bf5c7ad8565fc990f26142f85613958a329+104

Broken code: https://github.com/sindresorhus/refined-github/blob/373164c7f6cb094db746a44acabee967c7d9aff4/source/features/mark-merge-commits-in-list.js#L8

# Before

screenshot

# After

screenshot

```
Uncaught (in promise) TypeError: Cannot read property 'prepend' of null
    at mark_merge_commits_in_list (content.js:1952)
    at enableFeature (content.js:816)
    at <anonymous>
```

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes #1052

Test on https://github.com/babel/babel/commits/master?after=ddd40bf5c7ad8565fc990f26142f85613958a329+104

Notice: GitHub doesn't show the commit directly below the merge. The merged commit in this case is the third one, **Andarist**'s

merge commit screenshot

### CODE REVIEW

**Comment by sindresorhus** [comment]
It's a little bit weird that the author avatar shows behind the merge icon. The merge icon should not act like an avatar. The tooltip also shows on the merge icon, and it's broken:

screen shot 2018-03-03 at 01 05 17

**Comment by bfred-it** [comment]
I tried putting the icon on the first line but it was hard to align it with the avatar. Not much choice other than making it 2-lines tall, but that'd make merges _more_ visible, not less. Suggestions?

**Comment by sindresorhus** [comment]
How about something like this:

screen shot 2018-03-03 at 01 42 07

You can achieve that by just absolutely positioning the icon with adjusted `top`, and the `padding-left` on the first line. I would also make the merge icon smaller than in my above screenshot.

**Comment by bfred-it** [comment]
This is what I'm talking about. Does it look aligned?



Because it basically is 😅

**Comment by sindresorhus** [comment]
Yeah, I get it now, but I can't think of a better way to present it either.

**Comment by sindresorhus** [comment]
Do we really need the icon at all?

**Comment by bfred-it** [comment]
Wellllll... it _is_ more refined

**Pull request merged**
