### PR TITLE
Hide the fork count only on smaller screens

### PR DESCRIPTION
**Pull request by yakov116**
Re https://github.com/sindresorhus/refined-github/issues/4197#issuecomment-816628465

## Test URLs
https://github.com/sindresorhus/refined-github

## Screenshot
Video_2021-04-16_102042

### CODE REVIEW

**Review by fregante — APPROVED** [review]
cc @sindresorhus

**Comment by yakov116** [comment]
@sindresorhus ?

**Review by sindresorhus — APPROVED** [review]
I don't find the fork count useful at all, but I also don't feel strongly about hiding it, so this is fine by me.

**Comment by fregante** [comment]
Yeah the count is useless, but the link points to the useful fork network. It was suggested to add a link to the network in `more-dropdown` but at that point we'd just be adding further code for little benefit, so I just suggested we restore this count.

**Pull request merged**
