### PR TITLE
Feature/Measurement Git Repo/file Size on Github Using Github GraphQL API

### PR DESCRIPTION
**Pull request by dongs0104**
This feature was inspired by https://github.com/harshjv/github-repo-size
Almost web extension about repo-size doesn't work in the GHE so i rewritten using GraphQL API.

### CODE REVIEW

**Comment by bfred-it** [comment]
I used to use that extension but I never found it particularly useful. I suggest publishing this as a separate extension, if the owner of `github-repo-size` is not responding.

**Comment by sindresorhus** [comment]
I don't really see the usefulness of this either.

**Comment by laowantong** [comment]
To this date, https://github.com/harshjv/github-repo-size has 620 stars, and 11 615 users on the Chrome web store. IMHO, that's a lot of people.

**Comment by ShalokShalom** [comment]
I would even go as far to ask for a sorting feature,  so that allows us to sort by size,  date or name.  Why not? Thanks

**Comment by fregante** [comment]
> To this date, [harshjv/github-repo-size](https://github.com/harshjv/github-repo-size) has 620 stars, and 11 615 users on the Chrome web store. IMHO, that's a lot of people.

Right, that's why you should use that extension instead. There's no point in adding all the features here.

**Comment by laowantong** [comment]
Ok, you convinced me.

However, since I don't want to use Chrome, I guess I will have to wait until GitHub implements this feature.

Thanks for you hard work!

**Comment by fregante** [comment]
You might be able to download and install the extension on Firefox anyway. With a bit of convincing you could get the author to also publish to Mozilla Addons (you can do the same thing autonomously thanks to the MIT license)

**Comment by ShalokShalom** [comment]
You could also say this about all the other add ons, that got integrated, how do you differentiate here?

**Comment by fregante** [comment]
We've been rejecting those requests more often since this summer, basically coming to this conclusion: if it exists, use that. The more features we (needlessly add), the more we have to support.

**Comment by aprochet** [comment]
While IMO this is really basic functionality that should be integrated, I found an excellent AddOn for Firefox called Enhanced Github that does the trick. There is also at least one equivalent for Chrome.

**Pull request closed without merging**
