### PR TITLE
Use a consistent border color

### PR DESCRIPTION
**Pull request by ocarreterom**
- move border color to CSS variable
- normalize gray border color to `#e1e4e8`

Thanks for contributing! 🍄

1. LINKED ISSUES:
   No issue

2. TEST URLS:
   https://github.com/ (dashboard)

3. SCREENSHOT:
The border after "All activity" was darker.
<table>
<tr>
	<td>Before
	<td>After
<tr>
	<td>Captura de pantalla 2020-10-16 a las 1 07 09
	<td>Captura de pantalla 2020-10-16 a las 1 06 46
</table>

### CODE REVIEW

**Comment by yakov116** [comment]
Can you please provide before and after screenshots

**Comment by ocarreterom** [comment]
> Can you please provide before and after screenshots

Done! It's a subtle change 😅

**Comment by fregante** [comment]
I have to double check but I think that works! Thank you!

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
cc @silverwind heads up for updated CSS colors

**Comment by silverwind** [comment]
Should probably be automatically handled by our tooling. BTW GitHub now has CSS vars of their own, you should switch to them (for example `--color-border-primary` for your border).

**Comment by silverwind** [comment]
Automation picked it up just fine: https://github.com/StylishThemes/GitHub-Dark/commit/badb3c94ee4f5574b47b566c7c975385ceae66af

**Pull request merged**
