### PR TITLE
Add "Wait for successful checks" checkbox

### LINKED ISSUE #865: Add auto merge after tests pass button
Sometimes a PR is ready to merge, but you want to wait for the tests to pass, it would be nice to have a button that said "Merge when tests pass", if pressed, we should poll the button for the class that makes it green and just press it when it turns green.

I can make a PR if you like the idea, otherwise close and I'll make it a bookmarklet instead.

### PR DESCRIPTION
**Pull request by bfred-it**
Closes #865 

demo

Notes:

- The checkbox is shown only when there's a pending commit
- The checkbox is checked by default
- While waiting, the form is disabled
- While waiting, closing the tab requires a confirmation
- If a new commit is pushed while waiting, the waiting stops (i.e. form re-enabled, no action taken)
- If the checks fail, the waiting stops

Caveats:

- GitHub's UI can be finnicky, it doesn't always update (side note: the large "merge details" form does not update at all when the "confirm merge" form is open, but it doesn't affect the feature because I use the single commit's icon)
- Secondary features like branch deletion and comment submission can be added separately, so at least we can see how well this performs.

This was way more involved than I had anticipated.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> While waiting, closing the tab requires a confirmation

I didn't get any confirmation. The tab just closed as normal. (Chrome)

**Comment by sindresorhus** [comment]
Otherwise, seems to work perfectly though. And this is super useful!

**Comment by bfred-it** [comment]
I can have a warning when the user tries to close the tab or navigates to a new website, but not when GitHub tries to navigate to an ajaxed page. I could **detect it, warn the user and abort the submission**, but **not ask for confirmation**. Implementation suggestions?

**Comment by sindresorhus** [comment]
Awesome!

@bfred-it Do you wanna do a tweet about this feature with the above GIF? So I can retweet. Otherwise, I will.

**Comment by bfred-it** [comment]
Sure! I guess this can also be added to the highlights in the readme

**Comment by bfred-it** [comment]
By "Sure" I mean you can tweet it 😄

**Comment by gaillota** [comment]
Quick feedback: This feature blocks the merge even when there's only non-required checks remaining (eg. A deploy approval that you don't need). 

Maybe the feature can be updated to block only while required checks are not met ?

**Comment by bfred-it** [comment]
Can you give me a screenshot of that?

**Comment by waldyrious** [comment]
FYI, clicking the help button next to the checkbox, which I thought would show a modal box or tooltip with some info, actually took me straight to this issue, making me lose the changes to the commit message I had composed prior to the merge. Is this being tracked somewhere, or should I open an issue?

**Comment by busches** [comment]
Open an issue please.

**Comment by jesstelford** [comment]
It just hangs for me :(

I thought I'd successfully merged, but later realised I hadn't when I opened a new tab...

---

`hanging`
screen shot 2018-09-26 at 3 29 44 pm

---

`new tab`
screen shot 2018-09-26 at 3 32 03 pm

_(note: I blanked out the details)_

**Comment by jesstelford** [comment]
Can I suggest this option be unchecked by default to prevent issues like this and the one reported above?

**Comment by jesstelford** [comment]
> both screenshots show it merged

Yes, that's the problem: in the first screenshot, it shows it as merged, but when I opened a second tab to look at the page fresh; it _wasn't_ merged.

I clicked "merge" again in the second tab and took the second screenshot. Meanwhile the first tab continued to hang without updating the "Merge" button / surrounding UI.

Is; if I'd not opened a second tab, the first would have just hanged forever on the screen in the first screenshot, _but never actually merge_.

**Comment by busches** [comment]
If you can get another example, I think that'd be helpful. Both screenshots show it being merged at 21 minutes ago from the comment, which means it looks like the process did work or something odd happened on the GH side, since RGH does not add the merged commit message, but GH does.

**Comment by jesstelford** [comment]
My apologies, I misunderstood the area of the screenshot you were referring to. I see now that you mean the `jesstelford merged commit X into Y Z minutes ago`, and not the `[Confirm Merge] ☑ Wait for successful checks`.

That adds another interesting layer!

To clarify the steps of what happened, I'll itemise them:

#### 1 - Ready to merge

I saw that all my PR's checks had passed, and the `[Merge]` button was green (we've configured the repo to block merging unless checks are green).

I clicked `[Merge]`

#### 2 - Confirm merge

The button then changed to

> `[Confirm Merge] ☑ Wait for successful checks`

So I clicked `[Confirm Merge]`

#### 3 - Waiting

The `[Confirm Merge]` button greyed out, and I saw a screen like this (note: this is an edited screenshot):

Waiting for checks that are already complete

#### 4 - New tab

After reading the docs for `☑ Wait for successful checks`, I decided to open the PR in a new tab because things seemed to be hanging on the original tab.

In the new Tab, I saw the same UI from step 1: a `[Merge]` button. No indication of the PR having been merged, and all checks were still green.

#### 5 - Merge again

In the new tab, I clicked `[Merge]` followed by `[Confirm Merge]`, and instantly saw the following screen:

Successful merge

#### 6 - Still waiting

I checked the original tab, and noticed the `[Confirm Merge]` button was still visible as if it was still waiting for a check to complete, but it did show `jesstelford merged commit X into Y Z minutes ago`:

Still waiting even after a merge

---

I'll try get more granular screenshots for the next PR I do and will report back if it happened again 👍

**Pull request merged**
