### PR TITLE
Use native copy buttons

### PR DESCRIPTION
**Pull request by bfred-it**
1. Merges `copy-gist` and `copy-file` features
2. Uses the native `zeroclipboard` feature by GitHub
3. Creates a `BtnGroup` for the copy-gist button for a native look

## Test pages

File: https://github.com/sindresorhus/refined-github/blob/master/license
Gist: https://gist.github.com/addyosmani/fd3999ea7fce242756b1

### CODE REVIEW

**Comment by bfred-it** [comment]
Why: `zeroclipboard` offers feedback with a tooltip while the previous implementation feels like nothing happens when pressing the button.

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by bfred-it** [comment]
Rebased

**Comment by sindresorhus** [comment]
Looks good :)

**Pull request merged**
