### PR TITLE
Shorten "Pull Requests" tab to "PRs"

### LINKED ISSUE #440: Repo tabs doesn't fit when Wiki and Projects tabs are enabled
screen shot 2017-05-25 at 14 43 49

Maybe we should renamed `Insights` to `More` and move `Settings` there too?

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes #440

# Before

screen shot 2017-06-17 at 18 58 03

# After

screen shot 2017-06-17 at 18 58 19

# Also tested with long counters

screen shot 2017-06-17 at 19 00 39

### CODE REVIEW

**Comment by bfred-it** [comment]
Also we can rename Insights to Stats

**Comment by hkdobrev** [comment]
@bfred-it What do you think of doing it only when all of the tabs are available? This way it will say Pull requests in the majority of the cases, but for people using everything including Projects on their own repositories there would be a different tab on some repos.

**Comment by sindresorhus** [comment]
Wouldn't it be better to just move "Compare" to the Insights dropdown and rename it when it overflows. That way "Pull requests" is always consistent.

**Comment by bfred-it** [comment]
I don't know, I don't mind it being PRs all the time. That's what we refer them to anyway.

**Comment by sindresorhus** [comment]
> Rename what?

As suggested in https://github.com/sindresorhus/refined-github/issues/440#issuecomment-303984573, rename it to `More`.

That's also more future proof, in case GitHub adds more native tabs in the future.

**Comment by hkdobrev** [comment]
BTW GitHub just added "Community" to the "Insights" tab for open-source repositories where you're an admin. The whole community thing is great, but it has nothing to do with "Insights" for me, so 👍 on renaming "Insights" to "More".

**Pull request closed without merging**
