### PR TITLE
Unify reponav-dropdown creation

### PR DESCRIPTION
**Pull request by bfred-it**
After https://github.com/sindresorhus/refined-github/pull/739 the dropdown creation was getting lengthy. It made sense to merge all the related code.

Current output unchanged:

screen shot 2017-10-25 at 16 19 46 (before settings tab)
screen shot 2017-10-25 at 16 19 50 (no settings tab)

### CODE REVIEW

**Comment by busches** [comment]
Looks good on GHE too.

**Comment by bfred-it** [comment]
Excellent! I was waiting for you exactly. :D 

Thank you! Do you want to join Refined GitHub as a collaborator?

**Comment by busches** [comment]
Sure, then I can give the fancy seal of approval. :wink:

**Comment by bfred-it** [comment]
Pinging Dr. @sindresorhus to sign the document.

**Comment by sindresorhus** [comment]
@busches Awesome. Glad to have you on board :)

**Pull request merged**
