### PR TITLE
Clean fork events in `clean-dashboard`

### PR DESCRIPTION
**Pull request by cheap-glitch**
1. LINKED ISSUES: -

2. TEST URLS: the homepage dashboard

3. SCREENSHOT:

<table>
<tr>
	<th> Before
	<td>

Screenshot_2021-02-28 Build software better, together
<tr>
	<th> After
	<td>

Screenshot_2021-02-28 Build software better, together(1)
</table>

### CODE REVIEW

**Comment by fregante** [comment]
Hmmm I think they’re meant to be completely hidden, not just cleaned. There’s a specific feature for that

**Comment by cheap-glitch** [comment]
True, this is only useful if `hide-useless-newsfeed-events` is disabled.

**Comment by fregante** [comment]
Yeah we don’t merge features that require other features to be disabled in order to be tested

**Comment by fregante** [comment]
@yakov116 this selector is a good candidate for :is, even if it requires wrapping, because the :is is in the middle of each selector

**Pull request closed without merging**
