### PR TITLE
Markdown copy improvements

### LINKED ISSUE #522: 'Copy to Markdown' improvements
Related to #486 and #487
- [x] Images with a `width` or `height` attribute set needs to be converted back to an `` as Markdown images can't have a width/height
- [ ] ~~Mentions should not be converted to links~~
- [x] Copying a rendered emoji (🔥🔥🔥) in Chrome on macOS results in: `<g-emoji alias="fire" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f525.png" ios-version="6.0" title=":fire:">🔥</g-emoji><g-emoji alias="fire" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f525.png" ios-version="6.0" title=":fire:">🔥</g-emoji><g-emoji alias="fire" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f525.png" ios-version="6.0" title=":fire:">🔥</g-emoji>` We should strip out all the junk and just copy the character.

### PR DESCRIPTION
**Pull request by bfred-it**
Mostly fixes #522. There's only [one left](https://github.com/sindresorhus/refined-github/issues/522#issuecomment-310547556) and that's hard to fix.

Edit: **Automated tests have been [added](https://github.com/sindresorhus/refined-github/pull/546/commits/75ad7c36a28fdc7827ee67e32c95a923f227e168) ⚡️**

## Manual tests

✅ Drop `g-emoji` elements: 🔥🔥🔥
✅ Drop tasks from lists
 - [ ] try me out
 - [x] test across lines

✅ Drop autolinks around images: 
✅ Keep `` if it has width, height or align: copy
✅ Unwrap commit/issue autolinks: #522 833d5984fffb18a44b83d965b397f82e0ff3085e
✅ Unwrap **some** shortened links: https://www.npmjs.com https://twitter.com/bfred_it https://github.com/

✅ Wrap orphaned `li`s in their original parent:

- try selecting text from ➡️ here
- to ⬅️ here
- before this, the copied text would have been "➡️here*   to⬅️" without linebreaks

✅ Add support for `ol` lists that start after 1:

99. big lists
100. deserve big numbers

✅ Keep the original number of orphaned `li`s in numbered lists:

1. If you start copying
2. some text from ➡️here
3. to ⬅️ here
4. the copied text should start with `2. here` not, `1. here`

### CODE REVIEW

**Comment by bfred-it** [comment]
Tests added for all except -1 and -3 because they depend on the dom — which is not testable because jsdom [doesn't support Ranges yet.](https://github.com/tmpvar/jsdom/issues/317)

**Comment by hkdobrev** [comment]
The PR description rocks! I'll try to test it out tomorrow.

**Comment by sindresorhus** [comment]
Works great for me. Really nice work @bfred-it (as always!) 🙌

**Comment by bfred-it** [comment]
I'm wondering if this should be extracted from Refined GitHub as its own extension.

Related: we could add _sister extensions_ also in the options, so more people will see the essential [Hide Files on GitHub](https://github.com/sindresorhus/hide-files-on-github), [Octo Linker](https://github.com/octo-linker/chrome-extension/), and [npmhub](https://github.com/npmhub/npmhub/)

**Comment by sindresorhus** [comment]
@bfred-it I dunno. I would only use it on GitHub anyways. I do think a lot of the logic here should be extracted out into a node module though or more upstreamed to `to-markdown`.

**Comment by sindresorhus** [comment]
> Related: we could add _sister extensions_ also in the options, so more people will see the essential [Hide Files on GitHub](https://github.com/sindresorhus/hide-files-on-github), [Octo Linker](https://github.com/octo-linker/chrome-extension/), and [npmhub](https://github.com/npmhub/npmhub/)

👍

**Comment by bfred-it** [comment]
Yeah it'd be GitHub-specific anyway, I don't want to copy markdown anywhere else.

Not sure about npm since most of these are very specific to to-markdown and to GitHub.

`ol[start]` support has been [moved to to-markdown](https://github.com/domchristie/to-markdown/pull/187) but I'm hesitant to make more PRs since [it's being deprecated.](https://github.com/domchristie/to-markdown/pull/172#issuecomment-305871474)

**Comment by sindresorhus** [comment]
@bfred-it Just create a new module that wraps `to-markdown` with our own logic. Big rewrites like the planned `to-markdown` one usually go nowhere, and they end up having two unmaintained projects.

**Comment by bfred-it** [comment]
I think we're good this way. I don't want to support that package separately, here at least we have the luxury of possibly replacing to-markdown altogether and forget about it.

**Comment by sindresorhus** [comment]
Yup

**Pull request merged**
