### PR TITLE
Setup completely automatic deployment

### PR DESCRIPTION
**Pull request by bfred-it**
In the browser, only the latest version is ever supported and there is no concept of _breaking_ because there are no dependents. Semver doesn't apply.

Currently the deployment steps are:

1. Update the version in `extension/manifest.json`
2. Create a commit for it
3. Create a tag with the same version

Instead of waiting for the tag, with this PR every push to master is deployed.

The version is automatically set to the UTC datetime of the deploy: e.g. 17.6.18.1256

The only minor drawback is that you'll get an email from Mozilla after every accepted release — but that's an email filter away.

### CODE REVIEW

**Comment by bfred-it** [comment]
The `update-version` script is meant to be run on travis only; it's changes won't be committed.

**Comment by sindresorhus** [comment]
> The only minor drawback is that you'll get an email from Mozilla after every accepted release — but that's an email filter away.

Doesn't Mozilla do manual reviews?

**Comment by bfred-it** [comment]
Not anymore, they automated it recently because the queue was getting way too long. Perhaps they only review some. My updates get pushed within an hour now.

**Comment by sindresorhus** [comment]
Alright, I'm good with this, but let's keep this open until the next release. I'd like to do one more tagged release on Wednesday.

**Comment by bfred-it** [comment]
👍

**Comment by sindresorhus** [comment]
@hkdobrev @jgierer12 @paulmolluzzo Thoughts?

**Comment by jgierer12** [comment]
👍

**Comment by bfred-it** [comment]
FYI, merging this should trigger the deployment right away. 

Also, deployments can be avoided with `[ci skip]` or by stopping the deploy on Travis, should that be necessary (rarely should be, since we approve each PR)

**Comment by bfred-it** [comment]
Good to go?

**Comment by sindresorhus** [comment]
Yup

**Pull request merged**
