### PR TITLE
Fix `releases-tab` when `more-dropdown` is disabled

### LINKED ISSUE #2361: `releases-tab` does not work without `more-dropdown`
When `more-dropdown` is disabled or have failed to initialize due to an error,
`releases-tab` fails to inject.
It's not really a bug, but rather an enhancement request - to make `releases-tab` isolated.

`more-dropdown` enabled + `releases-tab` enabled:
image

`more-dropdown` disabled + `releases-tab` enabled:
image

Error in console:
```
❌ releases-tab
content.js:2709 TypeError: Cannot read property 'before' of null
    at releases_tab_init (content.js:3509)
    at async features_run (content.js:2704)
```

### PR DESCRIPTION
**Pull request by kidonng**
Closes #2361 

# Test

- [x] Repo without admin access
- [x] Repo with admin access

### CODE REVIEW

**Comment by sharkykh** [comment]
Test this on a repo with admin access, I believe the releases tab should be before "Settings".
Right now "Settings" is always the last nav item...

**Comment by kidonng** [comment]
I forgot the settings button. Solved that.

**Comment by sharkykh** [comment]
Well, now this won't work for repositories where you don't have admin access 😅

Also need to consider that this won't work as expected if the repository name ends in `settings`, like:
https://github.com/probot/settings
https://github.com/ledermann/rails-settings
(The selector would select the `Code` nav link)

**Comment by kidonng** [comment]
> Well, now this won't work for repositories where you don't have admin access 😅

Does it? Works fine on my browser...

**Comment by sharkykh** [comment]
> > Well, now this won't work for repositories where you don't have admin access 😅
> 
> Does it? Works fine on my browser...

I haven't actually tried, just looked at the code - How could this work if there is no link that ends in `settings` when you don't have admin access?

**Comment by kidonng** [comment]
It's handled by the util:

https://github.com/sindresorhus/refined-github/blob/0b2400511c28c9e22edbfc18770f113eafcecfc4/source/libs/dom-utils.ts#L25-L37

**Comment by kidonng** [comment]
> Also need to consider that this won't work as expected if the repository name ends in `settings`

Note that the code will only select direct children, so it's fine.

P.S. I spent some time figure out why it doesn't work https://github.com/probot/settings you give, and eventually realized it has no release 🤣

**Comment by tunnckoCore** [comment]
Just to mention, it's probably not exactly related to this PR but today I noticed that `more-dropdown` is kind of bugged and was always showing the dropdown, so I disabled it.

**Comment by deadpyxel** [comment]
@tunnckoCore That was reported in #2357 

@kidonng made #2359 to solve it.

**Comment by tunnckoCore** [comment]
Ah, cool. Sorry for messing here, but didn't find it earlier :)

**Comment by fregante** [comment]
We’re not gonna support all combinations of supported features.

**Pull request closed without merging**
