### PR TITLE
Highlight linked issue comment

### LINKED ISSUE #1164: Highlight linked comment (:target)
Visit:

```
https://github.com/sindresorhus/refined-github/issues/1069#issuecomment-370729777
```

Should be highlighted:

> yellow comment

This style can be achieved via `unread-item` class on the `.timeline-comment` element, but we can probably just copy-paste their style under a `:target` rule so it works without any JavaScript.

### PR DESCRIPTION
**Pull request by salmanulfarzy**
Highlight linked issue comments with `:target` and modified color. Hope this is what you expected @bfred-it. 

Test comment : https://github.com/sindresorhus/refined-github/pull/988#issuecomment-357531152
highlight linked issue

Close #1164

### CODE REVIEW

**Comment by salmanulfarzy** [comment]
Not sure whether related, But reaction avatars of linked comments are back to default GitHub style 😕 

Test comment: https://github.com/sindresorhus/refined-github/issues/1122#issuecomment-370383235

highlight linked issue regression

**Comment by bfred-it** [comment]
It should probably include _all_ the rules from GitHub, to make sure it works in every case. We can just pick the coloring properties and drop the rest. Their code is:

```css
.timeline-comment-wrapper .timeline-comment.unread-item::after,
.timeline-comment-wrapper .timeline-comment.unread-item::before {
    position: absolute;
    top: 11px;
    right: 100%;
    left: -16px;
    display: block;
    width: 0;
    height: 0;
    pointer-events: none;
    content: " ";
    border-color: transparent;
    border-style: solid solid outset
}

.timeline-comment-wrapper .timeline-comment.unread-item::after {
    margin-top: 1px;
    margin-left: 2px;
    border-width: 7px;
    border-right-color: #fffdef
}

.timeline-comment-wrapper .timeline-comment.unread-item::before {
    border-width: 8px;
    border-right-color: #e5d999
}
.timeline-comment.unread-item {
    border-color: #e5d999
}

.timeline-comment.unread-item .timeline-comment-header {
    background-color: #fffdef;
    border-bottom-color: #e5d999
}

.timeline-comment.unread-item .timeline-comment-label {
    border-color: #e5d999
}

.timeline-comment.unread-item .previewable-comment-form .comment-form-head.tabnav {
    color: #e5d999;
    background-color: #fffdef;
    border-bottom-color: #e5d999
}
```


This is how linking my own comments look like:

own comment


And this is what it should look like (screenshot made with `.unread-item`)

own comment, correct colors

**Comment by hkdobrev** [comment]
@bfred-it Wouldn't using JS enable the functionality from GitHub where the custom styling disappears after a bit?

**Comment by bfred-it** [comment]
I don't see why that would be desirable; the comment should be colored as long as the `:target` points to it, like the rest of the site (e.g. permalinked code)

**Comment by salmanulfarzy** [comment]
Updated with suggested modifications. But few questions about it,

- Should we modify the color of border around reactions ?
- Can't find a selector to change color for `::before` with `.current-user`. Current selector affects all the comments by user on thread. 

highlight issue comment before error

**Comment by bfred-it** [comment]
I posted the whole code, there's a couple `::before`/`::after` selectors there that I don't see in your commits. All of that needs to be in there or else we're just playing whack-a-mole.

**Comment by salmanulfarzy** [comment]
I'm extremely sorry for overlooking `::after`, Will make the necessary modifications.

**Comment by bfred-it** [comment]
Each selector needs `:root` at the start otherwise it's not strong enough to override the `.current-user` style.

**Comment by bfred-it** [comment]
Screenshot for readme

**Comment by bfred-it** [comment]
Thanks for your PR, @salmanulfarzy!

By the way this is particularly useful when opening notifications because now the least recent unread comment will be highlighted (because the notifications link to it)

**Comment by yakov116** [comment]
@salmanulfarzy thank you so much! this has been a real help for me!

**Pull request merged**
