### PR TITLE
Fix some minor icon color and position issues

### LINKED ISSUE #4625: Icon position and color issues
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

- `first-published-tag-for-merged-pr` is a little lower compared to the native copy button

  image

- `conversation-activity-filter` (or perhaps it's `first-published-tag-for-merged-pr`, not sure) icon in the sticky header has wrong color
  
  image

  EDIT: it seems both icon don't match with the native copy button:

  - Copy button: `rgb(88, 96, 105)`
  - `first-published-tag-for-merged-pr`: `rgb(106, 115, 125)`
  - `conversation-activity-filter`: `rgb(36, 41, 46)`

- (Not a bug, this is a little opinionated) `conversation-activity-filter` can have a larger left margin if it follows the comment count

  image

### Screenshot

See above

### Console errors

_No response_

### Example URL

https://github.com/sindresorhus/refined-github/pull/4029

### Browser(s) used

Chrome

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #4625 

## Test URLs

* [Open issue](https://github.com/sindresorhus/refined-github/issues/4008)
* [Released PR](https://github.com/sindresorhus/refined-github/pull/4487)

## Screenshot

Fixed horizontal spacing between comments count and eye icon:

image

Fixed icons color and vertical alignment of tag icon:

image

### CODE REVIEW

**Comment by fregante** [comment]
Untested but the changes look reasonable (as opposed to just pixel-based push/pull/vertical-align stuff 😃)

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
I just realized something… why is the eye outside the main container? It should be after the date to avoid changing position when the tag loads

**Comment by cheap-glitch** [comment]
> I just realized something… why is the eye outside the main container? It should be after the date to avoid changing position when the tag loads

Is it really worth it? It's not a trivial change, plus it makes the UI less readable, and also less consistent since the eye icon would not always be at the end of the line.\
Is the filter feature even that useful on these pages, where the PRs are merged and old enough to have been released?

**Comment by fregante** [comment]
We can merge this as is, but yes it's still worth it

**Pull request merged**
