### PR TITLE
Fix a couple of issues with GitHub Dark mode

### LINKED ISSUE #3798: Support for Github Darkmode
When using Refined Github with the new Github Darkmode the Activity List is rendered with a white background.

https://imgur.com/a/uy8K50q

### PR DESCRIPTION
**Pull request by mcornella**
1. LINKED ISSUES:
  Corrects some issues in #3798

2. TEST URLS:
   Just the [main dashboard](https://github.com/) (see while logged in).
   Also you need to have enabled Dark mode in [Settings](https://github.com/settings/appearance).

3. SCREENSHOTS:
	<details>
	<summary>With Dark mode (fixed)</summary>
	
	_**Before**_
	Before screenshot
	
	_**After**_
	After screenshot
	</details>
	
	<details>
	<summary>With Light mode (the same)</summary>
	
	_**Before**_
	Before screenshot
	
	_**After**_
	After screenshot
	</details>

Tested via custom CSS, with the following snippet:
```css
.dashboard .js-all-activity-header + div {
	background-color: var(--color-bg-canvas);
	border: 1px solid var(--color-border-primary);
}
```

### CODE REVIEW

**Review by fregante — APPROVED** [review]

**Review by yakov116 — APPROVED** [review]

**Comment by fregante** [comment]
Thanks for both fixed! I’ll deploy this as a hotfix because it’s bothering a few people ✌️

**Comment by szepeviktor** [comment]
I still have some white ones

kép

Please advise

**Comment by kidonng** [comment]
@szepeviktor Did you update Refined GitHub and clear your browser cache?

**Comment by szepeviktor** [comment]
> Verzió 20.12.9

But my cache is still warm.

Clearing right now...

**Comment by szepeviktor** [comment]
Done.

kép

Still some white objects...

**Comment by kidonng** [comment]
It should have round avatars:

image

There are probably some other extensions that caused this. You may need to test with a new browser profile.

**Comment by szepeviktor** [comment]
You are right, it is https://github.com/daattali/oldschool-github-extension/issues/39

I still want square everything but @sindresorhus denied it https://github.com/sindresorhus/refined-github/issues/3268

**Pull request merged**
