### PR TITLE
Add Firefox support

### LINKED ISSUE #71: Firefox port
Though the future of extension system of Firefox isn't clear, but I guess with advent of [WebExtensions](https://wiki.mozilla.org/WebExtensions) it would be fairly easy to port the extension for Nightlies. 

---

See #403 for progress on this.

### PR DESCRIPTION
**Pull request by jgierer12**
Fixing the things that don't work on Firefox yet:

- [x] Improves readability of tab indented code (62f0c9f9650ac579a2a9da52883f9af857032858)
- [x] Adds labels to comments by original poster (#376)

Fixes #71 

Once these are fixed, we can look into [publishing it](https://addons.mozilla.org/en-US/developers/) into the Add-on Store

### CODE REVIEW

**Comment by jgierer12** [comment]
@AdrianoCahete @bogas04 @jdreesen do you want to take a look at this? Let me know if you find anything else that doesn't work in Firefox

**Comment by AdrianoCahete** [comment]
I expect to test this weekend.

**Comment by hkdobrev** [comment]
@AdrianoCahete Have you had the chance to test this out?

**Comment by hkdobrev** [comment]
@jgierer12 Just notifying you of https://github.com/sindresorhus/refined-github/pull/414#issuecomment-300274945

**Comment by AdrianoCahete** [comment]
> Have you had the chance to test this out?

Sorry, I'm in the last release week in work, i didn't have time yet. :(

**Comment by jgierer12** [comment]
Just collecting some links about publishing to AMO:
https://developer.mozilla.org/en-US/Add-ons/Distribution
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference
https://github.com/mozilla/web-ext/issues/804
https://github.com/npmhub/npmhub/issues/20

**Comment by jgierer12** [comment]
After using this add-on on Firefox for a while now, I think we're ready to merge & submit to AMO. Going by https://github.com/npmhub/npmhub/issues/20, it can take quite a while until an add-on gets approved, so I added manual installation instructions to the readme. We'll also have to look into [web-ext](https://github.com/mozilla/web-ext) for automatic deployment.

**Comment by bfred-it** [comment]
For reference, this is how we've done it for npmhub:

- [.travis.yml](https://github.com/npmhub/npmhub/blob/0b3040a212027cc4fd4910a98ee0e478633480ef/.travis.yml#L6-L13)
    
    ```yml
    env:
      - EXTENSION_ID=kbbbjimdjbjclaebffknlabpogocablj
    deploy:
      provider: script
      skip_cleanup: true
      script: npm run update-version; npm run release-cws; npm run release-amo
      on:
          branch: master
    ```

- [package.json](https://github.com/npmhub/npmhub/blob/0b3040a212027cc4fd4910a98ee0e478633480ef/package.json#L16-L18)

    ```json
    {
        "scripts": {
          "test": "xo && web-ext lint",
          "release-amo": "OK='Your add-on has been submitted for review.'; web-ext sign -s extension | sed -n \"s/\\($OK\\).*$/\\1/;1,/$OK/p\" | perl -pe 'BEGIN { $s=1 } END { exit $s } $s=0 if /'\"$OK\"'/;'",
          "release-cws": "webstore upload --source=extension --auto-publish",
          "update-version": "dot-json extension/manifest.json version $(date -u +%Y.%-m.%-d.%-H%M)"
        }
    }
    ```

**Comment by sindresorhus** [comment]
Looks good.

@jgierer12 Can you open an issue/PR about automatic update submission?

**Pull request merged**
