### PR TITLE
Fix `widen-search-field` feature

### PR DESCRIPTION
**Pull request by joak46**
Follows #2436 
# Test

https://github.com/issues
https://github.com/pulls
https://github.com/sindresorhus/refined-github/issues
https://github.com/sindresorhus/refined-github/pulls

<details>
<summary>Previous content</summary>

### Test link
[Issues](https://github.com/sindresorhus/refined-github/issues)
[Pull Requests](https://github.com/sindresorhus/refined-github/pulls)
[Labels](https://github.com/sindresorhus/refined-github/labels)
[Releases](https://github.com/sindresorhus/refined-github/releases)

### Issue page
issue

### Pull requests page
pull

### Labels page (my repository)
label

### Labels page
other-label

### Releases page (forked repository)
releases

</details>

### CODE REVIEW

**Comment by fregante** [comment]
Thanks for the PR! However the intent of `widen-search-field` is to... make the search field longer. I don't see that in your screenshots. It should look like this:

**Comment by joak46** [comment]
@fregante mine is that short all the time, like normal github

**Comment by fregante** [comment]
> @fregante mine is that short all the time, like normal github

That's the point. Refined GitHub should make it longer.

**Comment by joak46** [comment]
@fregante these custom css works for me, others place above remains works as well

### Custom CSS
search

## Issues
issue

## Pull Requests
pull

**Comment by fregante** [comment]
Can you update this PR with the required code?

**Comment by joak46** [comment]
@fregante added, test passed too, all good

**Comment by fregante** [comment]
I think that there's a lot of overlap between the rules now, some rules are just undoing the previous rules and some rules no longer apply. Also the comments need to be fixed and shortened, don't add linebreaks unless it's a new different sentence.

**Comment by joak46** [comment]
@fregante i shorten comments

I already commented what those rules i add are doing.

The old `.subnav .float-right {` rule on line 14 for those buttons `Select tag`, `Draft a new release` on the right of Releases page

**Comment by fregante** [comment]
> I already commented what those rules i add are doing.

You might have misunderstood. By **undoing** I meant that the first rule sets `flex-grow: 1` and then your new rule **resets** it to `flex-grow: 0`. This PR should just make sure that `flex-grow: 1` is not applied there at all, instead of **adding it and undoing it** later.

You can see this in the developer tools:



I think all your new code justs _undoes_ something that the old code _does_. Instead, you should just fix the old code.

**Comment by joak46** [comment]
@fregante but you said `.subnav` is all over place, so i can't delete it, just apply on those button T.T

**Comment by joak46** [comment]
@fregante i think remove `.subnav` at line 2, remove `.subnav > :first-child:not(a) {` on line 24

Replace with
```
.subnav {
	display: flex;
}
```

**Pull request merged**
