### PR TITLE
Meta: Linkify RG’s own features on this repo via `rgh-linkify-features`

### PR DESCRIPTION
**Pull request by fregante**
Closes https://github.com/sindresorhus/refined-github/issues/3980

This feature is in 2 parts:

- linkifies `code` in comments anywhere via `rgh-linkify-features`
- linkifies `code` in conversation titles via `format-conversation-titles`

## Test

- this very PR, both in the title and in the 2 features mentioned above
- `summary > code` in comment: https://github.com/sindresorhus/refined-github/pull/3783

## Screenshots

Screen Shot

Screen Shot

## TODO

- [ ] the title link appears to be lost after updating the title or posting a new comment
- [x] new comments aren't affected
- [x] Depends on #4010

### CODE REVIEW

**Comment by fregante** [comment]
> the title link appears to be lost after [`clean-conversation-headers`](/sindresorhus/refined-github/blob/main/source/features/clean-conversation-headers.tsx) runs

This is because of a selector in `parse-backticks.tsx`. I added a note to https://github.com/sindresorhus/refined-github/issues/4008

**Comment by fregante** [comment]
Depends on https://github.com/sindresorhus/refined-github/pull/4010. Currently it includes some code

**Comment by fregante** [comment]
Should be good to go

**Comment by yakov116** [comment]
test

**Comment by fregante** [comment]
> Why not use observeElement?

The point is that the code should already work as is, but `parse-backticks.tsx` is overriding it.

**Comment by yakov116** [comment]
> We already use observeElement, but then [`parse-backticks`](/sindresorhus/refined-github/blob/main/source/features/parse-backticks.tsx) overrides it, observeElement runs again, finds a `code` and assumes it already run.

Gotchya

**Review by yakov116 — APPROVED** [review]
Tested working great!

**Comment by yakov116** [comment]
@fregante this is awesome! I already used it 3 times today! 
Thanks

**Review by 641210 — COMMENTED** [review]
****

**Comment by kidonng** [comment]
ONE OF THE BEST REFINED GITHUB FEATURES

(sorry for the noise, I just can't hold it)

**Pull request merged**
