### PR TITLE
Add 'Jump to bottom' link to discussion pages

### LINKED ISSUE #892: `Scroll to bottom` button for Issue comments page
Often I receive a notification in Gitify or an email that a new comment has been made. I click on the link and I then have to scroll to the bottom of the issue to see the update.

A button at the top to jump to the bottom would be great.

### PR DESCRIPTION
**Pull request by jgierer12**
Fixes #892 

Screenshot

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you add it to the "New Features" section in the readme if this get's accepted by other team members?

**Comment by bfred-it** [comment]
Neat solution! I'm always conflicted about _jump_ buttons but this looks good!

**Comment by jgierer12** [comment]
@hkdobrev WDYT?

**Comment by hkdobrev** [comment]
I like how unobtrusive it is. Thanks!

**Comment by bfred-it** [comment]
I don't think I ever used this button. Can we drop it? Like @hkdobrev said:

> I constantly do this with <kbd>⌘</kbd>+<kbd>↓</kbd> on macOS. I don't really use jump to top/bottom buttons on websites. On mobile it's sometimes useful and I appreciate GitHub adding it, but I won't be using it on Desktop.
> _Originally posted in https://github.com/sindresorhus/refined-github/issues/892#issuecomment-353593922_

**Pull request merged**
