### PR TITLE
Various fixes to `forked-to`

### PR DESCRIPTION
**Pull request by bfred-it**
Follows #2153 

Changes:

- Actually validate fork via HTTP request
- Don't validate current page
- Delete cache entry completely when fork is gone
- Avoid merging with existing cache when unnecessary (i.e. when opening the fork dialog)
- Get/validate/update cache in one step before showing the links
- Reduce number of functions

Currently untested

cc @jerone

### CODE REVIEW

**Comment by jerone** [comment]
I was trying something like the following to show the forks sooner:

```js
async function load(callback: () => void): Promise<void> {
	await elementReady('.pagehead h1.public');
	callback();
	await features.onAjaxedPages(callback);
}
```
But this code will ofc show double forks on some pages.

**Comment by jerone** [comment]
I tested this and aldo it works, it is noticeable slower. Maybe the `validateFork` check should be executed **after** adding the forks HTML, on the cache, so next page load shows the validated forks.

**Comment by bfred-it** [comment]
That works. Also I’ll have to avoid revalidation if it was done “recently”

I think a better strategy is to just fetch the fork box ***if*** there’s a fork in the cache:

- it will validate all forks and replenish the cache in one HTTP request

**Comment by jerone** [comment]
> I think a better strategy is to just fetch the fork box [..]

The fork fragment? If yes, see https://github.com/jerone/refined-github/blob/9df50080dfddee5f7a2a6a1dc4465166339fedfe/source/features/forked-to.tsx#L7-L12 how to load the fragment.

**Comment by bfred-it** [comment]
Now forks will be validated after being shown.

If you want to speed it up further with multiple forks, you can fetch the fork fragment, but for now let's see what happens in https://github.com/sindresorhus/refined-github/pull/2214

**Pull request merged**
