### PR TITLE
Show dropdown UI Reaction on hover

### LINKED ISSUE #170: Show reactions popover on mouseover
I believe a click is a waste of time/click to show the reactions. The popover should show on mouseover.

screen shot 2016-04-08 at 4 51 37 am

Do you guys agree?

### PR DESCRIPTION
**Pull request by paulmolluzzo**
This is a way better alternative to #185 that fixes #170.

This only uses CSS and does the exact same thing as #185 but without any blips or weirdness. So 😞  I didn't just try to do it this way in the first place.

### CODE REVIEW

**Comment by leocaseiro** [comment]
This one is perfect! Many many thanks @paulmolluzzo

**Comment by paulmolluzzo** [comment]
@sindresorhus @hkdobrev @DrewML any thoughts?

**Comment by DrewML** [comment]
This is excellent! Love how small the implementation is.

**Comment by sindresorhus** [comment]
I like this one the best too. I've been running it since you opened the PR.

When moving the mouse to an emoji I need to make sure not to leave the popup, otherwise it disappears. This is problematic when you want to get to the left emojis quickly, as your hand usually try to shortcut it:
untitled12

-

Not exactly relevant to this change, but the emoji I use the most is 👍  Is there any way to make the popup be centered?

**Comment by paulmolluzzo** [comment]
> When moving the mouse to an emoji I need to make sure not to leave the popup, otherwise it disappears. This is problematic when you want to get to the left emojis quickly, as your hand usually try to shortcut it:

I might be able to fix that...

> Not exactly relevant to this change, but the emoji I use the most is 👍 Is there any way to make the popup be centered?

I am pretty sure I can do that nicely, which probably solves the first issue plenty well on its own.

**Comment by sindresorhus** [comment]
> I might be able to fix that...

Maybe add some transparent padding there or something to make it part of the element.

**Comment by paulmolluzzo** [comment]
> Maybe add some transparent padding there or something to make it part of the element.

Yup, that's what I'm going for. Should be able to push this later tonight.

**Comment by paulmolluzzo** [comment]
@sindresorhus Ok, I fixed both of your requests. The increased `:hover` was trickier than I hoped it would be because there's a border around the popover so you can't just use `padding`. What I'm doing is giving the wrapper some size, positioning it outside the popover, and selecting the `:hover` on that element. 😓  BTW, I would not be surprised if this is (at least in part) why there's a `click` event to open this menu up. It's easier to use a `click` then this kind of "hover-when-you're-not-hovering" without JS. See this article from 2013 re: Amazon's dropdown: http://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown

Also, as requested, the popover is now centered over the point and centered on the button, so the arrow points right in between the `+` and the 😄 . This is almost one of those things where perfectly centered looks off-center, if you know what I mean.

> Love how small the implementation is.

@DrewML it _was_ small...

**Comment by sindresorhus** [comment]
Amazing. Didn't think you would be able to make it this good.

Could you remove the black tooltip saying "Add your reaction"? It's distracting now.

If you click the reactions icon the popup will be persistent like before. Possible to remove this behavior?

Would be nice to keep the blue hover effect on the reactions icon as long as the popup is open.

**Comment by paulmolluzzo** [comment]
@sindresorhus:

> Amazing. Didn't think you would be able to make it this good.

Thanks...? 😄 

> Could you remove the black tooltip saying "Add your reaction"? It's distracting now.

Done.

> If you click the reactions icon the popup will be persistent like before. Possible to remove this behavior?

This can't be done with CSS alone because there's a background modal that shows and can't be hidden selectively (it's too far away). With CSS I'd break the background entirely and it probably is used for other things. The right way to do this is to unbind the event listener on the button, but I can't pin down that event. If you can figure the event, we can unbind that.

> Would be nice to keep the blue hover effect on the reactions icon as long as the popup is open.

Done.

**Comment by leocaseiro** [comment]
> > If you click the reactions icon the popup will be persistent like before. Possible to remove this behavior?

> This can't be done with CSS alone because there's a background modal that shows and can't be hidden selectively (it's too far away). With CSS I'd break the background entirely and it probably is used for other things. The right way to do this is to unbind the event listener on the button, but I can't pin down that event. If you can figure the event, we can unbind that.

How about something like:
```css
.timeline-comment-actions .reaction-popover-container .timeline-comment-action.tooltipped::before,
.timeline-comment-actions .reaction-popover-container .timeline-comment-action.tooltipped::after {
	display:none !important;
}
```

**Comment by paulmolluzzo** [comment]
@leocaseiro that looks like it would affect the tooltip, but we're talking about hiding the whole popover (the tooltip is already being hidden). The popover shows when you click the button because it gets a class `.active` and even if I override the CSS applied with that class there is a modal background that is a sibling to a parent element like a dozen levels up. You have to unbind the click event or just hide the background. In the latter case it's not going to be specific to this container having an `.active` class (it's too far to traverse) so it's just always hiding that element, and it probably has its own events (like, that's how you dismiss popups by clicking "outside" the popup) so I don't think hiding it all the time is a good idea.

**Comment by leocaseiro** [comment]
@paulmolluzzo I'm sorry I mixed an issue with another. My bad.

Ow! I understood now. He means when we click to open the popup. I see, it stays opened.

**Comment by paulmolluzzo** [comment]
Still can't pin down this function. Maybe I'm overlooking something obvious, but when I debug on changes to attributes the only bound functions seem to be anonymous functions. I tried cloning and replacing the element, but that didn't do it either. It's possible the event listener is on a higher element and checking the class or something to determine what to apply (like it's bound to the whole header?), but IDK.

Any thoughts/clues appreciated. If not, I say review and consider merging as is and we'll leave the `click` behavior for now.

**Comment by leocaseiro** [comment]
In my opinion the click behaviour is not a big deal. It's still very useful with the mouseover...

**Comment by sindresorhus** [comment]
> Thanks...? 😄

Lol. Didn't mean it that way. Meant I didn't think it would be feasible to do it this good.

> This can't be done with CSS alone

Nah, not that important.

**Comment by sindresorhus** [comment]
Great work @paulmolluzzo :)

happy

**Comment by DrewML** [comment]
This is legit! Thanks @paulmolluzzo!

**Comment by paulmolluzzo** [comment]
@sindresorhus @DrewML Thanks!

**Pull request closed without merging**
