### PR TITLE
Fix: Extension may fail to load if custom CSS is specified

### LINKED ISSUE #4376: Extension sometimes fails to run when custom CSS is injected
I've recently added some custom CSS to hide the "Explore repositories" sidebar on the dashboard. This makes the extension fail regularly with the following error (Firefox 88.0.1, RGH 21.5.19):
```text
TypeError: document.head is null refined-github.js:1913:30
```

The line in question:
https://github.com/sindresorhus/refined-github/blob/83f233677157d21fb6ae11958fa45aa7ee99d65a/source/features/index.tsx#L91

Since this only happens (afaik) when opening new tabs (regardless of the URL), I'm guessing the extension tries to inject the CSS before the `<head>` exists and thus execution stops. This was probably introduced by #4352.

Edit: can confirm the bug goes away when removing the custom CSS.

### PR DESCRIPTION
**Pull request by fregante**
Fixes #4376

This is hard to test since it's a rare occurrence.

1. Specify CSS in the options
2. Reload the page a million times

### CODE REVIEW

**Comment by fregante** [comment]
I looked into contentScript.register, but my polyfill doesn't support `code` yet: https://github.com/fregante/content-scripts-register-polyfill/issues/16

**Comment by jdreesen** [comment]
For me, the notification page is broken most of the time, every other page seems to work 99% of the time.

**Comment by fregante** [comment]
Is it due to the custom CSS? Can you drop the CSS and ensure it doesn’t happen anymore?

**Comment by jdreesen** [comment]
Yes, it is. If I remove the custom CSS, RGH seems to work reliably on the notifications page.

**Comment by jdreesen** [comment]
Just installed the new version, and it's working again. Thank you so much!

**Comment by fregante** [comment]
Great! Thank you for the update

**Pull request merged**
