### PR TITLE
Fix `batch-open-issues` on glboal discussion list

### LINKED ISSUE #2338: "Open All" button from `batch-open-issues` doesn't work
The `batch-open-issues` feature adds a "Open All" button on pages like https://github.com/issues?q=org%3Aprisma+milestone%3A%22Preview+7%22+is%3Aopen

image

That would be _exactly_ what I need in a current workflow I am using, but clicking the button unfortunately doesn't do anything for me there.

Here is the code: https://github.com/sindresorhus/refined-github/blob/2e4a24d3957c205c7bc49525c69e1fa08593d2ca/source/features/batch-open-issues.tsx

Am I missing something here or is this really broken?

### PR DESCRIPTION
**Pull request by kidonng**
Closes #2338

# Test

- https://github.com/issues (global)
- https://github.com/MrSwitch/hello.js/issues (repo you're not a collaborator of)
- (repo where you **are** a collaborator of)

### CODE REVIEW

**Comment by fregante** [comment]
This fails on repos you're not a collaborator on:

https://github.com/MrSwitch/hello.js/issues

I think the condition isn't `isGlobalDiscussionList` but a more generic `are checkboxes available.

I added 2 more tests to your post

**Comment by kidonng** [comment]
Thanks, will check those later

**Comment by kidonng** [comment]
Sorry, I don't quite get *what* failed. It is working fine on:

- Global (https://github.com/issues)
- My own repo (directly click "Open All")
- My own repo (with selected issues)
- Other people's repo

Have I missed something?

**Comment by fregante** [comment]
> It is working fine

Indeed! I must have forgotten to refresh that tab after using your branch 😅

**Comment by janpio** [comment]
Thanks @kidonng!

I had told my team that some random person showed up in my issue and claimed it to fix it - and then they all laughed about how this will never get done and I will have to live with a broken "Open All" button.

That will teach them about OSS 🚀

**Pull request merged**
