### PR TITLE
Bypass the checks tab for all PR validation types

### PR DESCRIPTION
**Pull request by natemcmaster**
This copies the same shortcut added in https://github.com/sindresorhus/refined-github/pull/1636, but for Azure Pipelines build checks. 

Basically everything mentioned in https://github.com/sindresorhus/refined-github/issues/1620 about the "checks" UI applies to Azure Pipelines, too. The "details" link at the bottom of PRs leads to the checks tab.

image

Then, you have to find a small link at the bottom of the checks summary to actually navigate to Azure Pipelines.

screenshot

This PR bypasses this intermediate page by changing the "details" link to jump directly to the build results page in Azure Pipelines.

image

### CODE REVIEW

**Comment by bfred-it** [comment]
Change welcome. The code is nearly identical, so it's best to merge the two, rename the feature to `bypass-checks` or something that makes more sense, then add a migration to `background.js`

**Comment by bfred-it** [comment]
Actually if you can find a way to make it work for all the links it'd be great. I don't have any projects with Checks so I can't do it.

**Comment by natemcmaster** [comment]
Sure, I can de-dup the code. I'll have time tomorrow hopefully to update the PR.

> Actually if you can find a way to make it work for all the links it'd be great.

I don't know if there is a good general solution to the problem. I'd have to find more examples of the DOM for checks by Travis, Azure Pipelines, and others. For Azure Pipelines, the link we're trying to find looks like this:
```html
<div class="mb-4">
      <a class="text-small text-gray-light" target="_blank" rel="noopener noreferrer" data-hydro-click="{&quot;event_type&quot;:&quot;check_suite.external_click&quot;,&quot;payload&quot;:{&quot;check_suite_id&quot;:45116668,&quot;check_run_id&quot;:46467076,&quot;link_url&quot;:&quot;https://dnceng.visualstudio.com/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=66446&quot;,&quot;link_text&quot;:&quot;View more details on&quot;,&quot;client_id&quot;:&quot;1447371955.1516988087&quot;,&quot;originating_request_id&quot;:&quot;5A5F:743B:12259F7:1AFEB32:5C2FAC4F&quot;,&quot;originating_url&quot;:&quot;https://github.com/aspnet/AspNetCore/pull/5146/checks&quot;,&quot;user_id&quot;:2696087}}" data-hydro-click-hmac="860fd9c3390c8ed09ef00b73d4c81f31aa100319b2c1132d3407981b0d7056c7" href="https://dnceng.visualstudio.com/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=66446">
        <svg class="octicon octicon-link-external mr-2" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M11 10h1v3c0 .55-.45 1-1 1H1c-.55 0-1-.45-1-1V3c0-.55.45-1 1-1h3v1H1v10h10v-3zM6 2l2.25 2.25L5 7.5 6.5 9l3.25-3.25L12 8V2H6z"></path></svg>View more details on Azure Pipelines
</a>    </div>
```
I'm not sure how to write a generic selector that would match only this and not other links that might appear on this page.

**Comment by bfred-it** [comment]
`a.text-small .octicon-link-external` and then get the `parentNode` to select the link on the `fetch`ed page

**Comment by natemcmaster** [comment]
Thanks for the suggestions. I have updated the PR.

**Comment by Kocal** [comment]
@bfred-it @natemcmaster yes it still working for Travis :+1: 
Netlify is working too. :slightly_smiling_face:

**Comment by natemcmaster** [comment]
Thanks for cleaning up my PR. It still works on Azure Pipelines, too. Let me know if there is anything else I need to fix.

**Pull request merged**
