### PR TITLE
Hide unnecessary webpack stats

### PR DESCRIPTION
**Pull request by bfred-it**
```diff
 > @ watch ~/refined-github
 > webpack --mode=development --watch
 
-Hash: 2f921e27442babd59a80
 Version: webpack 4.29.4
 Time: 3517ms
 Built at: 02/20/2019 11:22:32 PM
                   Asset      Size      Chunks             Chunk Names
           background.js    19 KiB  background  [emitted]  background
       background.js.map  21.6 KiB  background  [emitted]  background
-          background.ts  1.96 KiB              [emitted]  
 browser-polyfill.min.js  9.79 KiB              [emitted]  
             content.css  25.5 KiB              [emitted]  
              content.js   328 KiB     content  [emitted]  content
          content.js.map   335 KiB     content  [emitted]  content
-             content.ts  3.92 KiB              [emitted]  
-           globals.d.ts  87 bytes              [emitted]  
                icon.png  1.89 KiB              [emitted]  
           manifest.json  1.05 KiB              [emitted]  
             options.css  1.31 KiB              [emitted]  
            options.html  2.04 KiB              [emitted]  
              options.js  11.6 KiB     options  [emitted]  options
          options.js.map  12.4 KiB     options  [emitted]  options
-Entrypoint content = content.js content.js.map
-Entrypoint background = background.js background.js.map
-Entrypoint options = options.js options.js.map
-[./source/background.ts] 2.63 KiB {background} [built]
-[./source/content.ts] 4.23 KiB {content} [built]
-[./source/features/add-co-authored-by.tsx] 2.15 KiB {content} [built]
-[./source/features/batch-open-issues.tsx] 2.07 KiB {content} [built]
-[./source/features/branch-buttons.tsx] 4.46 KiB {content} [built]
-[./source/features/bypass-checks.tsx] 1.11 KiB {content} [built]
-[./source/features/ci-link.tsx] 1.44 KiB {content} [built]
-[./source/features/close-out-of-view-modals.tsx] 1.27 KiB {content} [built]
-[./source/features/comment-fields-keyboard-shortcuts.tsx] 3.3 KiB {content} [built]
-[./source/features/commented-menu-item.tsx] 1.46 KiB {content} [built]
-[./source/features/comments-time-machine-links.tsx] 1.7 KiB {content} [built]
-[./source/features/copy-file.tsx] 1.75 KiB {content} [built]
-[./source/features/copy-on-y.tsx] 996 bytes {content} [built]
-[./source/features/create-release-shortcut.tsx] 803 bytes {content} [built]
-[./source/options.tsx] 797 bytes {options} [built]
-    + 123 hidden modules
-Hash: 64989eb1d30664a6ba2d
 Version: webpack 4.29.4
 Time: 657ms
 Built at: 02/20/2019 11:22:51 PM
          Asset     Size   Chunks             Chunk Names
     content.js  328 KiB  content  [emitted]  content
 content.js.map  335 KiB  content  [emitted]  content
  + 4 hidden assets
-Entrypoint content = content.js content.js.map
-Entrypoint background = background.js background.js.map
-Entrypoint options = options.js options.js.map
-[./source/content.ts] 4.23 KiB {content} [built]
-[./source/features/ci-link.tsx] 1.43 KiB {content} [built]
-    + 136 hidden modules
```

Also notice that we were pushing `.ts` files to the store (but `.map` only appears at during `watch`)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can we remove it all?

**Comment by bfred-it** [comment]
I wish, but I think it's useful to see what will end up in the store and how much it weighs. Even if we just enable it on Travis it's not gonna be enough because nobody will check it.

I wish there was a way to skip a few columns on the table too but they are hard-coded

**Comment by sindresorhus** [comment]
With `stats: false,` and https://github.com/GoogleChromeLabs/size-plugin we can have this:

```
❯ webpack

           background.js ⏤  4.18 kB
              content.js ⏤  45.5 kB
              options.js ⏤  2.6 kB
 browser-polyfill.min.js ⏤  3.1 kB
             options.css ⏤  658 B
            options.html ⏤  956 B
             content.css ⏤  7.88 kB
```

**Comment by bfred-it** [comment]
Excellent! It also shows you when the bundle increases during `watch`, which is pretty useful

```
 background.js ⏤  7.45 kB (+2.1 kB)
    content.js ⏤  61.9 kB
    options.js ⏤  3.51 kB
```

**Pull request merged**
