### PR TITLE
Make `clean-pinned-issues` more visible

### PR DESCRIPTION
**Pull request by ocarreterom**
Update pinned issues style to be more accurate with the GitHub theme. 💅 

Thanks for contributing! 🍄

1. LINKED ISSUES:
   Continue the discussion https://github.com/sindresorhus/refined-github/pull/3491

2. TEST URLS:
    https://github.com/sindresorhus/refined-github/issues

3. SCREENSHOT:
   

<table>
<tr>
	<td>Before
	<td>After
<tr>
	<td>Captura de pantalla 2020-10-16 a las 0 41 20
	<td>Captura de pantalla 2020-10-16 a las 0 43 26
</table>

### CODE REVIEW

**Comment by busches** [comment]
They look selected now, not a fan.

**Comment by fregante** [comment]
I don’t think I’ve seen that style anywhere else; if you have an example of GitHub using it we can discuss whether we should match it.

**Comment by ocarreterom** [comment]
For example GitHub use this style for:

1. Emphasize some section in a view like notification actions banner and files list header.
Captura de pantalla 2020-10-16 a las 17 28 22
Captura de pantalla 2020-10-16 a las 17 29 03

2. To highlight items on a list like your own comments on issues and PRs and notifications on hover.
Captura de pantalla 2020-10-16 a las 17 28 43
Captura de pantalla 2020-10-16 a las 17 27 26

There are some guidelines about blue boxes in Primer docs https://primer.style/css/components/box#blue-box-theme

---

The selected/active style should be more like this:
Captura de pantalla 2020-10-16 a las 18 21 52

---

Another suggestion 🤷‍♂️

<table>
<tr>
    <td>Before
    <td>After
<tr>
	<td>96194030-c6f66d80-0f49-11eb-91d2-8e8a7353e856
	<td>Captura de pantalla 2020-10-16 a las 18 09 17
</table>

In my opinion, the 2px width seems more like a glitch than a feature 😶

**Review by fregante — APPROVED** [review]

**Comment by notlmn** [comment]
Maybe this can go along with #3657, using the same colors? Do those colors work here?

**Comment by fregante** [comment]
> Maybe this can go along with #3657

That's a gray border, this is blue as per https://primer.style/css/components/box#blue-box-theme

**Comment by fregante** [comment]
@sindresorhus thoughts on the style? Worth the change?

**Comment by sindresorhus** [comment]
I think they look too "heavy" now. Maybe we could reduce the background color opacity to half?

```css
background-color: rgb(241 248 255 / 0.5);
```

Screen Shot 2020-11-20 at 10 22 48

**Comment by fregante** [comment]
I don't think this change is necessary after all. Thanks for opening the discussion though

**Pull request closed without merging**
