### PR TITLE
Fix `prevent-link-loss` warning message copy

### PR DESCRIPTION
**Pull request by waldyrious**
## Test URLs

Try adding this URL to a new comment (e.g. in this PR):

    https://github.com/github/choosealicense.com/compare/gh-pages...Pukimaa:gh-pages#diff-c0311c1df17d5d714db46ca1401ad374a35de861a461d211c6c947f1b2194034R8

## Screenshot

Screenshot 2021-06-14 at 18 16 38

After

image

### CODE REVIEW

**Comment by yakov116** [comment]
@waldyrious can you post a screenshot of it working?

**Review by yakov116 — APPROVED** [review]

**Comment by waldyrious** [comment]
I didn't think that would be needed for a 1-character change 😅 but sure — can you show me how to do it? Would I need to build the extension locally and install it? Or is it a simpler process?

**Comment by yakov116** [comment]
You could download the zip from the actions artifacts and test. If you can't I can try later.

**Comment by waldyrious** [comment]
If you could try it, I'd appreciate it. I'm not entirely clear on how find the zip, and I'm afraid I wouldn't know what to do with it anyway in order to test the extension.

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/suites/2991340755/artifacts/67565822

**Pull request merged**
