### PR TITLE
Add timemachine links to all repo links

### PR DESCRIPTION
**Pull request by bfred-it**
I think that the most clear and less troublesome way to solve this is to add an icon:

- It avoids the _"What you see is **not** what I get_ issue that'd we'd have if we change links without leaving a visual cue.
- It clearly shows that a link can be _refined_, rather than hiding the action behind a button (which I wouldn't know where to place anyway)

a

b

# Notes

- It's applied to all non-commit links (`blob` or `tree`)
- All links point to the default branch instead of the linked branch because
  - timestamped git tag links don't work (e.g. https://github.com/bfred-it/select-dom/tree/v4.0.0@%7B2019-03-17T08:48:45Z%7D)
  - we don't know if a `ref` is a tag without fetching it first 

# Tests

- https://github.com/sindresorhus/refined-github (repo link not altered)
- https://github.com/sindresorhus/refined-github/blob/master/source/features/jump-to-bottom-link.tsx#L3

And more links in:

- https://github.com/sindresorhus/refined-github/issues/807#issuecomment-469245606
- https://github.com/sindresorhus/refined-github/issues/1792
- https://github.com/sindresorhus/refined-github/issues/1096
- https://github.com/sindresorhus/refined-github/issues/1676#issuecomment-449004524 (these links are not affected because they are `/compare/` and `/commits/`)
- https://github.com/sindresorhus/refined-github/issues/1735
- https://github.com/sindresorhus/refined-github/issues/1197
- https://github.com/sindresorhus/refined-github/issues/1464 (perfect example because the linked file is now missing)

Possible bug, should we disable this feature in code blocks?

- https://github.com/sindresorhus/refined-github/issues/803

The clipping bug is actually due to the #1146 and also appears for linkified issues: no full solution, but moving the tooltip to the right might solve it for short links 

- https://github.com/sindresorhus/refined-github/issues/1864#issuecomment-474158153

Suggest more conversations with links like that

Closes https://github.com/sindresorhus/refined-github/issues/1448

### CODE REVIEW

**Comment by bfred-it** [comment]
Screenshot 2019-03-19 at 01 41 32

This also updates the old links, however I kinda want to move them to the comment dropdown at some point.

**Comment by sindresorhus** [comment]
This looks really useful!

**Comment by sindresorhus** [comment]
> All links point to the default branch instead of the linked branch because

However, this limitation considerably limits its usability. Is there any way we can do API calls to support getting the correct branch too?

**Comment by sindresorhus** [comment]
> /source/libs/api.js@master#L3 

This test (The second under the `Tests` header) doesn't work.

**Comment by sindresorhus** [comment]
> however I kinda want to move them to the comment dropdown at some point.

👍

**Comment by sindresorhus** [comment]
> should we disable this feature in code blocks?

Yes

**Comment by bfred-it** [comment]
> Is there any way we can do API calls to support getting the correct branch too?

Yes... if we must. I can test if all those `/tree/name` are tags. If they are, the icon isn't needed at all because tags are already semi-permalinks

> This test (The second under the `Tests` header) doesn't work.

It does, but it was a bad test since that file didn't exist when I posted my comment, so the link is still a 404. D'oh. I updated it.

**Comment by bfred-it** [comment]
> However, this limitation considerably limits its usability. Is there any way we can do API calls to support getting the correct branch too?

Too involved, I tried but I'm not interested, best left as a separate issue

> should we disable this feature in code blocks?

Done

> however I kinda want to move them to the comment dropdown at some point.

Done

Screenshot 2019-04-18 at 15 33 22



I think this only needs docs now

**Comment by sindresorhus** [comment]
> I tried but I'm not interested, best left as a separate issue

Can you open an issue for it?

**Comment by bfred-it** [comment]
> Can you open an issue for it?

Once this is merged, as it depends on it

**Pull request merged**
