### PR TITLE
Add `Compare` tab

### PR DESCRIPTION
**Pull request by busches**
This was mentioned in Issue #267. A lot of other things were mentioned as well, but this was a simple fix and something I manually type in a lot.

No shortcut was added as 'g c' seemed logical, but it's already used for the 'Code' tab.
Icon is the same icon used on the Compare page, but I'm open to other ideas.
Changed the RegEx for isCompare to make the trailing slash optional, but it probably makes more sense to remove the check for the trailing slash all together.

### CODE REVIEW

**Comment by busches** [comment]
@paulmolluzzo Correct, there are a LOT of things going on in #267 and this was an easy fix that I could delivery quickly that added value, which was my goal. If the rest of the things brought up in #267 could be fleshed out in clearer detail, a future PR could tackle those.

**Comment by busches** [comment]
@jgierer12 doh, not sure how I forgot that, it's fixed now.

**Comment by busches** [comment]
@jgierer12 Test added

**Comment by hkdobrev** [comment]
BTW GitHub is using different icons for Compare on different places, not sure which one is better:

Compare link on the code tab when you've chosen a different branch:
screen shot 2017-05-09 at 22 27 43

Compare icon on the compare page:

screen shot 2017-05-09 at 22 36 04

Which one do you prefer?

**Comment by busches** [comment]
@hkdobrev I like the file icon  better and swapped to that, thanks for the suggestion.

**Comment by sindresorhus** [comment]
Code looks good to me :)

@busches Can you add it to the `Highlights` section in the readme and link to a screenshot?

The merge conflict also needs to be resolved.

**Comment by sindresorhus** [comment]
> but it probably makes more sense to remove the check for the trailing slash all together.

👍

**Comment by busches** [comment]
Rebased and screenshot added to highlights.

**Comment by sindresorhus** [comment]
Great. Thank you. This is excellent :)

**Pull request merged**
