### PR TITLE
Hide `useful-forks` on GitHub Enterprise

### PR DESCRIPTION
**Pull request by payne911**
1. LINKED ISSUES:
   As per the comment there: https://github.com/sindresorhus/refined-github/pull/3955#issuecomment-787113315

2. TEST URLS:
   I don't use GHE, so that's a bit hard for me to provide.

3. SCREENSHOT:
   Contextually impossible for me.

### CODE REVIEW

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
I'd like to see the exception for private repos in the same PR if possible

**Comment by payne911** [comment]
> I'd like to see the exception for private repos in the same PR if possible

I'll send that in another PR once I figure it out, if you don't mind.

**Comment by fregante** [comment]
Thank you!

**Review by 641210 — COMMENTED** [review]
****

**Pull request merged**
