### PR TITLE
Add GitHub Follow to the related extensions list

### PR DESCRIPTION
**Pull request by hkdobrev**
Hopefully more people would see it and reduce feature requests in RG.

### CODE REVIEW

**Comment by sindresorhus** [comment]
It doesn't seem to be fully working https://github.com/staff0rd/github-follow-extension/issues/6 and it doesn't look very actively maintained.

**Comment by hkdobrev** [comment]
Indeed.

**Comment by staff0rd** [comment]
The extension is now fixed, I hope you'll reconsider including it.

**Comment by bfred-it** [comment]
screen shot 2018-03-11 at 14 48 23

It doesn't look as in the screenshots anymore, but it seems to work.

**Pull request merged**
