### PR TITLE
Update deps and --fix

### PR DESCRIPTION
**Pull request by bfred-it**
```
  source/features/copy-on-y.tsx:7:22
  ✖   7:22  This assertion is unnecessary since it does not change the type of the expression.  @typescript-eslint/no-unnecessary-type-assertion
```

https://github.com/sindresorhus/refined-github/blob/56eedadec4b537741093909358e8716ad03e5780/source/features/copy-on-y.tsx#L7

_Are you sure about that, XO?_ Because TypeScript wants that.

Bug in `@typescript-eslint/no-unnecessary-type-assertion`?

### CODE REVIEW

**Comment by sindresorhus** [comment]
I think it wants you to do:

```ts
const permalink = select<HTMLAnchorElement>('.js-permalink-shortcut').href;
```

**Comment by sindresorhus** [comment]
It's usually better to use generics when possible, as generics can be type-narrowed, but type assertions overrule anything.

**Comment by bfred-it** [comment]
Good! That should have fixed it.

This is still failing because of this:

```
ERROR in /Users/bfred/Web/projects-extensions/refined-github/source/features/ci-link.tsx
./source/features/ci-link.tsx
[tsl] ERROR in /Users/bfred/Web/projects-extensions/refined-github/source/features/ci-link.tsx(28,14)
      TS2339: Property 'callCount' does not exist on type '<ArgumentsType extends unknown[], ReturnType>(fn: (...arguments: ArgumentsType) => ReturnType, options?: Options) => (...arguments: ArgumentsType) => ReturnType'.
```

Which is due to:

```js
import onetime from 'onetime';
...
	if (onetime.callCount(fetchStatus) > 1) {
		icon.style.animation = 'none';
	}
```

I think the TS types need to be updated to add that property on `onetime`, but for now I'll change the code to use `import onetime, {callCount}`

**Comment by sindresorhus** [comment]
> I think the TS types need to be updated to add that property on onetime, but for now I'll change the code to use import onetime, {callCount}

Done: https://github.com/sindresorhus/onetime/releases/tag/v5.0.0

**Pull request merged**
