### PR TITLE
Improve feature application on AJAXed widgets

### PR DESCRIPTION
**Pull request by fregante**
# Tests

1. Visit an issue or PR (like this one)
2. Add a reaction

Or:

1. Visit an issue or PR (like this one)
2. Edit a comment

You should still see the features being applied correctly:

- `sticky-discussion-sidebar`
- `clean-sidebar`
- `reaction-avatars`
- `edit-comments-faster`’s icon (fixes https://github.com/sindresorhus/refined-github/issues/2572)
- `mark-unread`’s button

Follows https://github.com/sindresorhus/refined-github/pull/2533 https://github.com/sindresorhus/refined-github/pull/2344

### CODE REVIEW

**Comment by yakov116** [comment]
@fregante it made #2572 worse (upon edit it used to return the icon now it does not) and cause more issues with #2852

**Comment by fregante** [comment]
I just tested #2852 (including this PR) also on Chrome, it looks perfect to me, zero delay and zero issues: the edit icon is there and the sidebar is always clean

demo

**Comment by yakov116** [comment]
Will make a gif in a few (If my son does not wake up... 😄 )

**Comment by fregante** [comment]
Sorry I meant I tested #2987, not https://github.com/sindresorhus/refined-github/issues/2852. That issue is not fixed by any of this.

**Comment by fregante** [comment]
https://github.com/sindresorhus/refined-github/issues/2852 cannot be "made worse" because it was never supposed to work in the first place, there's no listener.

**Comment by yakov116** [comment]
Before this PR upon an edit it would return. Give me a few I will try to make a GIF

**Comment by yakov116** [comment]
Video_2020-04-12_100257

At first i was seeing strange things. After I deleted the node_modules folder, no strange thing but the issue is still there

**Comment by fregante** [comment]
I just tested the store version and the icons only appear on reload.

> #2852 cannot be "made worse" because it was never supposed to work in the first place, there's no listener.

⬆️

**Comment by tunnckoCore** [comment]
Cool! <3

**Comment by yakov116** [comment]
@fregante forget my previous comments. I am still having the issue of the edit icon not showing after reactions

**Comment by fregante** [comment]
Can you show that in a gif? Start when the edit icon is visible

**Comment by yakov116** [comment]
Video_2020-04-19_112712

**Comment by fregante** [comment]
Open a new issue

**Pull request merged**
