### PR TITLE
Update discussion-sidebar z-index

### LINKED ISSUE #1647: Sidebar showing under comment headers when sticky
When the sticky sidebar feature is enabled, the labels and other menus show under the comment titles:

screen shot 2018-11-30 at 11 39 38 am

The comment headers have a `z-index` of 25, while the sidebar has a `z-index` of 21

### PR DESCRIPTION
**Pull request by karaggeorge**
Fixes #1647

Before:
screen shot 2018-11-30 at 11 39 38 am

After:
screen shot 2018-11-30 at 11 39 51 am

`z-index` set to 26, since the comment titles have 25

### CODE REVIEW

**Comment by bfred-it** [comment]
If you want to create a `rgh-sticky-sidebar` class and then just use `classList.toggle('rgh-sticky-sidebar', sidebarHeight < window.innerHeight)` that'd be _wonderful_

**Comment by karaggeorge** [comment]
Sounds good. I'll make the update 👍

**Comment by karaggeorge** [comment]
@bfred-it updated

**Comment by bfred-it** [comment]
Thanks for the fix @karaggeorge! :)

**Pull request merged**
