### PR TITLE
Use system setting for `user-local-time` time formatting

### LINKED ISSUE #3597: Ability to preview `user-local-time` in 12h format
I do not see any option in the extensions settings to change the `user-local-time` format to 12h, it would be great if it were possible to change it.
image

### PR DESCRIPTION
**Pull request by yakov116**
1. LINKED ISSUES:
   Resolves #3597 

2. TEST URLS:
   My Avatar

3. SCREENSHOT:
image

### CODE REVIEW

**Review by sindresorhus — APPROVED** [review]
I disagree with this in principle, as 12-hour time is dumb and ambiguous. But I also recognize RG is not the place to fix world problems.

**Comment by fregante** [comment]
I also argue for 24h, but I saw that GitHub uses 12h on my en-US computer, so it’d kinda make sense to follow the same format

**Review by fregante — APPROVED** [review]
Begrudgingly

**Comment by yakov116** [comment]
Title is good?

**Pull request merged**
