### PR TITLE
Support dark mode in the options view

### PR DESCRIPTION
**Pull request by sindresorhus**
Screenshot 2019-10-28 at 15 36 44

### CODE REVIEW

**Comment by fregante** [comment]
What about Firefox? Does it break anything there?

**Comment by sindresorhus** [comment]
Looks fine to me:

Screenshot 2019-10-29 at 10 20 09

**Comment by fregante** [comment]
Perfect!

**Comment by fregante** [comment]
I noticed (in my other extension) that `--background-color: white` breaks Firefox’s regular background (it appears as a white border around the gray background)



We can probably drop the variables from `:root` and the lack of it will make the browser use the default values, essentially _skipping_ all of the new rules on non-dark browsers (ideal, Firefox’ default styles are better than this)

**Comment by fregante** [comment]
Never mind. I can't reproduce consistently.

**Comment by debajyoti-xyz** [comment]
On windows 10 with dark mode enabled the text color of feature filter input are a bit hard to read.

image

**Comment by fregante** [comment]
@debajyoti-xyz can you open a new issue?

**Pull request merged**
