### PR TITLE
Add Hotkey for updating branch on a stale PR.

### LINKED ISSUE #1105: Hotkey for updating branch on a stale PR
I'd like to use a hotkey for updating a branch that has gotten stale. Unless `u` is already preserved, I'd go with that one once you're in a pull request page.

### PR DESCRIPTION
**Pull request by vanniktech**
Fixes #1105

### CODE REVIEW

**Comment by bfred-it** [comment]
The selector is too generic, it matches this button for me:




But also I agree with @hkdobrev's concern: https://github.com/sindresorhus/refined-github/issues/1105#issuecomment-369047512

**Comment by vanniktech** [comment]
Agreed. I'm taking the last button now and this should be fixed. (Could not test it though since I don't have a PR with that style)

**Comment by bfred-it** [comment]
That's not how `:last-child` works, you're confusing it with jQuery's `:last` 😅

**Comment by vanniktech** [comment]
Okay now I understand what you mean. I only want this hotkey to work when the only thing I can do is update the branch and not having merge conflicts.

**Comment by vanniktech** [comment]
Closing since we're not on the same page.

**Pull request closed without merging**
