### PR TITLE
Keep features working after clicking the browser’s Back button

### PR DESCRIPTION
**Pull request by fregante**
Fixes https://github.com/sindresorhus/refined-github/issues/1247

Untested. If it works thank TypeScript and XO.

GitHub uses delegated events across the board and we have to do the same because PJAX either flattens the page to plain HTML or uses `cloneNode`, both of which preserve changes we make (and buttons we add) but discard attached events.

# Test

All the related features 😅

- Test normal function
- Open page, then navigate away (to another ajaxed page), click back

It would be great of anyone could help test this out and list which features you tried

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#1247: Old events don't work on history.back()](https://issuehunt.io/repos/51769689/issues/1247)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by yakov116** [comment]
@fregante if you upload a CRX I can test it

**Comment by fregante** [comment]
The Build workflow has an artifact. Look in the dropdown on the top right of Actions

**Comment by fregante** [comment]
Current version: https://github.com/sindresorhus/refined-github/suites/365152039/artifacts/751370

**Comment by fregante** [comment]
Tested and working, both normally and after clicking the browser's "back" button

source/features/hide-comments-faster.tsx
source/features/batch-open-issues.tsx

**Comment by fregante** [comment]
I manually tested/fixed every feature with the exception of a couple rare instances for `on-new-comments` and `on-pr-merge-panel-open`

Time to merge this and fix this behavior once for all!

**Pull request merged**
