### PR TITLE
Change branch link behavior on pull request site

### PR DESCRIPTION
**Pull request by marcbachmann**
- Move the link to a separate icon next to the name
- Focus the branch name on click
<hr/>

branch-link

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why?

**Comment by marcbachmann** [comment]
I use that label to copy pull request names to check them out locally.

**Comment by sindresorhus** [comment]
Then it would make more sense to have a button to copy the branch name, but not sure we want that either.

**Comment by marcbachmann** [comment]
Yes, definitely. That link now shows up for all branch references. It doesn't look that good.
I'd keep it consistent and switch back to a url.

Any reason you don't like a separate button to copy the name?
We could add it next to the edit button of a pr title.

**Comment by hkdobrev** [comment]
@marcbachmann Do you have git completion in your shell? You can check out a branch by using just the first few characters and tab completion?

There's also [hub](https://hub.github.com/) which allows you to check out a PR locally by pasting the URL.

**Comment by marcbachmann** [comment]
Hehe. Sure I do. But if you're on the website and want to checkout something, it's much faster to quickly copy the whole string than tabbing through a few matches where you have to find it.

I also use the alias `fetch-pr  = "!f() { git fetch origin refs/pull/$1/head:pr/$1; } ; f"` to check out a specific pr, but that doesn't keep the branch name.

... ok, I didn't know that `hub` also has a `checkout` enhancement. That's good enough. 😆

**Comment by hkdobrev** [comment]
In a way, I see the benefit, but even then, I wouldn't implement it this way, because there could be a username with a colon there and this won't work in a normal `git-checkout (1)`. And for some reason I don't like the copy button either. 🤷‍♂️

**Comment by paulmolluzzo** [comment]
💡 Right-click and select "Copy".

screen shot 2017-04-27 at 1 10 33 pm

**Comment by marcbachmann** [comment]
Tripple click works without this extention, that's why it broke my workflow.

**Pull request closed without merging**
