### PR TITLE
Simplify dom-chef usage

### PR DESCRIPTION
**Pull request by bfred-it**
@nickytonline I'm getting a weird error:

```
./refined-github/node_modules/dom-chef/index.d.ts' is not a module.
```

### CODE REVIEW

**Comment by nickytonline** [comment]
It appears you added an index.d.ts file to dom-chef recently and there's something it's not liking about it. I can take a peek tonight.

From what I can tell looking at the React types on DT, try adding these lines at the top of your index.d.ts

```
export = React;
export as namespace React;
```

**Comment by sindresorhus** [comment]
@nicksnyder That is legacy TS syntax.

I think the correct solution is putting this at the bottom of the file:

```ts
declare const react: React;
export default react;
```

It's annoying that you can't "default export" namespaces.

**Comment by nickytonline** [comment]
Correct. My bad. I was just grabbing what was in the React DT types. ;) Agreed that it's annoying that you can't default export a namespace.

**Comment by nicksnyder** [comment]
Wrong @ :)

**Comment by nickytonline** [comment]
I think he just wants you to contribute @nicksnyder. We need two Nicks. ;)

**Comment by sindresorhus** [comment]
@nicksnyder Sorry, the GitHub autocomplete sucks...

**Comment by bfred-it** [comment]
Like this? 
https://github.com/vadimdemedes/dom-chef/pull/32

**Comment by nickytonline** [comment]
Seems to look good. Try npm linking it to RGH and see how that goes.

**Comment by bfred-it** [comment]
That worked! :) `dom-chef@3.5.2` published

**Pull request merged**
