### PR TITLE
Add "Compare" and "Releases" tabs before "Settings" if present

### LINKED ISSUE #431: Inject Releases and Compare tab before Settings tab
At the moment we inject Releases and Compare tabs at the end of the repository tabs strip.

However, when you have admin access to a repository you also have a Settings tab, which in canonical GitHub interface is always last. And this makes sense.

We should change our injecting so the Settings tab always remain last if it is present.

### PR DESCRIPTION
**Pull request by lukaszklis**
Fixes #431.

### CODE REVIEW

**Comment by lukaszklis** [comment]
@jgierer12 That’s also a possibility, however it depends on the presence of the ”Graphs” tab + the ”Compare” tab would have to be added after ”Releases” tab to keep the current order. I’m fine with both approaches, depends on whatever seems better for you.

**Comment by sindresorhus** [comment]
It's good like this. Thanks @lukaszklis :)

**Comment by sindresorhus** [comment]
> That’s also a possibility, however it depends on the presence of the ”Graphs” tab 

Funnily GitHub just moved the Graphs tab, so good point.

**Comment by hkdobrev** [comment]
> Funnily GitHub just moved the Graphs tab, so good point.

😂 

Does anyone have anything other than Graphs in their Insights drop down?

I'm wondering whether it's a bug, an upcoming feature or extendable section of the repo via the new GitHub Apps.

**Comment by hkdobrev** [comment]
> Does anyone have anything other than Graphs in their Insights drop down?

Never mind, saw this #433

**Pull request merged**
