### PR TITLE
Fix conflict with ZenHub extension overlays

### PR DESCRIPTION
**Pull request by nBerg**
This was causing some issues with zenhub's overlays

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you give the PR a proper title that explains the change?

**Comment by nBerg** [comment]
Ooops! Sorry about that. Fixed

**Comment by bfred-it** [comment]
This doesn't change anything.

**Comment by nBerg** [comment]
On pages where the recent branches popup should appear this wont change anything.

On the zenhub boards page the html structure is something like:
screen shot 2018-01-04 at 10 00 03 am

Applying the position change to that container div messed with the zenhub overlays (they should be full screen):
zenhubscreenshot

I just moved the position change down to the `repository-content` div

**Comment by bfred-it** [comment]
I see the issue now, I thought it was trying to fix the other ZenHub-related issue we have for exactly the same feature (#906)

I'm merging this but #906 might require the opposite solution to be applied, so this might come undone later.

**Pull request merged**
