### PR TITLE
Fix display of "out of date" and "stale" warnings in sticky header

### LINKED ISSUE #139: Filenames in sticky header break UI with subset of changes
When looking at a single commit inside of a PR, GitHub shows a message in the commit header saying:
> You are viewing a subset of the changes. **View all changes**

screen shot 2016-03-31 at 22 54 47

However when you scroll down this message stays in the sticky header and it's not acting nicely with the filename we've added there.

screen shot 2016-03-31 at 22 55 00

(Screenshots are from https://github.com/composer/composer/pull/5134/commits/9d360cf338930f18264994f0fa5643852372c156).

This is a bit similar to #122, but I don't think it depends on whether the filename is long or short.

### PR DESCRIPTION
**Pull request by DrewML**
Fixes #139 

image

image

My design skills are *weak*, so let me know if you can think of a better alternative.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Could use some more top and bottom padding.

**Comment by hkdobrev** [comment]
I think this would look good even without the 100% width.

**Comment by paulmolluzzo** [comment]
I like the full width, and agree about the padding. Really, don't override the font or padding that GH has. 

When you change the font size and padding it winds up overlapping the bottom "edge" of the sticky container, but not evenly, so you'd need to add `margin-top` to satiate my OCD.

However, if you add in `width:120%; margin-left:-5%` it makes the bar go to the edge of the window, hiding that bottom edge (it sorta becomes the edge) which looks nice.

full-width

**Comment by DrewML** [comment]
Some updates pushed based on feedback

image

**Comment by sindresorhus** [comment]
Looks good :)

**Pull request merged**
