### PR TITLE
Drop `recently-pushed-branches-enhancements` feature

### LINKED ISSUE #3518: `recently-pushed-branches-enhancements` may cause duplicate banners
URL: https://github.com/sindresorhus/refined-github
Screenshot: image

I can't always replicate this, but it happened to me yesterday as well so I think it's better to report it here.

### LINKED ISSUE #3748: Drop `recently-pushed-branches-enhancements`
I'm tired of having to rewrite this every few months because of class changes. Maybe we should just drop it.

99847230-5db3dc80-2b3d-11eb-9e57-09147b77ef63
Screen Shot 2020-11-20 at 14 35 32

Feature also temporarily disabled in https://github.com/sindresorhus/refined-github/commit/c8a50197b2695b7f4bf5c96d87dd5211a5d9c7a6

### PR DESCRIPTION
**Pull request by fregante**
Re: https://github.com/sindresorhus/refined-github/issues/3748

Fixes #3518
Closes #3748

### CODE REVIEW

**Comment by yakov116** [comment]
Can we give it another chance? I'll wait for Sindre but I really liked the feature.

**Comment by sindresorhus** [comment]
Too bad. I use this feature all the time. Only saves me some seconds though, so I understand it might not be worth the continuous effort.

**Comment by fregante** [comment]
> Can we give it another chance

Only if you push a PR before this one is merged. ⏲

**Comment by fregante** [comment]
> so I understand it might not be worth the continuous effort.

The issue is that not only is it [troublesome](https://github.com/sindresorhus/refined-github/issues?q=+Recently+Pushed+Branches), it breaks badly: https://github.com/sindresorhus/refined-github/issues/3333 https://github.com/sindresorhus/refined-github/issues/2044 https://github.com/sindresorhus/refined-github/issues/3748

I think its main reason to exist (to avoid content jump) could be brought back in a saner manner:
	1. hide the banner by default
	2. detect its presence and add a "fresh branches available" notification button icon somewhere. The style of a custom 16x16 button is much more manageable

Clicking the button would unhide the regular bar in its regular position. This adds a click but doesn't affect the style.

Alternative solutions welcome.

**Comment by yakov116** [comment]
@fregante if you are expecting that quickly, don't think I will be able to do that. I can try to fix the css classes.

**Comment by yakov116** [comment]
45 minutes of trying... I give up. I though they just changed the classes. looks like they changed some layout.

You win.... I lose.

**Comment by fregante** [comment]
Let's try to live without this feature for a while and open a new specific issue to an issue you'd like to solve.

For historical purposes, the original request issues: 
- more places: https://github.com/sindresorhus/refined-github/issues/140
- no jump: https://github.com/sindresorhus/refined-github/issues/851

**Pull request merged**
