### PR TITLE
Distinctly identify commits that refer pull request

### LINKED ISSUE #1579: Distinct referenced commits style
### Before

before

### Before (with explanation of the problem)

Confusing, looks like the pull request commits and the commit that references this pull request are in the same branch.

before-explanation

### After

after

### Style

```css
.discussion-item-header[id^=ref-] .discussion-item-icon {
  background-color: #6db2ff;
  color: #ffffff;
}

.discussion-item-header[id^=ref-]::before {
  content: '';
  position: absolute;
  display: block;
  z-index: -1;
  left: -25px;
  top: -40px;
  width: 2px;
  height: 140px;
  background-color: #ffffff;
}

.discussion-item-header[id^=ref-commit-] + .discussion-item-body .timeline-commits .commit .commit-icon {
  color: #6db2ff;
}

.discussion-item-header {
  position: relative;
}

.discussion-item-header[id^=ref-commit-]::after {
  content: '';
  position: absolute;
  display: block;
  z-index: 0;
  left: -25px;
  top: 30px;
  bottom: -20px;
  width: 2px;
  background-color: #6db2ff;
}

.discussion-item-header[id^=ref-commit-] + .discussion-item-body .timeline-commits {
  position: relative;
}
```

https://gist.github.com/sompylasar/99b5d307da3168b833c1119fb95caf11

### PR DESCRIPTION
**Pull request by dakshshah96**
Fixes #1579

### CODE REVIEW

**Comment by bfred-it** [comment]
Can you post a URL where this would appear?

**Comment by dakshshah96** [comment]
@bfred-it You can take a look at this issue: https://github.com/sindresorhus/refined-github/issues/226

**Comment by bfred-it** [comment]
## Bug

This also affects regular references (before/after this PR): 

issue reference

## Note

It looks nice, but I don't know if it fixes the issue discussed:

> Confusing, looks like the pull request commits and the commit that references this pull request are in the same branch.

commit reference

I wonder if they should be taken completely off the line (`margin-left: 100px`):
    
offset

Also perhaps that blue makes it look **more** important on the timeline, rather than less important. Maybe we should _only_ use `margin-left`

**Comment by dakshshah96** [comment]
I'll try fixing the bug now.

I agree that the blue does make it look more important on the timeline. Only using `margin-left` seems like a good solution.

**Comment by sompylasar** [comment]
@bfred-it

I agree with blue vs margin : more-important vs same-importance.

Also some time later after making these styles I noticed that GitHub changed their markup and it became harder-or-impossible-with-CSS-only to determine the conditions for style application.

So reliability of this code has to be tested on a variation of scenarios (the community should definitely have more of them than me alone).

**Comment by jerone** [comment]
I see the vertical line as a timeline, this can contain commits, but also comments and thus also references. But the reference contains a description and the commit where reference happened. My suggestion would be to just combine them and remove the commit icon.

**First one has the commit icon removed:**
image

**Comment by bfred-it** [comment]
> My suggestion would be to combine them by removing the commit icon

Yo, that's so smart and obvious that GitHub should pick it up immediately.

@lukehefson plz

---

Combining them is a little harder since they are technically two whole different commits.

**Comment by jerone** [comment]
> Combining them is a little harder

Sorry, I didn't meant to combine them to hide. More semantically combine them *by* removing the icon.

Is there an example where multiple commits are in one reference? I was thinking, maybe we can indent the commit icon only.

**Pull request closed without merging**
