### PR TITLE
Default branch link: add support for forked repos

### PR DESCRIPTION
**Pull request by bfred-it**
Forks display the default branch as `original-repo:original-repos-branch`. 

This would break the old code.

We can't reliably detect the forks' default branch but in most cases it should match the original repo.

I thought we could support both the current repo's and the original repo's default branch.

Live example: https://github.com/jamiebuilds/refined-github/tree/tooltips/source

### CODE REVIEW

**Comment by bfred-it** [comment]
It turns out that the links are completely wrong, sadly.

On forks, GitHub compares each branch to respective branches on the origin's… unless they don't exist.

## Examples: 

New branch on fork: https://github.com/stivaugoin/refined-github/tree/add_pull-request_hotkey

> This branch is 4 commits ahead, 1 commit behind sindresorhus:master.

Pre-existing branch on fork: https://github.com/stivaugoin/refined-github/tree/github-follow

> This branch is even with sindresorhus:github-follow.

Sadly, there's no way to determine when GitHub refers to the default branch and when it just points to the origin's same-branch.

So we have to remove these buttons from forks altogether.

**Comment by sindresorhus** [comment]
Could we request the data we need by fetching a different page or even using the API?

**Comment by bfred-it** [comment]
It looks like it:

```
❯ curl https://api.github.com/repos/jamiebuilds/refined-github
{
  "id": 121555112,
  "name": "refined-github",
  "full_name": "jamiebuilds/refined-github",
  "default_branch": "master",
  "parent": {
    "id": 51769689,
    "name": "refined-github",
    "full_name": "sindresorhus/refined-github",
    "default_branch": "master"
  },
  "source": {
    "id": 51769689,
    "name": "refined-github",
    "full_name": "sindresorhus/refined-github",
    "default_branch": "master"
  }
}
```

**Comment by sindresorhus** [comment]
Cool. Let's use the API then.

**Comment by bfred-it** [comment]
Open a new issue? 😄 

Not sure I'll implement it

**Comment by sindresorhus** [comment]
Done: https://github.com/sindresorhus/refined-github/issues/1173

**Pull request closed without merging**
