### PR TITLE
Fixed notifications indicator

### LINKED ISSUE #527: Broken notifications indicator
I think a bug was introduced in https://github.com/sindresorhus/refined-github/commit/f073dd285750a9116722918c5efea40193fd58b5 which causes the notifications indicator to show that you've no unread notifications in some cases. Works in the notifications page though.

bug

### PR DESCRIPTION
**Pull request by neighborhood999**
I'm going to try to fix #527 .

### CODE REVIEW

**Comment by bfred-it** [comment]
This doesn't work at all if there are no notifications. I'm working on a small reorg of mark-unread.js

**Comment by neighborhood999** [comment]
@bfred-it Okay, Thank you.

**Comment by bfred-it** [comment]
The `data-ga-click` attribute check was a good idea though! I used it in https://github.com/sindresorhus/refined-github/pull/529/commits/249aac81aac4efd8c145ad3643803664c5378a94

**Comment by neighborhood999** [comment]
I'm so happy that idea can help! Expect you will fix it. Thank you.

**Pull request closed without merging**
