### PR TITLE
Avoid `conversation-activity-filter` duplicates

### LINKED ISSUE #4067: Multiple eye icons
img
https://github.com/harryfei/which-rs/pull/30

This only happens occasionally.

### PR DESCRIPTION
**Pull request by kidonng**
Fix #4067

See https://github.com/sindresorhus/refined-github/issues/4067#issuecomment-792273884 for details

## Test URLs

1. Open issue https://github.com/sindresorhus/refined-github/issues/4067
2. Go to issues tab
3. Open any issue again

## Screenshot

None

P.S. maybe we should rewrite all `onetime` usage for `selector-observer` with `observer.abort()`?

### CODE REVIEW

**Comment by fregante** [comment]
How is this different? The `observe` export is just a pre-bound `new SelectorObserver` from what I saw

**Comment by kidonng** [comment]
https://github.com/josh/selector-observer/blob/b811bb5d13cba9940026430f92a6760d5f9e365c/lib/selector-observer.js#L73

`observer.abort()` will remove the selector from `SelectorObserver`'s ` selectorSet` (yup, that's two different observer object).

**Comment by fregante** [comment]
I opened https://github.com/josh/selector-observer/issues/32

**Review by fregante — APPROVED** [review]
The code looks right. I don’t know if it fixes the issue because I wasn’t able to replicate it. 

As for the deinit, yeah that’s not a bad idea

**Comment by yakov116** [comment]
> `observer.abort()` will remove the selector from `SelectorObserver`'s ` selectorSet` (yup, that's two different observer object).

Shouldn't this be changed in all features?

**Review by ahmed2m — APPROVED** [review]
Looks like it solved the issue for me.

**Comment by cheap-glitch** [comment]
Can confirm this fixes the bug (tested on Firefox).

> I don’t know if it fixes the issue because I wasn’t able to replicate it.

It happens when navigating between conversations using "linked references". E.g. when clicking on the "Fix 4067" link at the top of this page, then on the PR link at the bottom, and repeating this several times:

Screenshot_2021-03-07 Prevent `conversation-activity-filter` from running multiple times by kidonng · Pull Request #4072 ·

**Comment by fregante** [comment]
> > `observer.abort()` will remove the selector from `SelectorObserver`'s ` selectorSet` (yup, that's two different observer object).
> 
> Shouldn't this be changed in all features?

Most features already have `onetime` and don’t have a deinit, so they aren’t affected by https://github.com/josh/selector-observer/issues/32

But yeah it’s a good idea, as I said previously.

**Comment by fregante** [comment]
Should we disable this feature in the hotfix? I don’t think we’ll do another release just yet, but I don’t want people to be annoyed by it.

**Comment by yakov116** [comment]
> Should we disable this feature in the hotfix branch?

Noooooo. I used this a few times today. 

Its great people can "see" the feature very well 👁️

**Comment by fregante** [comment]
> > Should we disable this feature in the hotfix branch?
> 
> Noooooo. I used this a few times today.

Sideloaded extensions aren't affected; Only store-downloaded ones are.

**Comment by fregante** [comment]
👆 

In this specific case it doesn't matter but, as a general pattern, what do you think if `deinit` is an array of functions to call? This has a few advantages:

- no risk of overriding the single `let observer` variable
- lets you have multiple deinit callbacks without having to defined each separately at the top of the file. This happens only once for `selector-observer` but there's also `delegate`, for which we could also do the same, everywhere

**Review by fregante — APPROVED** [review]

**Pull request merged**
