### PR TITLE
Remove projects from sidebar if there are no projects

### LINKED ISSUE #977: Remove Projects from the sidebar if there are no Projects
Similar to the removal of the Projects tab if there are no projects, I think we should remove the Projects section in the issue/PR sidebar if there are no projects to select there.

There are both repository and organisation projects in there so we should check the contents of the selector instead of using the number of projects in the repo as we do for the repository tab.

You cannot create Projects from that selector so there's no reason you would need it unless you already have projects created.

### PR DESCRIPTION
**Pull request by notlmn**
Closes #977
Replaces and closes #1945

This features removes the projects section in the issue and PR sidebar if the user doesn't have any permissions or if there are no projects to select.

### CODE REVIEW

**Comment by bfred-it** [comment]
- `safeElementReady` doesn't apply to `onAjaxedPages` because `onAjaxedPages` waits for dom ready
- only `isPRConversation` has the sidebar

**Comment by notlmn** [comment]
> Great solution! It works already, however I'd like to see some caching, like in `releases-tab.tsx`:

Wouldn't that conflict with organization level projects. What I mean is that if we cache count for each repo and a project is added at organization level, the user might have to wait until the cache expires.

Not saying its a bad idea, but thinking if there would be any problems, because releases is for a single repo, but projects work at both repo and organization level!? 🤔🤷‍♂️

**Comment by bfred-it** [comment]
That raises another question: is this piece of code correctly counting the projects in organizations as well?

And also: do closed projects appear in the dropdown?

> the user might have to wait until the cache expires

That's kinda the issue with all caches. The workaround would be to have a short cache (1 day)

**Comment by bfred-it** [comment]
Alternatively, instead of hiding the Projects, we could condense the sidebar:

- hide all the _Empty_ messages from the sidebar:
  
    


- hide all the empty sections, the current user can't do anything about them


    

Related feature request to keep in mind: https://github.com/sindresorhus/refined-github/issues/421

**Comment by notlmn** [comment]
> That raises another question: is this piece of code correctly counting the projects in organizations as well?

Yup, the partially loaded DOM contains item listing for both repository and organization projects combined in their own containers. Here we are counting these combined projects ([example](https://github.com/notlmn-dump/test/issues/1/show_partial?partial=issues%2Fsidebar%2Fprojects_menu_content)).

-------------

> And also: do closed projects appear in the dropdown?

Just tested it, no they don't. 🎉

--------------

> That's kinda the issue with all caches. The workaround would be to have a short cache (1 day)

I'll see what I can do with caching, might take time though.

**Comment by notlmn** [comment]
> Alternatively, instead of hiding the Projects, we could condense the sidebar

Already thought of generalizing this feature hide all the empty sidebar stuff, but stopped after looking at "Assignees", that looks like a useful thing to have even when it doesn't have anything to show, or maybe that's just me.

Open to other thoughts too! 😉

**Comment by bfred-it** [comment]
@sindresorhus agreed that this is the way to go, `clean-discussion-sidebar`: https://github.com/sindresorhus/refined-github/pull/1965#issuecomment-485492676

No fetches; just hide "no content" if the user is a collaborator or hide the whole section for all other users.

I would go as far as hiding the section header for `Labels` and `Notifications`:

clean-sidebar

**Comment by bfred-it** [comment]
That's not what I meant 😅

> 2. Hide "None yet", "No milestone", etc for collaborators

The section should stay there for collaborators, it should only hide that extra text. This feature should not require any `fetch`es

**Comment by notlmn** [comment]
> The section should stay there for collaborators, it should only hide that extra text. This feature should not require any `fetch`es

That does not actually align with what #977 and #421 sounds, but can be manageable. Will update in a bit.

**Comment by notlmn** [comment]
<details>
<summary>Screenshots</summary>

## Repo with no permissions
### PR to some repo
| Before | After |
| :-: | :-: |
| 1-before | 1-after |

### Issue on some repo
| Before | After |
| :-: | :-: |
| 2-before | 2-after |

## Repo with permissions
### Assigned issue with projects
| Before | After |
| :-: | :-: |
| 3-before | 3-after |

### Non-assigned issue with projects
| Before | After |
| :-: | :-: |
| 4-before | 4-after |

</details>

-----------------

> 1. Hide empty sections for regular users

Done.

-----------------

> 3. Move "Assign yourself" next to "Assignees" header, if empty

That's not possible, the header itself is a `<details>` element, can't put `button` inside another interactive element. Can `position` it `absolute`ly, but I don't see the point in that.

**Comment by notlmn** [comment]
> 4. I would go as far as hiding the section header for `Labels` and `Notifications`

I don't know good this looks like. Is this okay?
save

**Comment by bfred-it** [comment]
> The section should stay there for collaborators, it **should only hide that extra text. This feature should not require any `fetch`es**

This

**Pull request closed without merging**
