### PR TITLE
Add download folder button

### LINKED ISSUE #815: Download specific folder?
Sometimes you're browsing through a massive codebase and want to download a suite of files, sometime there a single example in the docs which you want to download. Is this possible?

### PR DESCRIPTION
**Pull request by bfred-it**
Closes #815 

It will look like this:

screenshot

The download page itself can be discussed and improved on [the downloader tool's repo](https://github.com/bfred-it/download-github-dir)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Would be nice if we had a token field in our options, so we could just use it for this too.

**Comment by bfred-it** [comment]
Yeah once we get that in our settings I can update the tool to accept the token via URL parameters, if that doesn't sound too much of a risk.

**Comment by sindresorhus** [comment]
Yes, no more risk than trusting us with the token in this extension. I would move the `download-directory.github.io` repo to your account, so it's immediately clear who they're trusting (a member of this extension).

**Comment by bfred-it** [comment]
>  I would move the `download-directory.github.io` repo to your account

I can't. That nice URL is only available to the `download-directory` org. It initially was `bfred-it.github.io/github-download-dir`, then `github-download-dir.bfred.it`, then that.

I can add my `© Name` in the tool itself but it's not like anyone knows me anyway.

**Comment by bfred-it** [comment]
Readme screenshot

screen shot 2018-01-17 at 20 11 59

**Comment by sindresorhus** [comment]
Ah ok, maybe add that that URL is trusted by `Refined GitHub`, so people are immediately aware how they ended up on a different URL.

**Comment by amarlearning** [comment]
@bfred-it @sindresorhus I think you people are looking for [this](https://github.com/amarlearning/Github-Sectory#github-sectory).

**Comment by bfred-it** [comment]
We’re definitely not looking for python tools in an browser extension 😃

**Comment by kingheath** [comment]
473044022022cc3f52b73fa5ba9ca826e7104da48ff944b9611b8bf1a87a4ffc77e50573b802207c15de2ddcede3f9289598642c8fc440288e15db18b811ececae073efb901d7a012102679a681d9b5bf5c672e0413997762664a17009038674b806bf27dd6b368d9b67
--

[btc.com](url)

**Comment by JohnnyJTH** [comment]
I could just be doing something wrong but I can't see the download button in a folder. The readme screenshots show an older UI. The button row is gone in the new github design I think?

**Comment by stamminator** [comment]
Reporting the same as @JohnnyJTH. No more download button.

**Comment by cheap-glitch** [comment]
I have one on Firefox with RGH v22.1.18. It's in the little dropdown on the far left:

image

**Comment by stamminator** [comment]
@JohnnyJTH @cheap-glitch Looks like the issue is taking place if it's not the default branch https://github.com/refined-github/refined-github/issues/5335#issuecomment-1020881240

**Comment by Eversor** [comment]
Confirm not working anymore on chrome. v22.12.15

**Comment by fregante** [comment]
Please don't leave comments on 5-year-old issues. Open a new bug report instead

**Pull request merged**
