### PR TITLE
Restore `faster-reviews` autofocus

### PR DESCRIPTION
**Pull request by FloEdelmann**
As mentioned in #3621. You can test it right here in this PR :wink:

### CODE REVIEW

**Comment by fregante** [comment]
I think this is a GitHub but we could wait to be fixed.

This feature merely mirrors the native "Add your review" button that appears when someone requests your review:

**Comment by FloEdelmann** [comment]
I use it all the time, that's why I wanted to fix it. For quite some time now we are adding the "review now" button for no good reason, it leads to exactly the same page/state as the "Files" tab does.

I didn't know about that other place where the link is used as well. So maybe GitHub has actually an incentive to fix it themselves.

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
Alternatively, this could be implemented as an additional init in the same file so that it fixes the native `#submit-review` hash as well.

**Comment by FloEdelmann** [comment]
I've changed it back to `#submit-review`.

> could be implemented as an additional init in the same file

Why an additional init?

**Pull request merged**
