### PR TITLE
Drop, sort, move, reword features in the readme

### PR DESCRIPTION
**Pull request by bfred-it**

### CODE REVIEW

**Comment by jgierer12** [comment]
How about we move the features into a separate file? I always felt they cluttered the readme and distracted from the important stuff. We could still show a few new features + a link to the features file.

**Comment by bfred-it** [comment]
What’s the “important stuff”? 😃 

The readme is the extension’s landing page so it makes sense to me to include all it can do.

**Comment by bfred-it** [comment]
If anything I’d move “customization” to Contribute.md and Maintainers to its own file (it’s just for vanity anyway)

Once that’s gone… only the features and intro are left.

**Comment by sindresorhus** [comment]
> If anything I’d move “customization” to Contribute.md

It doesn't really fit in contribute.md as it's not about contributing to this project. I think we should rather just put it in a `<details>` tag.

> Maintainers to its own file (it’s just for vanity anyway) or drop it entirely since there’s a GitHub page dedicated to it already.

That's really up to you and the other team members.

**Comment by bfred-it** [comment]
> That's really up to you and the other team members.

For me the GitHub's contributors page is more than anyone needs: https://github.com/sindresorhus/refined-github/graphs/contributors

**Comment by bfred-it** [comment]
>  given that people don't have a choice nor are informed when extensions update, the commit list is the most appropriate and comprehensive changelog. https://github.com/sindresorhus/refined-github/commits/master
> by @bfred-it

@sindresorhus do you mind if we start prefixing these commits with `Meta:`? Otherwise our _changelog_ is messy to read for the users. I also considered using Travis to create releases on each deployment, but I'm not sure of how easy that'd be.

**Comment by sindresorhus** [comment]
> do you mind if we start prefixing these commits with Meta:?

👍 

> That's really up to you and the other team members.
> For me the GitHub's contributors page is more than anyone needs: sindresorhus/refined-github/graphs/contributors

@jgierer12 @hkdobrev @busches @paulmolluzzo Thoughts?

**Comment by busches** [comment]
Doesn't bother me, that's normally where I go.

**Comment by paulmolluzzo** [comment]
I’m fine with that as well.

Alternatively we could remove contributors from the readme and create a contributors file and/or use All Contributors if we want to put in that effort. (https://github.com/kentcdodds/all-contributors)

**Comment by sindresorhus** [comment]
> Alternatively we could remove contributors from the readme and create a contributors file and/or use All Contributors if we want to put in that effort. (kentcdodds/all-contributors)

Nah, that's too much overhead.

**Pull request merged**
