### PR TITLE
Add link to Dependency Graph in More dropdown

### PR DESCRIPTION
**Pull request by busches**
Also changed the Insights link icon to 'Search' since the 'Graph' icon
seemed more fitting for the Dependency Graph

Fixes issue #737

Screenshot:
image

### CODE REVIEW

**Comment by yakov116** [comment]
@busches Why not make the dropdown box bigger?

**Comment by yeskunall** [comment]
I think it'd be better if you could remove the text-wrap. It'd look a bit more pleasing IMO.

**Comment by busches** [comment]
Good call, thankfully github has this class already.

image

**Comment by yakov116** [comment]
Why not use the "package icon?

octicon octicon-gift

**Comment by yeskunall** [comment]
@busches another thing: this already exists, but compare slightly shifted to the left, and it's quite visible now that you've added a new link 😅

**Comment by busches** [comment]
@yakov116 doesn't matter to me, let's see what others think.

Pushing another commit to disable this for GHE, which doesn't support the feature yet.

**Comment by jgierer12** [comment]
How about renaming it to just 'Dependencies' to make it shorter?

**Comment by yeskunall** [comment]
@jgierer12 less verbose, sure, but might not make the point across as well.

**Comment by bfred-it** [comment]
I think Depencies is enough. Also in the last screenshot there’s not enough padding on the right

**Comment by busches** [comment]
@yakov116 I like the package icon better and swapped to it, but it looks a bit weird at that size
image

@bfred-it that's using a GH style :) Outside of hardcoding the width, I can't get the padding on the right to expand without reducing the padding on left.

**Comment by yakov116** [comment]
@busches he did you make it small? It looks like it lost all its quality in that picture

**Comment by busches** [comment]
@yakov116 they're SVGs I used the code they provided https://octicons.github.com/icon/package/

**Comment by bfred-it** [comment]
Current style:

current dropdown

**Pull request merged**
