### PR TITLE
Totally finally fix every single removeDiffSigns bug forever

### LINKED ISSUE #590: Latest releases breaks spaces in PRs
For example: https://github.com/rob3n/yard-frontend/pull/4/files
https://github.com/rob3n/yard-frontend/blob/770ad32d0b60f42aff3c7e61edb5fbfdaecb5bc1/public/index.html

image

But file have spaces
image

### LINKED ISSUE #601: Incorrect spacing in diff
>My commit adds a single line without any preceeding whitespace, but it get's displayed with a small extra indentation (which is confusing).
>
>Correct: (plain github)
screenshot from 2017-07-09 18-45-49
>
>Wrong: (refined github enabled)
screenshot from 2017-07-09 18-45-15
>
>The Raw commit is here: https://github.com/dunst-project/dunst/commit/717c747a8caf0f823da0e4e45bbb632ef46c68ee

*@bebehei in https://github.com/sindresorhus/refined-github/issues/590#issuecomment-313931801*

### PR DESCRIPTION
**Pull request by bfred-it**
I think it fixes #601
Definitely fixes #590 
Remembers #557 
Honors #396
Wishes luck to #382
Prays for #317 because that's still a separate issue
Blames it all on #254

### CODE REVIEW

**Comment by sindresorhus** [comment]
I tested all the test cases we have in various issues and seems to solve them.

**Comment by sindresorhus** [comment]
Ugh, encountered a regression again. See: https://github.com/sindresorhus/eslint-plugin-unicorn/pull/99/files#diff-2d660eee44e5e1d2a779ac70f6ad47a6R22

screen shot 2017-07-10 at 17 29 13

**Comment by sindresorhus** [comment]
It also adds space in front of colons... Super weird.

screen shot 2017-07-10 at 17 55 29

https://github.com/sindresorhus/eslint-plugin-unicorn/pull/100/files#diff-126eaa52c8d3f2872d9763009c8365e3R6

**Comment by bfred-it** [comment]
blindssuck

**Comment by ramlmn** [comment]
image

**Pull request merged**
