### PR TITLE
Move close/cancel buttons to the left - Fixes #410

### LINKED ISSUE #410: Move the "Close issue" button to the left
It's not like this is a problem you see each and every day, but when it happens, it's kind of annoying: From time to time people fat-finger on the "Close issue" button when they actually meant to submit a comment.

image

It would be nice to create a little more space between those buttons, maybe even to completely move the "Close issue" button to the left.

image

What do you think?

### PR DESCRIPTION
**Pull request by Loilo**
Moves the "Close issue" button in the issue comment section to the left for the sake of accuracy.

### CODE REVIEW

**Comment by Loilo** [comment]
Sure.

**Comment by Loilo** [comment]
Huh. I wanted to take a screenshot in Firefox and it seems the comment box looks completely different there. It got an endless stream of additional buttons and a "Styling with Markdown is supported" in place where the "Close issue" button should have gone. 🤔

image

Any suggestions? I think putting the button kind of in the mid of the row is weird.

The only solution that's spontaneously coming to my mind is to not put the "Close issue" button on the left, but just increase the distance to the "Comment" button. (That may look... weird? Badly designed? Not sure.)

Hm.

(As I have not done too many Pull Requests yet: Is this appropriate to discuss here or would it rather go into the original issue?)

**Comment by hkdobrev** [comment]
@Loilo I'd suggest to not worry about Firefox now. All these additional buttons are the default for GitHub now and we don't have full Firefox support for the extension yet. We'd need look into it more, but we have an issue about that already: #71. Just take the screenshot in Chrome so we could merge as it'd help Chrome users for sure. Separately, we need to spend some time fixing Firefox issues probably with separate issues for outstanding things.

**Comment by Loilo** [comment]
Uhm. Yes. Let's assume that I did not totally forget the fact that this is a Chrome extension. 🙈

**Comment by hkdobrev** [comment]
> Uhm. Yes. Let's assume that I did not totally forget the fact that this is a Chrome extension. 🙈

Hehe 😆 No worries. It should soon be a Firefox extension as well --> #403.

**Comment by Loilo** [comment]
Okay, updated screenshot to use the moved button, the current GitHub design (font, primary button color) and @sindresorhus's latest avatar. 😝

**Comment by jgierer12** [comment]
> Huh. I wanted to take a screenshot in Firefox and it seems the comment box looks completely different there than in Chrome

That's weird, which version of Firefox do you use? For me (FF 53.0.2) it looks like this: Comment form

**Comment by Loilo** [comment]
I may need to clarify this: My firefox does not have any of the Refined GitHub scripts running. I only wanted to make the screenshot there to see if its rendering is superior to Chrome in any way.

**Comment by jgierer12** [comment]
@Loilo ah, that makes sense. Thanks for clarifying!

**Comment by jgierer12** [comment]
How about moving the "Cancel" button (when editing a comment) as well for consistency?
Edit comment buttons

**Comment by Loilo** [comment]
I don't care, but I agree that this would actually give it a more consistent look. I'll add that.

**Comment by Loilo** [comment]
@jgierer12 Can you tell me where to find those inline commenting option?

**Comment by hkdobrev** [comment]
@Loilo 
> Can you tell me where to find that inline commenting option?
1. Go to a PR
2. Go to Files tab.
3. Click <kbd>+</kbd> button on the left of any line. E.g. https://github.com/sindresorhus/refined-github/pull/414/files#diff-83ab1d10d74dc75c62ac9cf612cfce51R581

**Comment by Loilo** [comment]
Thanks.

**Comment by Loilo** [comment]
Regarding the inline comments: Would you only move the "Cancel" to the left or the "Add single comment" option as well?

Thematically, only the Cancel button should go left. Regarding the issue this PR tries to solve—misclicking—both should go left.

Thoughts?

**Comment by jgierer12** [comment]
> Would you only move the "Cancel" to the left or the "Add single comment" option as well?

Yes, I'd only move "Cancel"

**Comment by hkdobrev** [comment]
I'd prefer only the cancel button to go left.

You already have a shortcut for the primary button - <kbd>⌘</kbd>/<kbd>Ctrl</kbd>+<kbd>Enter</kbd>. And also a misclick on the other button is not a destructive action.

**Comment by Loilo** [comment]
Okay, that's added too.
And <kbd>⌘Enter</kbd> was new to me, thanks. 👍

**Comment by sindresorhus** [comment]
@Loilo Can you also add it to the feature highlight in the readme? https://github.com/sindresorhus/refined-github#highlights

**Comment by Loilo** [comment]
There you go.

**Comment by hkdobrev** [comment]
Thanks! 🎉

**Comment by Loilo** [comment]
My pleasure. 🙃

**Comment by jgierer12** [comment]
Great work @Loilo 😄

**Comment by Loilo** [comment]
Thanks. I'm thinking of aiming for #341 next, but I'm not sure yet if I've got the time. :)

**Pull request merged**
