### PR TITLE
Build icons on demand

### PR DESCRIPTION
**Pull request by bfred-it**
SVG elements are currently created on every page, even if they're unneeded. This change makes them on-demand.

Also: dom-chef@2 dropped the automatic cloneNode behavior, so something like this is necessary.

✅ ~~**Warning:** dom-chef currently has an SVG bug; this PR depends on https://github.com/vadimdemedes/dom-chef/pull/12~~

### CODE REVIEW

**Comment by sindresorhus** [comment]
With this change the "Releases" tab is gone and https://github.com/sindresorhus/refined-github/issues/727.

**Comment by busches** [comment]
Everything is working for me, I can't reproduce @sindresorhus's findings.

**Comment by hkdobrev** [comment]
OK, playing a bit more with it I've encountered the following JS error in the Chrome extension which I think is from this change:

> Uncaught `HierarchyRequestError`: Failed to execute `'replaceWith'` on `'Element'`: The new child element contains the parent.
> 
> content.js:1720 (anonymous function)

```js
viewButton.replaceWith(Object(dom_chef["h"])
```

**Comment by bfred-it** [comment]
@sindresorhus I think you had skipped `npm i`

@hkdobrev that was due to dom-chef's old cloning behavior. Fixed now

**Comment by sindresorhus** [comment]
> @sindresorhus I think you had skipped npm i

Ugh, yeah.

**Pull request merged**
