### PR TITLE
Add `oldest-newest-commit-list` feature

### PR DESCRIPTION
**Pull request by eranshmil**
This feature adds two new links (Oldest and Newest) to the commit list pagination.
The `api3` url is now exposed because I didn't want to make too many changes to support `head` requests.

# Test
https://github.com/sindresorhus/refined-github/commits/master

# Before
image

# After
image

### CODE REVIEW

**Comment by bfred-it** [comment]
How often do you need to reach the first commit though?

**Comment by eranshmil** [comment]
Personally, I need that often when trying to investigate something in open source projects. The blame feature isn't enough for me.

**Comment by sindresorhus** [comment]
I could see the use-case for "Newest" to go back to the first page, but I don't think I ever needed to see the oldest commits. And I don't think either are useful enough to make the default navigation noisy. I think these would be better as either keyboard shortcuts or links somewhere that are not visually disturbing the normal navigation.

**Comment by sindresorhus** [comment]
Maybe they could be small faded out links, not buttons, in positions like this:

Screen Shot 2019-04-17 at 20 56 00

**Comment by bfred-it** [comment]
The links could be more discrete chevrons «»

`Newest` is technically already accessible by selecting the current branch in the branch selector (two clicks though)

There’s a big implementation difference between Newest and Oldest, if we decide that Oldest isn’t worth the hassle (2 API calls on every Commits page), we could just add a Newest link

**Comment by eranshmil** [comment]
Well, I'd love to have the oldest button.
But if you think it's not worth the hassle, I don't think there's a reason to add only the newest button.

**Comment by bfred-it** [comment]
Please run this to delete the tags from your fork and locally, we keep pulling them from your fork and pushing them to this repo (we no longer use tags)

```sh
git tag -d $(git tag | grep -E '.')
git ls-remote --tags --refs origin | cut -f2 | xargs git push origin --delete
```

**Comment by eranshmil** [comment]
> Please run this to delete the tags from your fork and locally, we keep pulling them from your fork and pushing them to this repo (we no longer use tags)
> 
> ```shell
> git tag -d $(git tag | grep -E '.')
> git ls-remote --tags --refs origin | cut -f2 | xargs git push origin --delete
> ```

I did that, is it ok now?

**Comment by bfred-it** [comment]
It is thanks! And sorry if it sounded like it was your fault, I worded it badly

**Comment by eranshmil** [comment]
> It is thanks! And sorry if it sounded like it was your fault, I worded it badly

That's fine. :)

Really appreciate your hard work!

**Comment by eranshmil** [comment]
> Well, I'd love to have the oldest button.
> But if you think it's not worth the hassle, I don't think there's a reason to add only the newest button.

Please let me know what's your decision about this feature, going forward with both of the buttons or just close this PR?
Thanks!

**Comment by bfred-it** [comment]
I'll close this for now and I'll only implement the Newest button

**Comment by corysimmons** [comment]
fwiw I wish Oldest button got merged. I frequently just want to see how old a project is and where it started off out of sheer curiosity.

**Comment by yakov116** [comment]
@corysimmons how old is already there

**Comment by corysimmons** [comment]
@yakov116 I can't seem to find it. :\

**Comment by yakov116** [comment]
@corysimmons its on the repo bar. It was one of the last features added

**Comment by corysimmons** [comment]
Ah, that explains why I missed it. Thank you so much.

**Pull request closed without merging**
