### PR TITLE
Make `hide-zero-packages` more reliable

### LINKED ISSUE #4472: `hide-zero-packages` never runs
Test on https://github.com/sindresorhus

This is because the detection is not dom ready safe.
https://github.com/sindresorhus/refined-github/blob/6f2b3731cfcbc4af1915dac0cb35526594df141f/source/features/hide-zero-packages.tsx#L17-L24

### PR DESCRIPTION
**Pull request by yakov116**
Close #4472 

## Test URLs
   https://github.com/sindresorhus (no packages)
I cannot find any user with packages. Anyone know of a test URL?

## Screenshot
image

### CODE REVIEW

**Comment by fregante** [comment]
> I cannot find any user with packages. Anyone know of a test URL?

I've probably never seen anyone using them. Maybe some GitHub developers? A twitter search might get you some results

**Comment by yakov116** [comment]
> I've probably never seen anyone using them. Maybe some GitHub developers? A twitter search might get you some results

No luck checked 235 accounts! @kidonng how did you test?

**Comment by kidonng** [comment]
I used to have published some packages on GitHub, but I've removed them for, well, obvious reasons.
I guess the situation is that, GitHub packages is more likely to be used a. in private or b. under organization accounts. Perhaps the only way to test is give some fake data 😅

**Comment by fregante** [comment]
Here's a package https://github.com/primer/components/packages/10922

**Comment by yakov116** [comment]
@fregante those are on a repo, which is not handled by this feature.

I need on a user.

**Comment by fregante** [comment]
The first is on an org: https://github.com/orgs/primer/packages
Still not applicable?

**Comment by yakov116** [comment]
Nope

```
include: [
		pageDetect.isUserProfile
	],
	exclude: [
		// Keep it visible on your own profile due to #3737
		pageDetect.isOwnUserProfile
	],
```

**Comment by fregante** [comment]
Why not? It also has a package tab

**Comment by fregante** [comment]
Anyway, a Google search turned up https://github.com/srepollock?tab=packages

**Comment by yakov116** [comment]
And... The only way is a query as the count is not displayed.

Drop Feature?

**Comment by yakov116** [comment]
> Why not? It also has a package tab

I think because the count was not displayed. I can blame it

**Comment by fregante** [comment]
The screenshot in your post was taken from the readme. That makes zero sense

**Comment by yakov116** [comment]
FYI it was not I took it from https://github.com/sindresorhus/refined-github/pull/3573

Besides
> No luck checked 235 accounts!

The point is to know it is working, I could have made a new one. Whatever.

**Comment by fregante** [comment]
> The point is to know it is working, I could have made a new one. Whatever.

How could it be working if the count is totally missing everywhere? The feature just couldn't work at all.

> FYI it was not I took it from #3573

The screenshot in PRs is meant to demonstrate the issue or the bugfix. Taking random existing screenshots doesn't help and it's not what the template asks.

> I don’t know why I have to explain how to follow a template in every PR you open.

**Pull request closed without merging**
