### PR TITLE
Fix alignment of reaction avatars in comments and reviews

### PR DESCRIPTION
**Pull request by ramlmn**
| Before | After|
|---|---|
| image | image |

### CODE REVIEW

**Comment by ramlmn** [comment]
Can someone have a look at this?

/cc @sindresorhus @bfred-it @hkdobrev

**Comment by ramlmn** [comment]
The PR is for aligning avatars in **review comments**, but also slightly adjusts avatars in **regular comments**.

e.g. https://github.com/sindresorhus/refined-github/pull/821#discussion_r151914341

**Comment by bfred-it** [comment]
Got it, but the number is now misaligned and I'm not sure that I like the tighter spacing, that's why I meant.

**Comment by ramlmn** [comment]
> but the number is now misaligned

Everything is actually perfectly aligned vertically now
* before:
  image

* after:
  image

-----------------------------

> I'm not sure I like the tighter spacing

Should I increase the spacing (like the following)?
* without added spacing:
  image
* with added spacing:
  image

**Comment by bfred-it** [comment]
Look, it's not aligned in your _after_ screenshot. The red lines have the same length

33469695-689678fc-d68a-11e7-9323-70e3e3a5f0db

**Comment by ramlmn** [comment]
Sorry, my bad. Is was looking only if the items we aligned inside the content-box, instead of the border-box.

Now:
image

**Comment by bfred-it** [comment]
Still off compared to the original. Make sure that the text vertical alignment and emoji-text spacing matches the original. Now they're too close.

**Comment by ramlmn** [comment]
> I'd rather not seen any changes to anything but the avatars' vertical alignment

Fixed in the recent commit.

after

**Comment by bfred-it** [comment]
I still see everything moving

**Comment by ramlmn** [comment]
Can I get a visual diff from your side?

**Comment by bfred-it** [comment]
(Gifs show no refined, refined@`master`, refined@this-pr)

Before f4fd6f1 (👍 and `117` move up)

old

After f4fd6f1

new

**Comment by ramlmn** [comment]
Merge at will!

**Pull request merged**
