### PR TITLE
Highlight closing PRs in open issues and PRs

### LINKED ISSUE #1116: Automatic "has PR" tag
Like #1078 shows what PR closed an issue, we can show what PR _will_ close an issue.

Like for #1078, we already have this information somewhere in the thread:

info icon

Perhaps we can use the same style GitHub uses to link to PRs in branch pages that have open PRs, example: https://github.com/sindresorhus/refined-github/tree/merge-commits

branch with pr

Mockup for this feature:

link mockup

To keep in mind: there might be multiple PRs trying to close an issue so multiple buttons would be shown in that case.

### PR DESCRIPTION
**Pull request by bfred-it**
Closes #1116

with label

### CODE REVIEW

**Comment by bfred-it** [comment]
Also works with more closing PRs:

https://github.com/bfred-it-obsolete/test/issues/11

**Comment by bfred-it** [comment]
And since PRs can also close other PRs, it also works on PRs:

https://github.com/bfred-it-obsolete/test/pull/8

**Comment by bfred-it** [comment]
screen shot 2018-03-06 at 21 29 48

**Comment by yakov116** [comment]
@bfred-it Looks like this stopped working 😞

**Pull request merged**
