### PR TITLE
Make Enterprise injection more reliable /2

### LINKED ISSUE #2174: `content.css` not injected on GHE
This was initially discussed in https://github.com/sindresorhus/refined-github/issues/2170

Here is how the feature should work:

Here is how it actually looks on GHE for me (in incognito with no other extensions)

image

### PR DESCRIPTION
**Pull request by bfred-it**
Follows #2111
Fixes #2174 #2173 #2171 https://github.com/sindresorhus/refined-github/pull/2184

cc'ing GHE users @ahatzz11 @gibfahn @rastersize @SivanMehta @NickCraver

### CODE REVIEW

**Comment by bfred-it** [comment]
cc'ing GHE users @hatzz11 @gibfahn @rastersize @SivanMehta @NickCraver

**Comment by tknickman** [comment]
@bfred-it grabbed lated and confirmed this is fixed on GHE `v2.16.10`. Thanks so much!

**Comment by bfred-it** [comment]
Thanks for confirming! If you find any more GHE-related issues let me know

**Comment by tknickman** [comment]
For sure! Feel free to mention me as well if you need help validating / getting examples for anything on GHE

**Pull request merged**
