### PR TITLE
Unhide new suggestions icon

### LINKED ISSUE #1586: New Github Feature "Suggestions" icon is not showing up when refined-github extension is turned on
image

You can still activate the beta feature with `cmd-g` when the extension is enabled, however.

### PR DESCRIPTION
**Pull request by Phrynobatrachus**
resolves #1586

### CODE REVIEW

**Comment by Phrynobatrachus** [comment]
Also, do we still want to hide the @ and # buttons? That CSS rule needs updated more if so. I can do that in this PR too.

**Comment by hkdobrev** [comment]
Let's get this in and we can open a separate issue on reworking all CSS selectors around that toolbar properly.

**Comment by bfred-it** [comment]
Yes we still want to hide those. They make no sense, just press @ and #

**Comment by hkdobrev** [comment]
I think the rest was unhidden for some reason before that. Let's discuss that whole toolbar and the implementation. This was just a quick fix for new GitHub feature.

**Pull request merged**
