### PR TITLE
Fix `suggest-commit-title-limit` input field size

### LINKED ISSUE #3998: `suggest-commit-title-limit` is sized incorrectly, 1-character short
Tested in Safari. Happens when you're about to merge a PR

gif

The field should match the length limit, but it doesn't anymore. Might have to do with `padding` or `box-sizing`

### PR DESCRIPTION
**Pull request by xtianatilano**
Fixes #3998

## Test URLs
Any PR for merge + This 72-char title:

```
123456789 123456789 123456789 123456789 123456789 123456789 123456789 12
```

## Screenshot

Before:
before

After:
suggest-commit-title

### CODE REVIEW

**Comment by fregante** [comment]
In your gif, as you move the cursor from the end to the start, you can see the text shifting by a pixel. This shows that there’s still overflow. 

The 72ch is the correct size here and should not change. This is more likely caused by `box-sizing: border-box`, which should be changed to `box-sizing: content-box`. Does that fixing?

**Comment by xtianatilano** [comment]
Updated. 

`box-sizing: content-box` does fix it, I initially thought that the extra space was kinda too long. 😅

**Review by fregante — APPROVED** [review]
Thank you!

**Review by fregante — CHANGES_REQUESTED** [review]
Tested, actually while it fixes the bug, the final width is longer than 72-chars

gif

**Review by fregante — APPROVED** [review]
Thankfully the fix was easy 
gif

**Pull request merged**
