### PR TITLE
Remove "remove diff signs" feature

### LINKED ISSUE #1444: Github now excludes + and - when copying from diffs
A new change just went live that excludes `+` and `-` when copying the contents of a diff. That feature of the plugin shouldn't be needed now.

### PR DESCRIPTION
**Pull request by kubukoz**
Closes #1444

### CODE REVIEW

**Comment by kubukoz** [comment]
I see there's some extra work so let's mark this WIP for now

**Comment by kubukoz** [comment]
Actually, there also seems to be some CSS. Also, you wouldn't believe how
hard it is to remove a line in Android Chrome...

**Comment by kubukoz** [comment]
Should be ready now, but from the comments in #1444 it seems like GitHub removed this functionality for a while, so we shouldn't merge this until it comes back

**Comment by pbarbiero** [comment]
This is showing up for me currently, I wonder if its a staggered rollout?

**Comment by kubukoz** [comment]
looks like the feature is back...

**Comment by jdreesen** [comment]
For me, too. I had to disable the RGH feature.

**Comment by yakov116** [comment]
@bfred-it ?

**Comment by xt0rted** [comment]
This feature was turned back on this morning, it should be visible to everyone again.

**Comment by yakov116** [comment]
@sindresorhus?

**Comment by kubukoz** [comment]
I'm not familiar with how Enterprise works so I guess you have a good point there :)
Regarding the rollout/removal I would've just suggested to merge this later, but your solution is much better in both of these.

I'm closing this and will link your PR in the original issue. Thanks!

**Comment by yakov116** [comment]
@KattMingMing and @kubukoz See https://github.com/sindresorhus/refined-github/pull/1330#issuecomment-390116635

**Comment by kubukoz** [comment]
hmm... how is that related to this PR?

**Comment by yakov116** [comment]
@kubukoz its related to the fact the GHE will break

**Comment by KattMingMing** [comment]
@yakov116 https://github.com/sindresorhus/refined-github/pull/1451 resolves https://github.com/sindresorhus/refined-github/issues/1444 for GHE and GitHub.com

**Comment by aaiezza** [comment]
I think this may have a caused an issue with the diff view. The first character of every line of a file is now missing in some cases:
image

**Pull request closed without merging**
