### PR TITLE
Enable toggleAllThingsWithAlt on all commits

### PR DESCRIPTION
**Pull request by brunolemos**
This feature was only working on PR pages (files changed tab or pr commit), but not when opening a specific commit outside a PR.

### CODE REVIEW

**Comment by brunolemos** [comment]
Needs to be tested before merging, I commited directly on GitHub.

**Comment by bfred-it** [comment]
Sadly it doesn't seem to work. The label is added but alt+click doesn't toggle more than one.

Tested on https://github.com/sindresorhus/refined-github/commit/4743195ebb971b6ead31224824dd9a150fb0938b

**Comment by brunolemos** [comment]
Do you have any idea why?

**Comment by brunolemos** [comment]
@bfred-it: fixed

**Comment by bfred-it** [comment]
I think this breaks other "things", like [PR comments](https://user-images.githubusercontent.com/25818354/33240033-3e271588-d2af-11e7-93af-13b6e325f65d.gif)

**Comment by brunolemos** [comment]
@bfred-it ready

**Comment by bfred-it** [comment]
Thanks @brunolemos

**Pull request merged**
