### PR TITLE
Meta: refactor `getCurrentBranch`

### PR DESCRIPTION
**Pull request by yakov116**
Follows https://github.com/sindresorhus/refined-github/pull/3166#issuecomment-638210073

### CODE REVIEW

**Comment by sindresorhus** [comment]
```js
x = new URL('https://github.com/private/private/commits/master.atom?token=AEAXKWNR')
		.pathname
		.split('/')
		.slice(6) // Drops the initial https://host/user/repo/route/ part
		.slice(4) // Drops the initial /user/repo/route/ part
		.join('/');

console.log(x);
//=> ''
```

So it seems the `.replace(/\.atom$/, '');` part is moot or the logic is faulty.

**Comment by fregante** [comment]
```js
x = new URL('https://github.com/private/private/commits/master.atom?token=AEAXKWNR')
		.pathname
		.split('/')
		.slice(4) // Drops the initial /user/repo/route/ part
		.join('/');
// -> master.atom
```

**Comment by sindresorhus** [comment]
I'm stupid. Ignore me.

**Comment by fregante** [comment]
I always do

**Pull request merged**
