### PR TITLE
Add collapsible file diffs to compare and commit views

### LINKED ISSUE #58: Minimize/Maximize mouse cursors for PR show in non PR areas
I was casually using the unpacked extension today and noticed the cursor showing up in file headers that don't belong to the PR. Incidentally, we should probably add the behavior to commit review areas now that I think about it but for now, we can nix this bug until we decide to incorporate that behavior.

### PR DESCRIPTION
**Pull request by hkdobrev**
Fix #58

This is an alternative to #59.

Closes #59

### CODE REVIEW

**Comment by hkdobrev** [comment]
OK, `isCommit` check is `false` when the commit is loaded dynamically from clicking a commit link in a PR. It affects both the collapsing behaviour and the patch/diff links added in #66.

Also it still keeps the icons in blob views which #59 fixes. Will work more on that.

**Comment by hkdobrev** [comment]
OK, I've updated the PR with a fix for `isCommit`which fixes a bug in #66 as wll.
I've also improved the CSS selector to not use wildcard selector and to target only file headers which are part of a diff.

@sindresorhus @tdlm @paulmolluzzo What do you think?

**Comment by paulmolluzzo** [comment]
> OK, isCommit check is false when the commit is loaded dynamically from clicking a commit link in a PR.

I think this is a manifestation of the same issue I mentioned here: https://github.com/sindresorhus/refined-github/issues/64#issuecomment-193549236

I'm wondering if we need to add a Mutation Observer whenever you're in a repo and watch if the body changes, then run through the tests to reapply different functionality. The DOM is being updated but doesn't go through the full initialization of the document, so the different tests don't get checked.

Again, this is why things get fixed on a refresh.

Thoughts?

**Comment by hkdobrev** [comment]
@paulmolluzzo It could be useful if we are doing something more complex, but for the time being dynamic checks of the URL are doing the job fine.

Speaking of which I better make `isCommit` a function to keep the style consistent.

**Comment by hkdobrev** [comment]
@paulmolluzzo The same way if you make the `isRepoRoot` check dynamic, it should work without the CSS fix in #65. Haven't tried it though.

**Comment by paulmolluzzo** [comment]
@hkdobrev by making it a function? That might work, I didn't try in my attempt.

**Comment by paulmolluzzo** [comment]
First off, the PR is working as expected currently and I think it can go to master like this.

However, I tested @hkdobrev's theory about making `isRepoRoot` dynamic and since he's here and working on related items it might be better if he did the following:

1. Make `isRepo`, `isRepoRoot`, `isDashboard`, and `isCompare` dynamic and update references to them. This is more consistent.
2. Move `isRepoRoot` to be defined all the way at the top with everything else. @hkdobrev already moved `isCommit` so might as well make it all consistent.
3. Get rid of the extra CSS that hides `#readme.blob #refined-github-readme-edit-link`. This isn't necessary when 1 and 2 above are done.
4. (optional) Rearrange these `const` definitions so that all the reusable "parts" are together (`path`, `ownerName`, etc.) and all the "tests" are together (`isRepo()`, et al). I think it'll be easier to read and more accessible to new people if they're organized.

Nice catch @hkdobrev with this solution! If you add to this PR I'll give it a test.

@sindresorhus if you think the suggestions above are out of scope for this PR, I'll just make a new issue for them and fix them after it's merged.

**Comment by sindresorhus** [comment]
@paulmolluzzo :+1: to all your suggestions, but should be a separate PR.

**Pull request closed without merging**
