### PR TITLE
Add missing space in `clean-conversation-headers` 

### LINKED ISSUE #3483: Missing space after username in PR conversation headers
Today I saw that since a few days there's a space missing after the username in the PR conversation header.

image

It is likely due to this:
https://github.com/sindresorhus/refined-github/blob/6bba1c5de1e8b609e010f252d72ff9c63af431a6/source/features/clean-conversation-headers.tsx#L46

which should be `' into '`

Github refined v20.8.16 on Chrome

### PR DESCRIPTION
**Pull request by fcornelius**
fixes #3483

### CODE REVIEW

**Comment by fregante** [comment]
Is the space necessary? Can you post a screenshot of the before and after?

**Comment by fregante** [comment]
Ah I saw your issue now. PRs should include “fixes #issue”. Please follow the PR template

**Comment by fcornelius** [comment]
Right, sorry. I thought mentioning it in the commit is enough but you're right, it says so in the template. Screenshot is in the issue

**Comment by fregante** [comment]
Thanks! Appreciated

**Pull request merged**
