### PR TITLE
Improve error handling for the Safari extension app

### PR DESCRIPTION
**Pull request by sindresorhus**
I also slightly improved the look of the wrapper app:

Screen Shot 2021-04-10 at 15 27 41

### CODE REVIEW

**Comment by fregante** [comment]
Does this fix or explain #4216? Now that the problem is gone from my computer I can't test it anymore

**Comment by sindresorhus** [comment]
@fregante It doesn't fix it. But if it happens, it shows the user an error dialog at least.

**Comment by fregante** [comment]
Was this included in 21.4.12? 😳 

Anyway, I'm not a Swift dev, so merge as you see fit

**Comment by sindresorhus** [comment]
Ugh, no it was not. I'll do another release in a few days then I guess.

**Pull request merged**
