### PR TITLE
Add support for namespaced branches to`fix-view-file-link-in-pr`

### PR DESCRIPTION
**Pull request by tejanium**
This PR will fix 404 when clicking "View file" on the PR if branch name is namespaced (example: `namespaced/branch`)

# Test
With the latest build plugin installed, go to this PR's [Files Changed tab](https://github.com/sindresorhus/refined-github/pull/2595/files) >  click on `...` > click "View file" (bonus: click it "View file" multiple time, by closing the dialog and opening it again over and over)

### CODE REVIEW

**Comment by fregante** [comment]
Can you provide a test link?

**Comment by tejanium** [comment]
Hmm..I did provide the test link on the PR's description

To check the bug
1. Goto https://github.com/sindresorhus/refined-github/pull/2595/files
2. Click on `...`
3. Click "View file"
4. 404

I'm not sure how to provide test link for the fixes

**Comment by fregante** [comment]
Ugh, sorry. Long day 😓

**Comment by fregante** [comment]
Partially tested. How does it look? Does it work for you?

**Comment by tejanium** [comment]
Nice improvement! And yes, it works fine for me! 👍

**Comment by fregante** [comment]
Thank you for the PR Teja! 🥕

**Pull request merged**
