### PR TITLE
Remove user avatar from new comment form on threads

### LINKED ISSUE #1066: Remove user avatar from new comment form on threads
While scanning a conversation, I inadvertently scan for my avatar as well to see if I've commented and on which threads I've participated in (related: #1065). However, I see my own avatar on each new comment form in each thread.

Suggestion: Remove your own avatar from the Reply form in PR review threads.

**Now**

image

**After**

image

Let me know your thoughts and I can submit a PR with an implementation!

---
> _Side note_
> I'm not sure how much your own avatar is useful on the new comment form at the bottom either, but the threads ones are more misleading as they could occur multiple times.
> image

### PR DESCRIPTION
**Pull request by notlmn**
Fixes #1066.

Wanted to leave this to @hkdobrev, but no one was picking it up.

### CODE REVIEW

**Comment by bfred-it** [comment]
Should we add this to the readme?

**Comment by sindresorhus** [comment]
Yes, it's a good way for us to keep track of features in case they disappear because of GitHub changes. Alternatively, we could have an internal feature list for things not deemed important enough for the readme?

**Comment by bfred-it** [comment]
> it's a good way for us to keep track of features in case they disappear

Is it though? I don't remember ever going through and checking if they're still there. Features that disappear either are noticed by someone or they just stay there.

The CSS is probably full of this since it's 1000 lines long.

---

I'm fine with moving some lesser changes to a separate list, or even a smaller "and more" `<details>` section in the readme itself.

**Comment by sindresorhus** [comment]
> or even a smaller "and more" <details> section in the readme itself.

👍 Sounds good.

**Comment by sindresorhus** [comment]
Gonna skip on the readme inclusion until we have a place to put tiny changes.

**Pull request merged**
