### PR TITLE
fix bug where switcher is messing with account menu

### PR DESCRIPTION
**Pull request by joshmanders**
This closes https://github.com/sindresorhus/refined-github/issues/13

### CODE REVIEW

**Comment by sindresorhus** [comment]
I'm still seeing the issue. Click your profile pic and quickly move you mouse down the menu and it will disappear.

**Comment by joshmanders** [comment]
Hmmm strange, it works for me. :/

**Comment by sindresorhus** [comment]
@hkdobrev @paulmolluzzo Does this fix it for you?

**Comment by hkdobrev** [comment]
I cannot reproduce with this change.

**Pull request merged**
