### PR TITLE
Meta: Add per-feature “unaffected” version in the hotfix manager

### PR DESCRIPTION
**Pull request by fregante**
Fixes https://github.com/sindresorhus/refined-github/issues/4324

To test this PR, the manifest version needs to be manually changed. I tested it and the function correctly returns the expected option settings.

### CODE REVIEW

**Comment by fregante** [comment]
To test this, the manifest version needs to be manually changed. I tested it and the function correctly returns the expected option settings.

**Comment by fregante** [comment]
Will wait for https://github.com/sindresorhus/refined-github/pull/4316#issuecomment-838423309

**Comment by yakov116** [comment]
I should have commented earlier.

Maybe we should be able to put in an issue number. Like we used to have and let the users know so we can get some help on the issue?

**Comment by fregante** [comment]
Yeah that would be nice, it can be shown as a notice in the options page:

```
 ------------------------------------------------------
| `dim-bots` has been temporarily disabled due to #123 |
| `bugs-tab` has been temporarily disabled due to #456 |
 ------------------------------------------------------
```

**Pull request merged**
