### PR TITLE
Add "Open all in tabs" button for notifications

### LINKED ISSUE #701: Add "open all in tabs" button for Github notifications
This is something I use all the time, and if it's useful for others, it might be worth incorporating into Refined Github.

I ended up [implementing it myself](https://github.com/gibfahn/gnt) (partly just to learn webextensions), so I'd be happy to try and incorporate it into this extension if this is something that might be wanted.

image

### PR DESCRIPTION
**Pull request by tanmayrajani**
- Fixes #701 
- Opens all notifications in background tabs next to current tab
- Asks for confirmation only when notifications are more than 10

### CODE REVIEW

**Comment by gibfahn** [comment]
>Asks for confirmation only when notifications are more than 10

Would really like an option to disable the confirmation if possible.

**Comment by bfred-it** [comment]
Pinging @sindresorhus for that

**Comment by bfred-it** [comment]
**Note:** if you want to test notifications and you're not already Sindre, just Watch the [Rust repo](https://github.com/rust-lang/rust/issues) and you'll get 3 notifications within 10 minutes 😅

**Comment by sindresorhus** [comment]
> Would really like an option to disable the confirmation if possible.

How about we allow pressing enter to confirm the confirmation?

**Comment by sindresorhus** [comment]
This looks good to me, but the feature needs to be mentioned in the readme.

**Comment by bfred-it** [comment]
> How about we allow pressing enter to confirm the confirmation?

Technically already possible—after 2 tabs to focus the button. Perhaps we can focus that automatically in every `rel=facebox` (including "Mark all as read"), but that can be submitted as a separate PR and feature.

**Comment by bfred-it** [comment]
@sindresorhus done!

screenshot for readme

**Comment by sindresorhus** [comment]
Thanks for working on this @tanmayrajani :)

**Comment by sindresorhus** [comment]
> We could automatically focus that in every rel=facebox (including "Mark all as read"), but that can be submitted as a separate PR and feature.

:arrow_up: @gibfahn Open an issue or PR if you want this ;)

**Comment by bfred-it** [comment]
I opened that as #730 already 😅

**Pull request merged**
