### PR TITLE
Add link to delete fork if the PR is merged

### LINKED ISSUE #48: [Idea] Add remove fork button to pull requests
Once a pull request has been merged I get the option to delete the branch from my fork. It would also be nice if I'd the possibility to delete the entire fork. Right now I have to go the the fork and then click on the settings tab where I find the delete button. What do you think? Is it even possible?

### PR DESCRIPTION
**Pull request by paulmolluzzo**
This fixes #48.

This adds a link to the settings page of the forked repo where you can delete that repo. There's no anchor that I can use on the page to automatically scroll. (There are hidden anchors, but it doesn't look like hidden anchors work.)

Open to style suggestions.

Screenshot:
delete fork

### CODE REVIEW

**Comment by paulmolluzzo** [comment]
It also passes for a different reason: That box is even visible for me now, and it's not merged.

**Comment by paulmolluzzo** [comment]
This is injecting the link in a hidden element, so is that acceptable? IDK honestly. I'm thinking they are using hidden/displayed elements for various scenarios, so as long as it's not visible in the wrong place it should be OK. There are more than 1 "been merged" cases, so if anyone can test on other PRs that'd be helpful.

**Comment by paulmolluzzo** [comment]
OK, I tested this on about a dozen repos that I do/don't own, that are/aren't forks, and that are/aren't merged. It works as expected in all of the ones I checked without errors in the console. :tada:

I added in the `length` test that @SpaceK33z suggested. Also, I added in a test to be sure it's a forked repo.

If anyone finds issues please LMK.

**Comment by vinkla** [comment]
Great work! Will this still trigger the confirmation box?

**Comment by paulmolluzzo** [comment]
@vinkla this doesn't even trigger a delete, technically. I just brings you to the settings page. See here: https://github.com/sindresorhus/refined-github/issues/48#issuecomment-191172493

From there the flow is unchanged. So think of this like a shortcut to settings.

**Comment by vinkla** [comment]
Okay, great. Keep up the good work!

**Comment by sindresorhus** [comment]
@paulmolluzzo Do you have a place I can test it out?

**Comment by paulmolluzzo** [comment]
@sindresorhus any link I send probably won't do you any good b/c you need to be in my account. These are all the cases to test (I think):

* Owned/forked/random repo
* Open/closed/merged - and merged might have "merged and dirty"
* Branch still exists or was already deleted.

Here are a few screenshots

**closed deleted:**
closed-deleted

**closed dirty fork:**
closed-dirty-fork

**closed fork deleted:**
closed-fork-deleted

**closed fork not deleted:**
closed-fork-not-deleted

**closed owned deleted:**
closed-owned-deleted

**closed owned-not-deleted:**
closed-owned-not-deleted

**open:**
open

**open fork:**
open-fork

**Comment by sindresorhus** [comment]
Cool. That's good enough for me. Could you add it to the readme too, and link to `https://cloud.githubusercontent.com/assets/737065/13498068/648f3434-e126-11e5-8b40-f77cddb91089.png`?

**Comment by paulmolluzzo** [comment]
@sindresorhus added.

**Comment by sindresorhus** [comment]
Awesome. Looks good :)

**Pull request closed without merging**
