### PR TITLE
Add cookie-based cache with expiration

### LINKED ISSUE #624: Caches don't have limits/expirations
We're using the storage to cache the release count and the users' full name. These caches don't expire and they just pile up. There should be a mechanism to either regularly purge the cache or to make them expire.

A thought was to use good ol' cookies in the `background.js` (yes they work in there) since the expiration is handled natively and new items push out the old items once the limit is reached — just like you'd expect from a cache.

However cookies are limited to 4KB (instead of 5MB), which maybe fits around 100 user names and 40 release counts.

Ideas?

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes #624 

Cookies are limited to about 170 entries, which makes it a pretty short cache though

### CODE REVIEW

**Comment by sindresorhus** [comment]
I don't really like this. Feels like abuse of cookies. And cookies are sent with every request, so this will actually slow down requests, right? And the hard limit on cookies is pretty low. I think it would be better to just use a LRU implementation with support for TTL for our caching. What are the benefits of cookies? I only see downsides. Maybe native TTL, but TTL is not that to do ourselves.

**Comment by bfred-it** [comment]
> And cookies are sent with every request

No because they're stored on `background.js`'s cookie manager, so they're exclusive to RGH and never sent anywhere

> What are the benefits of cookies?

13 lines of code to have TTL https://github.com/sindresorhus/refined-github/blob/16eb017f29af3e8358a07f2bf4f091f38ca8f3a3/source/libs/cache.js#L41-L55

> TTL is not that to do ourselves

?

**Comment by sindresorhus** [comment]
> TTL is not that to do ourselves

Was trying to say that TTL is not that hard to do ourselves. 

Roughly: We just need an entry that contains an object with all the keys and their TTL timestamp as value, and then for every `get`/`set` we check the last time the DB was cleaned and if it's time to clean, get the all the keys in the TTL entry, and delete the ones that are expired. We don't need any accurate TTL, so we can implement it the simple way.

**Comment by bfred-it** [comment]
The issue has been open for a year and that solution never materialized however 😃

The “full names” cache Ian probably pretty long for many users by now

**Comment by sindresorhus** [comment]
Alright. I guess this is better than what we have now and I don't have time either to do something better than cookies. I still think we should do it eventually though.

**Pull request merged**
