### PR TITLE
Suggestion: Increase font size of code to make it more readable

### PR DESCRIPTION
**Pull request by arshad**
Would you consider a PR to increase the default font size of code? Thanks.

make core more readable

### CODE REVIEW

**Comment by sindresorhus** [comment]
I'm not interested in this myself, but I can see it being useful for some. How about we make a `extras.css` file in root that is not included in the extension, but available so people can easily copy-paste if they need it?

**Comment by whitneyit** [comment]
Could this be achieved by options and then opting in for the features you want?

**Comment by sindresorhus** [comment]
@whitneyit It could, but I'm not very interested in adding options. It's a slippery slope. Soon then, I'll have requests for most thing being options.

**Comment by joshmanders** [comment]
An opt-in options page would be splendid. I love this extension but there are a few things I'd rather do without.

**Comment by sindresorhus** [comment]
> I love this extension but there are a few things I'd rather do without.

Proving my point. Everyone wants something differently, which would end up in everything being options.

Out of curiosity, what would you rather do without and why?

**Comment by joshmanders** [comment]
I understand your opinionated requirements, so I'm not complaining or anything. :) 

Just some stuff like `Hides other users starring/forking your repos from the newsfeed` I like to see.

**Pull request closed without merging**
