### PR TITLE
Only move the organization switcher if it exists

### PR DESCRIPTION
**Pull request by bfred-it**
> The only other annoying thing is `padding-top` to `dashboard-sidebar`. Not every user has an organization switcher which leaves a large gap above sidebar.
> https://github.com/sindresorhus/refined-github/pull/599#issuecomment-313983025

### CODE REVIEW

**Comment by sindresorhus** [comment]
This PR causes a noticeable jump when the switcher is moved. The switched move is not noticeable on master. It introduces a slight bug in the style. Notice the icon.

Before:

screen shot 2017-07-10 at 14 53 34

After:

screen shot 2017-07-10 at 14 53 40

**Comment by bfred-it** [comment]
Is that still an issue for you?

**Comment by sindresorhus** [comment]
> It introduces a slight bug in the style. Notice the icon.

⬆️ This is still an issue. The chat icon on the first item is not correctly horizontally aligned.

**Comment by bfred-it** [comment]
GitHub treats the first item differently and our style was overriding part of it.

screen shot 2017-07-18 at 18 23 17

**Pull request merged**
