### PR TITLE
Apply `linkify-code` to unfolded diffs

### LINKED ISSUE #2091: Apply auto-linking after unfolding diffs
This is a follow-up from https://github.com/sindresorhus/refined-github/issues/1499. Of the repro cases I provided there

>  URLs appear to not be linked even if the URL _as a whole_ was added ([first example](https://github.com/sindresorhus/refined-github/pull/546/files#diff-36280fbf56b6409696e3d46d6b30118fR51)), or even if they're just in comments alongside changes ([second example](https://github.com/sindresorhus/refined-github/pull/636/files#diff-36280fbf56b6409696e3d46d6b30118fR51)—note that I unfolded the top of the diff to get there, not sure if that matters).

> URLs do appear to be linked if they're in non-PR code blocks ([third example](https://github.com/sindresorhus/refined-github/blob/3f5fc489e417d4f4a14da5ea423775e9ca9246fd/source/features/copy-markdown.js#L45)).

The first is fixed with https://github.com/sindresorhus/refined-github/pull/2066, and the third remains fixed, but the second is still broken.

I can repro both if I visit the unfolded part directly ([link](https://github.com/sindresorhus/refined-github/pull/636/files#diff-36280fbf56b6409696e3d46d6b30118fR51)) and if I go to the folded diff ([link](https://github.com/sindresorhus/refined-github/pull/636/files)), then unfold the top (one unfold should be sufficient to see the link, at line 51).

Not sure if this is a regression or no.

### PR DESCRIPTION
**Pull request by kidonng**
Part of #3084 (if I should mention it)
Resolves #2091

Test: https://github.com/sindresorhus/refined-github/pull/636/files (unfold the diff above)

This PR simply warp the old code with `selector-observer` and add an additional selector (`.blob-expanded`) to make it work on unfolded diffs.

~~Merge `format-conversation-titles` in this PR as well (on request by https://github.com/sindresorhus/refined-github/pull/3397#issuecomment-664580685)~~

### CODE REVIEW

**Comment by fregante** [comment]
https://github.com/sindresorhus/refined-github/pull/3410#issuecomment-665106479

**Comment by fregante** [comment]
I wasn't able to undo the deleted file, the console reported this 404:

```
https://github.com/sindresorhus/refined-github/new/linkify-code?filename=source/features/format-conversation-titles.tsx
```

Screen Shot 2020-07-30 at 12 48 58

**Comment by fregante** [comment]
I think this only needs to remove mentions of the issue title since that widget is incompatible with `selector-observer`

The rest seems correct

**Comment by fregante** [comment]
Also related: https://github.com/sindresorhus/refined-github/issues/2264 https://github.com/sindresorhus/refined-github/issues/3279

**Comment by kidonng** [comment]
> Also related: #2264 #3279

Roger that, but it would be in other PR

**Comment by fregante** [comment]
Can you look into this as well? https://github.com/sindresorhus/refined-github/issues/3226 What's going on? Is the selector wrong?

**Comment by fregante** [comment]
Congratulations for solving the oldest open bug 🍰

**Comment by fregante** [comment]
Can you try restoring the laziness from https://github.com/sindresorhus/refined-github/pull/3091/files? I think my code only lacked the `:not(.rgh-*)` part of selectors. Otherwise this feature might be heavy on long files like https://github.com/yakov116/refined-github/blob/upstream/package-lock.json

**Comment by kidonng** [comment]
> Is the selector wrong

Yeah, need to narrow it down

**Pull request merged**
