### PR TITLE
Add link to user's top repositories

### PR DESCRIPTION
**Pull request by momothereal**
Adds a toggle to replace `Pinned repositories` with `Top repositories` (most starred).

Also adds the GraphQL implementation from #1399

Example:

image

--

image

### CODE REVIEW

**Comment by bfred-it** [comment]
This seems a bit too much trouble for a feature that can be replaced by a link to: https://github.com/search?o=desc&q=user%3Asindresorhus&s=stars&type=Repositories

Not as pretty, but also not limited to 6 repos and with 200 lines of code.

For future reference, the graph API should be merged into the the same file, as originally suggested [here](https://github.com/sindresorhus/refined-github/pull/1399#discussion_r202865862)

**Comment by sindresorhus** [comment]
While it does look nice, I agree with @bfred-it, it's not worth the maintenance burden when a link achieves the same thing and also lets the user see more than 6 repos.

**Comment by bfred-it** [comment]
Can you turn this feature into a link with that URL[](https://github.com/sindresorhus/refined-github/pull/1495/commits/f09bef5480e28a3a80fd79bd2a328058700fcceb)?

It should be something not far from: 

```
select('pinned repos title').after(' / ', <a href="..url..">Top repositories</a>)
```

**Comment by bfred-it** [comment]
Can this be picked up or can it be closed? :)

**Comment by yakov116** [comment]
@bfred-it you blow my mind! Wow, I can't get over how you took a about 100 lines of code and put it into about 10!

**Comment by bfred-it** [comment]
haha it's not exactly the same feature though :D

**Pull request merged**
