### PR TITLE
Update squash-and-merge title when PR title changes

### LINKED ISSUE #1555: Squash+Merge title = PR title doesn't handle updated PR titles
Feature #276, `Force "squash and merge" title to be the pull request title`, doesn't take into account that a user might update the PR title before using the squash+merge button. They have to reload the page first to get the new PR title into the input field, which is unexpected.

### PR DESCRIPTION
**Pull request by notlmn**
~~Fixes~~ #1555

### CODE REVIEW

**Comment by bfred-it** [comment]
I don't find this feature particularly useful, it doesn't solve the bug it was meant to solve and it only affects the situation when the user clicks `Squash and merge` first and then changes the title.

Feel free to merge it if you still find it useful

**Comment by sindresorhus** [comment]
@bfred-it You're right. I thought this was fixing the issue of "updating the title, then clicking "squash and merge", and the squash title not being updated", but it seems that works on master too, so must have been fixed at some point.

**Comment by bfred-it** [comment]
Closing in favor of https://github.com/sindresorhus/refined-github/issues/1790

**Comment by notlmn** [comment]
Thanks @bfred-it!

**Comment by bfred-it** [comment]
🐰 thanks for the contribution as always, Laxman!

**Pull request merged**
