### PR TITLE
Disable referrer for linkified URLs

### LINKED ISSUE #1376: Referer in code blocks linkified URLs
Is it possible to stop linkifing URLs in code blocks when they contain only links?
Or maybe somehow strip referer header?

I know I can disable `linkify-urls-in-code` completly, but this affect only me.

```
https://www.whatismyreferer.com/
http://example.com/
http://example.net/
```

### PR DESCRIPTION
**Pull request by gwarser**
Fixes #1376 

Tested in Firefox 60, 62, Chromium 66

### CODE REVIEW

**Comment by notlmn** [comment]
The `Referrer` header can also be disabled using `rel="noreferrer"`, which can also contain `noopener` for disabling same-origin and cross-origin `window.opener` property.

**Comment by gwarser** [comment]
Do you think there is a chance that someone will add `target` attribute to these links?

**Comment by bfred-it** [comment]
I thought `referrerpolicy: 'no-referrer'` covered `noopener` but it doesn't, so yeah let's use `rel="noreferrer noopener"` instead of `referrerpolicy`

**Comment by gwarser** [comment]
Overwritten.

**Pull request merged**
