### PR TITLE
Load script injector's ping receiver (for GH Enterprise)

### LINKED ISSUE #479: Trending nav item is repeating in header
image

Steps to reproduce:
1. Go to https://github.com/sindresorhus/refined-github It's added twice
1. Click on a sub-repo navigation item - e.g. Issues tab.

This has been introduced relatively recently on `master`.

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes #479

@busches please have a look

### CODE REVIEW

**Comment by derimagia** [comment]
I had this issue as well and this fixed the issue for me on GHE

**Comment by SimenB** [comment]
Still getting this on the latest release

image

Not sure how to reproduce it though. Repro from #479 doesn't work...

**Comment by bfred-it** [comment]
Any errors in the console? Try enabling Developer mode and debug the `background page`

**Comment by SimenB** [comment]
This is on public GitHub btw, not GHE.

>Try enabling Developer mode and debug the `background page`

What do you mean? I've never debugged/worked on a chrome extension, so not sure how 🙂

**Comment by SimenB** [comment]
I did get an error in the console now, and extra "Trending", not sure if relevant, though.

image

**Comment by SimenB** [comment]
I don't think so. Putting a breakpoint in 
```js
async function addTrendingMenuItem() {
	const secondListItem = await index$2('.header-nav.float-left .header-nav-item:nth-child(2)');

	jquery_slim_min$1(secondListItem).after(`
		<li class="header-nav-item">
			<a href="/trending" class="header-nav-link" data-hotkey="g t">Trending</a>
		</li>
	`);
}
```
and it's called sometimes on navigation. No errors

**Comment by SimenB** [comment]
Last post: It happens when it looks like the script is reloaded. The script fades away, then comes back, and the function is called again.

Maybe just check if trending is already there?

**Comment by bfred-it** [comment]
That error is for a different extension. RGH is `hlepfoohegkhhmjieoechaddaejaokhf`

The duplicated Trending is just the tip of the iceberg, the issue is that `content.js` is being executed multiple times. A quick fix would be to detect this and stop its execution asap, but it doesn't solve the underlying issue described in this PR (the injector injects it multiple times)

To debug it:

1. Disable the extension from the store
2. [Load the extension locally](https://github.com/sindresorhus/refined-github#chrome)
3. [Inspect the background page](https://stackoverflow.com/a/10258029/288906)

**Comment by SimenB** [comment]
Have you looked into something like this: https://stackoverflow.com/a/26951766/1850276

Should probably open a separate issue...

**Comment by bfred-it** [comment]
The current setup supports GHE, that doesn't

**Comment by bfred-it** [comment]
You can continue the discussion in the actual issue: https://github.com/sindresorhus/refined-github/issues/479

**Comment by bfred-it** [comment]
There's a new version on AMO. Please uninstall the current one and reinstall the new one.

**Pull request merged**
