### PR TITLE
Move jQuery out of the bundle

### LINKED ISSUE #439: Deploy to AMO
- [x] Initial submit to AMO
  @sindresorhus do you want to submit it yourself? Otherwise I'll do it. Either way you're going to have to create an account on https://addons.mozilla.org/en-US/developers/
- [x] Set up auto-deployment using [web-ext](https://github.com/mozilla/web-ext)
  https://github.com/sindresorhus/refined-github/pull/403#issuecomment-302838065
- [ ] Fix review warnings:
  <details><summary markdown="true">Unsafe assignment to innerHTML <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/linkify-urls-in-code.js#L26"><code>linkify-urls-in-code.js 26:5</code></a></summary><blockquote>Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.</blockquote></details>
  <details><summary markdown="true">Unsafe assignment to innerHTML <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/linkify-urls-in-code.js#L36"><code>linkify-urls-in-code.js 36:5</code></a></summary><blockquote>Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.</blockquote></details>
  <details><summary markdown="true">"storage.local" can cause issues when loaded temporarily <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/content.js#L60"><code>content.js 60:3</code></a></summary><blockquote>Warning: This API can cause issues when loaded temporarily using about:debugging in Firefox unless you specify applications > gecko > id in the manifest. Please see: https://mzl.la/2hizK4a for more.</blockquote></details>
  <details><summary markdown="true">"storage.local" can cause issues when loaded temporarily <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/content.js#L62"><code>content.js 62:3</code></a></summary><blockquote>Warning: This API can cause issues when loaded temporarily using about:debugging in Firefox unless you specify applications > gecko > id in the manifest. Please see: https://mzl.la/2hizK4a for more.</blockquote></details>
  <details><summary markdown="true">Unsafe assignment to innerHTML <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/content.js#L284"><code>content.js 284:3</code></a></summary><blockquote>Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.</blockquote></details>
  <details><summary markdown="true">"storage.local" can cause issues when loaded temporarily <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/show-names.js#L5"><code>show-names.js 5:3</code></a></summary><blockquote>Warning: This API can cause issues when loaded temporarily using about:debugging in Firefox unless you specify applications > gecko > id in the manifest. Please see: https://mzl.la/2hizK4a for more.</blockquote></details>
  <details><summary markdown="true">"storage.local" can cause issues when loaded temporarily <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/show-names.js#L9"><code>show-names.js 9:3</code></a></summary><blockquote>Warning: This API can cause issues when loaded temporarily using about:debugging in Firefox unless you specify applications > gecko > id in the manifest. Please see: https://mzl.la/2hizK4a for more.</blockquote></details>

### LINKED ISSUE #519: Deploy is failing
https://travis-ci.org/sindresorhus/refined-github/builds/245849567

```
> refined-github@ release:amo /home/travis/build/sindresorhus/refined-github
> cd extension && webext submit
/home/travis/build/sindresorhus/refined-github/node_modules/.bin/web-ext sign
Missing required arguments: api-key, api-secret
```

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes #519

The difference between our custom build and the normal jQuery is 18KB, about 15% of our bundle.

### CODE REVIEW

**Comment by hkdobrev** [comment]
I think this is to fix #519, not #439 which is already closed (even though it's related).

**Comment by bfred-it** [comment]
My bad. I always select the wrong issue when I type `#` and then select one from the list that appears.

**Comment by sindresorhus** [comment]
I think we should use the official slim build of jQuery. 18 KB is not a lot, but it's still a waste.

**Comment by bfred-it** [comment]
Oh I didn't even know that there was an official slim version.

**Pull request merged**
