### PR TITLE
Add `sort-issues-by-update-time` to `filter-comments-by-you`

### LINKED ISSUE #2052: `filter-comments-by-you` does not add sort:updated-desc
Should be simple to add

### PR DESCRIPTION
**Pull request by yakov116**
Fixes #2052

### CODE REVIEW

**Comment by bfred-it** [comment]
This is from another feature and shouldn’t be in here, ideally

It should work automatically if the sorting feature runs after this feature

**Comment by yakov116** [comment]
This
https://github.com/sindresorhus/refined-github/blob/dfee7e87714c07941119809f6674fd742524c52b/source/content.ts#L61

Should be moved here?
https://github.com/sindresorhus/refined-github/blob/dfee7e87714c07941119809f6674fd742524c52b/source/content.ts#L41-L42

**Comment by bfred-it** [comment]
Probably, yes, before that

**Comment by yakov116** [comment]
@bfred-it done

**Pull request merged**
