### PR TITLE
Fix centering and spacing of `reaction-avatars` count

### PR DESCRIPTION
**Pull request by SNDST00M**
Some work to improve the rendering of reaction counts in the `reaction-avatars` feature.

## Test URLs

https://github.com/microsoft/vscode/issues/124901

## Screenshot

Before:

After:

### CODE REVIEW

**Comment by SNDST00M** [comment]
@fregante threw out a bunch of lines with only a 1px regression
I did copy code from flash.scss in #4763 but that was a mistake in retrospect

**Comment by fregante** [comment]
When sending PRs it's best to avoid reordering CSS properties or else I have to check all those lines unnecessarily. Most lines don't need to be changed here

**Comment by SNDST00M** [comment]
Sorry, in the habit of sorting alphabetically - almost automatic for me :)

**Comment by fregante** [comment]
The current code is still wrong. Please don't open more PRs on this issue.

### The avatars are no longer overlapped

Screen Shot 10 <-- before
Screen Shot 9 <-- after

### The `-1px` margin just messes with the image

Screen Shot 11

**Comment by SNDST00M** [comment]
While I understand the 4-review limit applies here, it turns out this was a simple matter of:

```css
:root .social-reaction-summary-item .social-button-emoji,
:root .social-reaction-summary-item span:nth-child(2) {
	align-self: center;
	box-sizing: content-box;
}

:root .rgh-reactions span:nth-child(2):not(:last-child) {
	min-width: 16px;
}
```

**Pull request closed without merging**
