### PR TITLE
Link to restored branches

### PR DESCRIPTION
**Pull request by bfred-it**
> If a branch is deleted and subsequently restored, it would not link to it
> @hkdobrev in #422 

* Fixes the above
* Cleans up the function
* Fixes the below (title not showing on `user deleted the xxx branch` event)

screen shot 2017-07-08 at 01 03 38
screen shot 2017-07-08 at 01 03 27

### CODE REVIEW

**Comment by bfred-it** [comment]
Test pages:

- deleted branch: https://github.com/sindresorhus/refined-github/pull/576
- restored branch: https://github.com/bfred-it/sandbox/pull/11

**Comment by bfred-it** [comment]
But actually a line might be better than a title: 

strikethrough


Thoughts?

**Comment by sindresorhus** [comment]
> Better than a title to mark deleted branches:

Strikethrough

**Comment by sindresorhus** [comment]
It shows the strikethrough on the wrong item.

It should show it on:

screen shot 2017-07-10 at 14 49 14

But it shows on:

screen shot 2017-07-10 at 14 49 22

**Comment by bfred-it** [comment]
It strikes through all the mentions of the deleted branch, but there was an extra `inline-block` span that nulled the `text-decoration`. Now it works:

screen shot 2017-07-11 at 18 30 15

**Comment by sindresorhus** [comment]
Discovered a small issue. This PR no longer linkifies `master` in https://github.com/sindresorhus/refined-github/pull/422. It should still linkify `master` even though `branch-link-deleted-fix` is deleted.

**Comment by bfred-it** [comment]
This should fix it 🙏

**Comment by sindresorhus** [comment]
That did it 👌

**Pull request merged**
