### PR TITLE
Fix console error caused by `embed-gist-via-iframe`

### LINKED ISSUE #2530: Console Errors
- [x]  https://github.com/sponsors/sindresorhus

```js
❌ forked-to
content.js:2856 TypeError: Cannot read property 'addEventListener' of null
    at forked_to_init (content.js:7820)
    at features_run (content.js:2851)
    at content.js:2898
    at content.js:2813
    at onAjaxedPagesRaw (content.js:2808)
```
```js
❌ more-dropdown
content.js:2856 TypeError: Cannot read property 'append' of null
    at appendBefore (content.js:3537)
    at createDropdown (content.js:3565)
    at more_dropdown_init (content.js:3578)
    at async features_run (content.js:2851)
```
```js
❌ edit-files-faster
content.js:2856 Error: Unable to fetch.
Ensure that your token has access to this repo.
{
	"message": "Not Found",
	"documentation_url": "https://developer.github.com/v3/repos/#get"
}
    at getError (content.js:3063)
    at async chrome-extension:/hlepfoohegkhhmjieoechaddaejaokhf/content.js:3025
    at async fetchFromApi (content.js:3078)
    at async get_default_branch (content.js:3086)
    at async edit_files_faster_init (content.js:6973)
    at async features_run (content.js:2851)
```
- [x]  Click on the sponsor button in a repo or the watch dropdown
```js
content.js:4502 Uncaught TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
    at HTMLDocument.<anonymous> (content.js:4502)
    at HTMLDocument.listenerFn (content.js:369)
```

- [ ] https://gist.github.com/yakov116
```js
❌ embed-gist-via-iframe
content.js:2856 TypeError: Cannot read property 'cloneNode' of null
    at embed_gist_via_iframe_init (content.js:8398)
    at features_run (content.js:2851)
    at Object.add (content.js:2896)
```

### PR DESCRIPTION
**Pull request by kidonng**
Fixes #2530

# Test

https://gist.github.com/yakov116 (no more error)
https://gist.github.com/yakov116/2d81580f7907839f9065e670f0aba64c (ensure it still works)
[Test for GHE]

### CODE REVIEW

**Comment by kidonng** [comment]
I'm just about the append that note😅 I'm thinking about GHE because I saw `location.pathname.split('/', 2)[1] === 'gist'` in `isGist()`.

**Comment by fregante** [comment]
Yeah but you can detect that too. Dom-based tests are to be avoided.

**Comment by fregante** [comment]
Something like

```js
/^\/(gist\/)?[^/]+\/[0-9a-f]{40}$/
```

**Comment by fregante** [comment]
@kidonng can you finish this PR?

**Comment by kidonng** [comment]
Sorry I had been busy last week 😅 working now

**Comment by fregante** [comment]
Uhm why not just in `page-detect.ts` with tests?

**Comment by kidonng** [comment]
> Uhm why not just in `page-detect.ts` with tests?

I thought it was specific to the feature 🤔 and since it is within the range of `isGist()`, once it goes into `page-detect.ts` the tests will fail.

**Comment by fregante** [comment]
> I thought it was specific to this feature

Any feature can appear on a single gist page. https://github.com/sindresorhus/refined-github/pull/2539/commits/9a5f12764720d6584a91e91afcc19c7d6ee5f41f was setup with a single TODO to include tests for those URLs.

The tests "fail" because pages that are `isSingleGist` are also `isGist`; to fix it, all tests URLs you place in `isSingleGist` (1 URL) should also be part of `isGist`.

**Comment by kidonng** [comment]
> The tests "fail" because pages that are `isSingleGist` are also `isGist`; to fix it, all tests URLs you place in `isSingleGist` (1 URL) should also be part of `isGist`.

I misunderstood the test result of a previous commit https://github.com/sindresorhus/refined-github/pull/2539/commits/a96257fb18b3de52103938b9f9964bf162a036f4 😅
Sorry for the long take on this PR 😌.

**Pull request merged**
