### PR TITLE
Meta: Add more information about the token in the options page

### PR DESCRIPTION
**Pull request by fregante**
Related: #3752

### CODE REVIEW

**Comment by yakov116** [comment]
Hey I started writing a code 😠! 
I like your layout much better than mine ❤️.

**Comment by fregante** [comment]
You're too fast! 😅

**Comment by yakov116** [comment]
Can I push to this PR or do you want to have 2 PR's.
1. Add the description
2. Add the validation



> You're too fast! 😅 I sent this PR 7 minutes after my comment describing it.

I started writing it this morning (the validation part)

**Comment by fregante** [comment]
If you postpone it a day or 2 we can merge this first. The style isn't _super,_ I wonder if the ✅/❌ would make it look more sensible.

**Pull request merged**
