### PR TITLE
Add a copy button next to the branch name. Closes #77.

### LINKED ISSUE #77: Easy copy paste of branches and filenames in PR's
When reviewing a PR from a colleague, I often want to check it out on my local machine. I often do this by copying the branch name from the PR into a shell. More often than not, I don't quite get it right first time and for some reason find it difficult to copy the branch name.

The same applies if I want to look at a specific file (doubly more annoying because of truncated file names in Pull Requests)

The copy button next to sha's in the commits file is handy, so why not add it next to branches too?

E.g.:

screenshot 2016-03-11 at 23 16 40

and

screenshot 2016-03-11 at 23 20 38

### PR DESCRIPTION
**Pull request by edhgoose**
See #77 for details.

I'm not sure about the padding on the copy button at the moment, it makes the target a bit small. But let me know what you think.

add_a_copy_button_next_to_the_branch_name__closes__77__by_edhgoose_ _pull_request__78_ _sindresorhus_refined-github

### CODE REVIEW

**Comment by paulmolluzzo** [comment]
I'm still not sold on this idea, but I'll comment on the implementation:

As @hkdobrev [said here](https://github.com/sindresorhus/refined-github/issues/77#issuecomment-195918508), this doesn't work for a fork of a repo. Case in point, in this PRI have the options of copying the word "master" or "master", so that's not valuable IMO.

Second, the original `linkifyBranchRefs()` had a side benefit of also linkifying those branch names in other places, like when a PR is closed/merged. See #66 for an example. This clipboard icon is added there too, and it feels even less necessary there.

The spacing is weird, I'd make it tighter to the target text.

All that said, I'm still not sure that there's much value to this. @sindresorhus what do you think?

**Comment by hkdobrev** [comment]
I still think #77 should be closed as `wontfix`. I'll add my comments there.

**Comment by sindresorhus** [comment]
Sorry @edhgoose, gonna close as it seems none of us want or need something like this.

Happy to link to it in https://github.com/sindresorhus/refined-github#community-tweaks though :)

**Comment by montogeek** [comment]
I need this, Why? To copy paste the branch to the terminal easily

**Comment by bfred-it** [comment]
Perhaps @edhgoose is willing to turn it into a separate extension.

**Comment by edhgoose** [comment]
I think GitHub changed something which made copying easier... and so while the button would be nice I actually cope quite well without it. I'd probably not have time/desire to build an extension, but feel free to go nuts on the code that I wrote in this PR and do it yourself. There's a couple bugs with it I think, but I'm afraid I can't remember what

**Comment by hkdobrev** [comment]
We could probably leave the branch name not linked and add a link next to it.

**Comment by erikhuizinga** [comment]
Maybe something like the `<>` icon next to comments: https://github.com/sindresorhus/refined-github/blob/7c75af58f77c705bd03d1ec9b5e15b9042884f15/source/features/add-time-machine-links-to-comments.js

But then next to the branch name.

**Comment by bfred-it** [comment]
I think the suggested solution was to use hub.github.com

1. Copy the PR’s URL
2. Open your terminal
3. Run something like `hub checkout $(pbpaste)`

That command is always the same in my history and it automatically uses my clipboard. 

If you really need this button, I’m 80% sure that there’s a userscript or extension already. Not all features _have_ to be in Refined GitHub

**Comment by salmanulfarzy** [comment]
You could also do this with [`hub pr`](https://hub.github.com/hub-pr.1.html) command. List PRs with `hub pr list` and then checkout them with `hub pr checkout <PR>`

**Comment by Empty2k12** [comment]
Screenshot 2019-04-01 at 18 35 23

Github added this natively. Who could have known people actually want this? /s

**Comment by bfred-it** [comment]
People can continue using their “faster horses” while the rest of us can use tools that don’t require moving at all :)

**Pull request closed without merging**
