### PR TITLE
Change the header back to normal

### PR DESCRIPTION
**Pull request by sbussard**
Removes the dark theme from the top banner

### CODE REVIEW

**Comment by bfred-it** [comment]
I don't mind the black banner. I'm sure we all feel weird when things suddenly look different, but we'll likely get used to it.

**Comment by sindresorhus** [comment]
Let's give it some weeks and we can reevaluate.

**Comment by hkdobrev** [comment]
I find bugs with the banner, not the black banner, but some misalignments in certain cases and some pages. I guess I should report to GitHub, but if I could revert without those bugs for now would be great for me!

**Comment by sbussard** [comment]
This PR won't work anymore, Github changed their code.

**Pull request closed without merging**
