### PR TITLE
Update dependencies; make Firefox 78 the minimum version

### PR DESCRIPTION
**Pull request by yakov116**
Follows https://github.com/sindresorhus/refined-github/pull/2410#issuecomment-643135144

I updated all the dependencies too. Let me know if I should revert or if you want to do this entirely on your own.

### CODE REVIEW

**Comment by fregante** [comment]
Finally!

**Comment by fregante** [comment]
Is it possible to change the target ES version in tsconfig? `??` doesn't need to be transpiled anymore, but `acorn` support in `webpack` made it impossible to change the `target`

**Comment by yakov116** [comment]
I can try later today. I dont **think** its possible without updating to webpack v5 (where acorn was updated).

**Comment by yakov116** [comment]
> Is it possible to change the target ES version in tsconfig?

No

**Pull request merged**
