### PR TITLE
Add `link-to-prior-blame-line` feature

### LINKED ISSUE #2175: "View blame prior to this change" link should include the current line
1. https://github.com/sindresorhus/refined-github/blame/master/readme.md#L200
2. Click on 

	View blame prior to this change

3. The page loads, you're no longer on line 200 but at the start of the document

"View blame prior to this change" link should include the current line (where you click)

Something like

```ts
for (const link of select.all('.reblame-link')) {
	link.hash = '#' + link.closest('.blame-hunk')!.querySelector('.js-line-number[id]')!.id
}
```

### PR DESCRIPTION
**Pull request by arnaudvalle**
Closes #2175

# Test

- Go to a blame page (i.e. https://github.com/sindresorhus/refined-github/blame/master/readme.md)
- Click on:
image
- You're on the line number you clicked on, not at the beginning of the document

### CODE REVIEW

**Comment by yakov116** [comment]
@arnaudvalle  Thanks for your PR!
Can you try not to include the issue number in a commit it creates unnecessary noise.
image

**Comment by arnaudvalle** [comment]
> Can you try not to include the issue number in a commit it creates unnecessary noise.
Ah sure, my bad. Want me to edit the commit message then or do you mean that for future commits?

**Comment by yakov116** [comment]
@arnaudvalle nah just for the future.

**Comment by fregante** [comment]
A couple things:
- change description to: `Preserves the current line on “View blame prior to this change” links.`
- add it the readme, under “GitHub shortcomings”

**Comment by sindresorhus** [comment]
Tested. Works well. Thanks for contributing :)

**Pull request merged**
