### PR TITLE
Re-write test helper as an AVA macro

### PR DESCRIPTION
**Pull request by DrewML**
This is currently failing `xo` linting right now, due to this usage of macros + the `ava/test-title` ESLint rule.

[I know that I can assign a function to `urlMatcherMacro.title` and the lint rule won't nag](https://github.com/avajs/eslint-plugin-ava/commit/c2e158c3c351ee81a32b57fd5eccda7b105b67d1), but, for this scenario, that's not really needed.

@sindresorhus @jamestalmage Any suggestions? One thing I considered doing was removing the need to pass in the `detectFn`. Instead, we would use the first string passed in for the dynamic test title + as a key for looking up the `detectFn` on the `pageDetect` object. The snag there was that the first string arg passed to a `test` call gets passed to the `title` fn, but not to the macro itself. I could make the title/method name the _last_ arg to the macro.

### CODE REVIEW

**Comment by jamestalmage** [comment]
See https://github.com/avajs/eslint-plugin-ava/pull/112

Merged to master, but not published.

**Comment by DrewML** [comment]
Nice. I saw that you had done that work and merged it in, just jumped to the assumption that it was already released. Thanks!

**Comment by jamestalmage** [comment]
Should be published now

**Comment by DrewML** [comment]
@jamestalmage Thanks! That fixed it

**Comment by sindresorhus** [comment]
Looks good :)

**Pull request merged**
