### PR TITLE
Add support for requiring json

### LINKED ISSUE #519: Deploy is failing
https://travis-ci.org/sindresorhus/refined-github/builds/245849567

```
> refined-github@ release:amo /home/travis/build/sindresorhus/refined-github
> cd extension && webext submit
/home/travis/build/sindresorhus/refined-github/node_modules/.bin/web-ext sign
Missing required arguments: api-key, api-secret
```

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes #519

### CODE REVIEW

**Comment by sindresorhus** [comment]
It's so dumb that end-users needs to this manually. It should just be handled by Rollup by default. Rollup should support the Node.js require algorithm out of the box... Anyways.

**Comment by bfred-it** [comment]
Yeah rollup literally only takes care of es modules and tree shaking. That's it. To replace browserify it literally needs 5+ plugins (node-resolve, commonjs, json, globals, builtins, maybe more) and they often have issues as you start requiring modules that have less common configurations.

I'll try webpack@3 at some point, once [`ModuleConcatenationPlugin`](https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b) gets more docs.

**Comment by sindresorhus** [comment]
> I'll try webpack@3 at some point, once [`ModuleConcatenationPlugin`](https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b) gets more docs.

Even Webpack forces you do to the JSON thing manually...

**Comment by bfred-it** [comment]
> **Note: Since webpack v2, importing of JSON files will work by default. You might still want to use this if you use a custom file extension.**
> https://github.com/webpack-contrib/json-loader

**Comment by sindresorhus** [comment]
🤗

**Pull request merged**
