### PR TITLE
Enforce usage of browser.* APIs

### LINKED ISSUE #495: Use Promised `browser.*` APIs
Firefox copied Chrome's extensions API, renamed `chrome.*` to `browser.*` and made them Promised.

Do you think it's worthwhile to use a `browser.*` polyfill like [mozilla/webextension-polyfill](https://github.com/mozilla/webextension-polyfill) so we can leave callback APIs (and the awful `chrome.runtime.lastError`) in the dust?

I'm guessing that the polyfill also works with unsupported APIs like `chrome.permissions.*`

### PR DESCRIPTION
**Pull request by bfred-it**
Why: consistency + Promises `>` Callbacks. We make little use of browser APIs, anyway.

Closes #495 

Tested the changed parts:

- Options (add GHE domain)
- Repo releases (a. visit home first; or b. visit non-home first)
- Show full names (open any discussion)

### CODE REVIEW

**Comment by bfred-it** [comment]
For future reference `browser-polyfill.min.js` is pulled from:

https://unpkg.com/webextension-polyfill@latest/dist/browser-polyfill.min.js

**Comment by sindresorhus** [comment]
Can we use Webpack to at least copy it from the `node_modules` folder to the dist? Not a big fan of having to manually keep it up to date.

**Comment by bfred-it** [comment]
A bit complicated... 8b765e8

<details><summary> That becomes this unminified monstrosity: </summary>



```js
!function(modules) {
 function __webpack_require__(moduleId) {
  if (installedModules[moduleId]) return installedModules[moduleId].exports;
  var module = installedModules[moduleId] = {
   i: moduleId,
   l: !1,
   exports: {}
  };
  return modules[moduleId].call(module.exports, module, module.exports, __webpack_require__), 
  module.l = !0, module.exports;
 }
 var installedModules = {};
 __webpack_require__.m = modules, __webpack_require__.c = installedModules, __webpack_require__.d = function(exports, name, getter) {
  __webpack_require__.o(exports, name) || Object.defineProperty(exports, name, {
   configurable: !1,
   enumerable: !0,
   get: getter
  });
 }, __webpack_require__.n = function(module) {
  var getter = module && module.__esModule ? function() {
   return module.default;
  } : function() {
   return module;
  };
  return __webpack_require__.d(getter, "a", getter), getter;
 }, __webpack_require__.o = function(object, property) {
  return Object.prototype.hasOwnProperty.call(object, property);
 }, __webpack_require__.p = "", __webpack_require__(__webpack_require__.s = 32);
}({
 32: function(module, exports, __webpack_require__) {
  window.browser = __webpack_require__(33);
 },
 33: function(module, exports, __webpack_require__) {
  var __WEBPACK_AMD_DEFINE_FACTORY__, __WEBPACK_AMD_DEFINE_ARRAY__, __WEBPACK_AMD_DEFINE_RESULT__;
  !function(a, b) {
   __WEBPACK_AMD_DEFINE_ARRAY__ = [ module ], void 0 !== (__WEBPACK_AMD_DEFINE_RESULT__ = "function" == typeof (__WEBPACK_AMD_DEFINE_FACTORY__ = b) ? __WEBPACK_AMD_DEFINE_FACTORY__.apply(exports, __WEBPACK_AMD_DEFINE_ARRAY__) : __WEBPACK_AMD_DEFINE_FACTORY__) && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__);
  }(0, function(a) {
   "use strict";
   "undefined" == typeof browser ? a.exports = (() => {
    const c = {
     alarms: {
      clear: {
       minArgs: 0,
       maxArgs: 1
      },
      clearAll: {
       minArgs: 0,
       maxArgs: 0
      },
      get: {
       minArgs: 0,
       maxArgs: 1
      },
      getAll: {
       minArgs: 0,
       maxArgs: 0
      }
     },
     bookmarks: {
      create: {
       minArgs: 1,
       maxArgs: 1
      },
      export: {
       minArgs: 0,
       maxArgs: 0
      },
      get: {
       minArgs: 1,
       maxArgs: 1
      },
      getChildren: {
       minArgs: 1,
       maxArgs: 1
      },
      getRecent: {
       minArgs: 1,
       maxArgs: 1
      },
      getTree: {
       minArgs: 0,
       maxArgs: 0
      },
      getSubTree: {
       minArgs: 1,
       maxArgs: 1
      },
      import: {
       minArgs: 0,
       maxArgs: 0
      },
      move: {
       minArgs: 2,
       maxArgs: 2
      },
      remove: {
       minArgs: 1,
       maxArgs: 1
      },
      removeTree: {
       minArgs: 1,
       maxArgs: 1
      },
      search: {
       minArgs: 1,
       maxArgs: 1
      },
      update: {
       minArgs: 2,
       maxArgs: 2
      }
     },
     browserAction: {
      getBadgeBackgroundColor: {
       minArgs: 1,
       maxArgs: 1
      },
      getBadgeText: {
       minArgs: 1,
       maxArgs: 1
      },
      getPopup: {
       minArgs: 1,
       maxArgs: 1
      },
      getTitle: {
       minArgs: 1,
       maxArgs: 1
      },
      setIcon: {
       minArgs: 1,
       maxArgs: 1
      }
     },
     commands: {
      getAll: {
       minArgs: 0,
       maxArgs: 0
      }
     },
     contextMenus: {
      update: {
       minArgs: 2,
       maxArgs: 2
      },
      remove: {
       minArgs: 1,
       maxArgs: 1
      },
      removeAll: {
       minArgs: 0,
       maxArgs: 0
      }
     },
     cookies: {
      get: {
       minArgs: 1,
       maxArgs: 1
      },
      getAll: {
       minArgs: 1,
       maxArgs: 1
      },
      getAllCookieStores: {
       minArgs: 0,
       maxArgs: 0
      },
      remove: {
       minArgs: 1,
       maxArgs: 1
      },
      set: {
       minArgs: 1,
       maxArgs: 1
      }
     },
     devtools: {
      inspectedWindow: {
       eval: {
        minArgs: 1,
        maxArgs: 2
       }
      },
      panels: {
       create: {
        minArgs: 3,
        maxArgs: 3,
        singleCallbackArg: !0
       }
      }
     },
     downloads: {
      download: {
       minArgs: 1,
       maxArgs: 1
      },
      cancel: {
       minArgs: 1,
       maxArgs: 1
      },
      erase: {
       minArgs: 1,
       maxArgs: 1
      },
      getFileIcon: {
       minArgs: 1,
       maxArgs: 2
      },
      open: {
       minArgs: 1,
       maxArgs: 1
      },
      pause: {
       minArgs: 1,
       maxArgs: 1
      },
      removeFile: {
       minArgs: 1,
       maxArgs: 1
      },
      resume: {
       minArgs: 1,
       maxArgs: 1
      },
      search: {
       minArgs: 1,
       maxArgs: 1
      },
      show: {
       minArgs: 1,
       maxArgs: 1
      }
     },
     extension: {
      isAllowedFileSchemeAccess: {
       minArgs: 0,
       maxArgs: 0
      },
      isAllowedIncognitoAccess: {
       minArgs: 0,
       maxArgs: 0
      }
     },
     history: {
      addUrl: {
       minArgs: 1,
       maxArgs: 1
      },
      getVisits: {
       minArgs: 1,
       maxArgs: 1
      },
      deleteAll: {
       minArgs: 0,
       maxArgs: 0
      },
      deleteRange: {
       minArgs: 1,
       maxArgs: 1
      },
      deleteUrl: {
       minArgs: 1,
       maxArgs: 1
      },
      search: {
       minArgs: 1,
       maxArgs: 1
      }
     },
     i18n: {
      detectLanguage: {
       minArgs: 1,
       maxArgs: 1
      },
      getAcceptLanguages: {
       minArgs: 0,
       maxArgs: 0
      }
     },
     idle: {
      queryState: {
       minArgs: 1,
       maxArgs: 1
      }
     },
     management: {
      get: {
       minArgs: 1,
       maxArgs: 1
      },
      getAll: {
       minArgs: 0,
       maxArgs: 0
      },
      getSelf: {
       minArgs: 0,
       maxArgs: 0
      },
      uninstallSelf: {
       minArgs: 0,
       maxArgs: 1
      }
     },
     notifications: {
      clear: {
       minArgs: 1,
       maxArgs: 1
      },
      create: {
       minArgs: 1,
       maxArgs: 2
      },
      getAll: {
       minArgs: 0,
       maxArgs: 0
      },
      getPermissionLevel: {
       minArgs: 0,
       maxArgs: 0
      },
      update: {
       minArgs: 2,
       maxArgs: 2
      }
     },
     pageAction: {
      getPopup: {
       minArgs: 1,
       maxArgs: 1
      },
      getTitle: {
       minArgs: 1,
       maxArgs: 1
      },
      hide: {
       minArgs: 0,
       maxArgs: 0
      },
      setIcon: {
       minArgs: 1,
       maxArgs: 1
      },
      show: {
       minArgs: 0,
       maxArgs: 0
      }
     },
     runtime: {
      getBackgroundPage: {
       minArgs: 0,
       maxArgs: 0
      },
      getBrowserInfo: {
       minArgs: 0,
       maxArgs: 0
      },
      getPlatformInfo: {
       minArgs: 0,
       maxArgs: 0
      },
      openOptionsPage: {
       minArgs: 0,
       maxArgs: 0
      },
      requestUpdateCheck: {
       minArgs: 0,
       maxArgs: 0
      },
      sendMessage: {
       minArgs: 1,
       maxArgs: 3
      },
      sendNativeMessage: {
       minArgs: 2,
       maxArgs: 2
      },
      setUninstallURL: {
       minArgs: 1,
       maxArgs: 1
      }
     },
     storage: {
      local: {
       clear: {
        minArgs: 0,
        maxArgs: 0
       },
       get: {
        minArgs: 0,
        maxArgs: 1
       },
       getBytesInUse: {
        minArgs: 0,
        maxArgs: 1
       },
       remove: {
        minArgs: 1,
        maxArgs: 1
       },
       set: {
        minArgs: 1,
        maxArgs: 1
       }
      },
      managed: {
       get: {
        minArgs: 0,
        maxArgs: 1
       },
       getBytesInUse: {
        minArgs: 0,
        maxArgs: 1
       }
      },
      sync: {
       clear: {
        minArgs: 0,
        maxArgs: 0
       },
       get: {
        minArgs: 0,
        maxArgs: 1
       },
       getBytesInUse: {
        minArgs: 0,
        maxArgs: 1
       },
       remove: {
        minArgs: 1,
        maxArgs: 1
       },
       set: {
        minArgs: 1,
        maxArgs: 1
       }
      }
     },
     tabs: {
      create: {
       minArgs: 1,
       maxArgs: 1
      },
      captureVisibleTab: {
       minArgs: 0,
       maxArgs: 2
      },
      detectLanguage: {
       minArgs: 0,
       maxArgs: 1
      },
      duplicate: {
       minArgs: 1,
       maxArgs: 1
      },
      executeScript: {
       minArgs: 1,
       maxArgs: 2
      },
      get: {
       minArgs: 1,
       maxArgs: 1
      },
      getCurrent: {
       minArgs: 0,
       maxArgs: 0
      },
      getZoom: {
       minArgs: 0,
       maxArgs: 1
      },
      getZoomSettings: {
       minArgs: 0,
       maxArgs: 1
      },
      highlight: {
       minArgs: 1,
       maxArgs: 1
      },
      insertCSS: {
       minArgs: 1,
       maxArgs: 2
      },
      move: {
       minArgs: 2,
       maxArgs: 2
      },
      reload: {
       minArgs: 0,
       maxArgs: 2
      },
      remove: {
       minArgs: 1,
       maxArgs: 1
      },
      query: {
       minArgs: 1,
       maxArgs: 1
      },
      removeCSS: {
       minArgs: 1,
       maxArgs: 2
      },
      sendMessage: {
       minArgs: 2,
       maxArgs: 3
      },
      setZoom: {
       minArgs: 1,
       maxArgs: 2
      },
      setZoomSettings: {
       minArgs: 1,
       maxArgs: 2
      },
      update: {
       minArgs: 1,
       maxArgs: 2
      }
     },
     webNavigation: {
      getAllFrames: {
       minArgs: 1,
       maxArgs: 1
      },
      getFrame: {
       minArgs: 1,
       maxArgs: 1
      }
     },
     webRequest: {
      handlerBehaviorChanged: {
       minArgs: 0,
       maxArgs: 0
      }
     },
     windows: {
      create: {
       minArgs: 0,
       maxArgs: 1
      },
      get: {
       minArgs: 1,
       maxArgs: 2
      },
      getAll: {
       minArgs: 0,
       maxArgs: 1
      },
      getCurrent: {
       minArgs: 0,
       maxArgs: 1
      },
      getLastFocused: {
       minArgs: 0,
       maxArgs: 1
      },
      remove: {
       minArgs: 1,
       maxArgs: 1
      },
      update: {
       minArgs: 2,
       maxArgs: 2
      }
     }
    };
    if (0 === Object.keys(c).length) throw new Error("api-metadata.json has not been included in browser-polyfill");
    class d extends WeakMap {
     constructor(o, p) {
      super(p), this.createItem = o;
     }
     get(o) {
      return this.has(o) || this.set(o, this.createItem(o)), super.get(o);
     }
    }
    const h = (o, p, q) => new Proxy(p, {
     apply: (r, s, t) => q.call(s, o, ...t)
    });
    let i = Function.call.bind(Object.prototype.hasOwnProperty);
    const j = (o, p = {}, q = {}) => {
     let r = Object.create(null), s = {
      has: (t, u) => u in t || u in r,
      get(t, u) {
       if (u in r) return r[u];
       if (u in t) {
        let w = t[u];
        if ("function" == typeof w) if ("function" == typeof p[u]) w = h(t, t[u], p[u]); else if (i(q, u)) {
         let x = ((o, p) => {
          const q = r => 1 == r ? "argument" : "arguments";
          return function(s, ...t) {
           if (t.length < p.minArgs) throw new Error(`Expected at least ${p.minArgs} ${q(p.minArgs)} for ${o}(), got ${t.length}`);
           if (t.length > p.maxArgs) throw new Error(`Expected at most ${p.maxArgs} ${q(p.maxArgs)} for ${o}(), got ${t.length}`);
           return new Promise((u, v) => {
            s[o](...t, ((o, p) => (...q) => {
             chrome.runtime.lastError ? o.reject(chrome.runtime.lastError) : p.singleCallbackArg || 1 === q.length ? o.resolve(q[0]) : o.resolve(q);
            })({
             resolve: u,
             reject: v
            }, p));
           });
          };
         })(u, q[u]);
         w = h(t, t[u], x);
        } else w = w.bind(t); else {
         if ("object" != typeof w || null === w || !i(p, u) && !i(q, u)) return Object.defineProperty(r, u, {
          configurable: !0,
          enumerable: !0,
          get: () => t[u],
          set(x) {
           t[u] = x;
          }
         }), w;
         w = j(w, p[u], q[u]);
        }
        return r[u] = w, w;
       }
      },
      set: (t, u, v) => (u in r ? r[u] = v : t[u] = v, !0),
      defineProperty: (t, u, v) => Reflect.defineProperty(r, u, v),
      deleteProperty: (t, u) => Reflect.deleteProperty(r, u)
     };
     return new Proxy(o, s);
    }, m = {
     runtime: {
      onMessage: (o => ({
       addListener(p, q, ...r) {
        p.addListener(o.get(q), ...r);
       },
       hasListener: (p, q) => p.hasListener(o.get(q)),
       removeListener(p, q) {
        p.removeListener(o.get(q));
       }
      }))(new d(o => "function" == typeof o ? function(q, r, s) {
       let t = o(q, r);
       return (o => o && "object" == typeof o && "function" == typeof o.then)(t) ? (t.then(s, u => {
        console.error(u), s(u);
       }), !0) : void (void 0 !== t && s(t));
      } : o))
     }
    }, n = Object.assign({}, chrome);
    return j(n, m, c);
   })() : a.exports = browser;
  });
 }
});
```

<details>

**Comment by hkdobrev** [comment]
I've recently done that in an extension with gulp + browserify (I'm not Webpack-proficient and I've started with https://github.com/yeoman/generator-chrome-extension). For me using it from `node_modules` and packaging it with the build system is the better option. Just keep in mind that before Firefox 57 is stable, the polyfill is replacing things on Firefox as well where it shouldn't and there are some unexpected differences in promises and cross-frame communication (which I don't think we have in RG).

**Comment by bfred-it** [comment]
Anyway, this is good to be merged. The output code shouldn't be terribly important, we'll see if Mozilla reviewers complain 😅

**Comment by bfred-it** [comment]
Best of both worlds! Files are automatically moved from npm without any compilation, and now jQuery too!

**Comment by sindresorhus** [comment]
> Best of both worlds! Files are automatically moved from npm without any compilation, and now jQuery too!

Yay!

**Pull request merged**
