### PR TITLE
Clean up icons

### PR DESCRIPTION
**Pull request by shroudedcode**
While working on a new feature that required me to add a new icon I noticed that the `source/libs/icons.js` file was pretty messy and decided to clean it up.

To do that, I ...

* removed the `version` attribute from all `<svg>` tags (user agents ignore it)
* removed one occurrence of the `xmlns` attribute (user agents ignore it as well)
* removed the `viewBox` attribute from `<svg>` tags when it was `0 0 [width] [height]` (= redundant)
* removed `aria-label` tag from all `<svg>` tags (icons can be used in multiple contexts)
* added the `aria-hidden` attribute to all `<svg>` tags
* removed the `role` attribute from all `<svg>` tags (useless with `aria-hidden`)
* ordered the attributes (for consistency)

These changes make the file more readable and reduce the amount of code RGH inserts into the DOM.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Did you try running the icons through https://jakearchibald.github.io/svgomg/ or SVGo to see if we could minify them?

**Comment by bfred-it** [comment]
I think they're already minified by GitHub

**Comment by shroudedcode** [comment]
@sindresorhus It suggested making the `<path>` tags self-closing, so I did that.

@bfred-it I only removed `viewBox` from `<svg>` tags where `viewBox` and `width` and `height` were matching. Is `viewBox` still necessary in these cases?

**Comment by bfred-it** [comment]
> Is viewBox still necessary in these cases?

Can you check all the icons across the extension to see if they've changed? 😄 

However this might be a moot point if we follow @jgierer12's good suggestion, we can probably just `require` the SVG files directly if webpack is configured.

**Comment by bfred-it** [comment]
When in doubt, blame @hkdobrev

**Pull request merged**
