### PR TITLE
Add: `jsdelivr-cdn`

### PR DESCRIPTION
**Pull request by Rawnly**
# Features
- Adds a new button near the `Copy` button that lets you copy a cdn url from jsdelivr, the pattern for the url is: `https://cdn.jsdelivr.net/gh/<user>/<repo>/<path-to-file>`

# Test
[This one](https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.min.css) `https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.min.css`

Should generate the [following](https://cdn.jsdelivr.net/gh/twbs/bootstrap/dist/css/bootstrap.min.css)
`https://cdn.jsdelivr.net/gh/twbs/bootstrap/dist/css/bootstrap.min.css`

### CODE REVIEW

**Comment by bfred-it** [comment]
- This only applies to JavaScript files
- jsdelivr is only one of the possible CDNs people might be interested in and we can’t add them all

so it doesn’t belong to RGH. It’s best you keep this as a bookmarklet or make another extension/userscript

**Comment by Rawnly** [comment]
> * jsdelivr is only one of the possible CDNs people might be interested in and we can’t add them all

I understand this and I agree with you. However the URL works with every type of file, there's no restriction to js files. ✌️

**Comment by bfred-it** [comment]
Yeah but nobody is going to use jsdeliver for rust files. What I mean is that it only applies to web developers. This button will appear on every file but it’d only make sense on some. Plus I suppose most use a bundler and not CDNs like that, so this further reduces its utility.

**Comment by bfred-it** [comment]
This is the closest feature we’d be interested in, as far as CDNs go: https://github.com/sindresorhus/refined-github/issues/1096

**Pull request closed without merging**
