### PR TITLE
Avoid jump when adding Trending link

### PR DESCRIPTION
**Pull request by bfred-it**
Issue before this PR: the Trending link is added on domready, which happens after the first paint.

trending link is added too late

This change can probably be applied to more jumpy parts at some point, but this is the most visible on every page.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Yes! :)

**Comment by SimenB** [comment]
I'm now getting multiple trending links, is that because of this change?

image

**Comment by bfred-it** [comment]
Refer to https://github.com/sindresorhus/refined-github/issues/479

**Comment by SimenB** [comment]
Ah, thanks!

**Pull request merged**
