### PR TITLE
Publish a git tag for every Refined GitHub release

### PR DESCRIPTION
**Pull request by bfred-it**
This will:

- create a versioned tag on cronjob **and** tags called `hotfix`
- publish all other tags using the tag name as version

~~**WARNING:** As of a5aaa54 it already works **from this branch**, so any changes will be published to git releases and the old travis job will pick that up and publish it to the stores. This instant publishing is temporary and for testing only.~~

~~@sindresorhus I'd like to avoid giving my GH API token to travis, so I'd rather set this up with SSH, if possible: 6345bcf~~ _Done_

~~Perhaps this can be done in https://github.com/sindresorhus/refined-github/settings/keys~~ _Done_

Reference:

- https://github.com/alrra/travis-scripts/blob/master/docs/github-deploy-keys.md
- https://help.github.com/en/articles/which-remote-url-should-i-use#cloning-with-ssh-urls

### CODE REVIEW

**Comment by yakov116** [comment]
Curious why?

**Comment by yakov116** [comment]
Curious why?

**Comment by bfred-it** [comment]
To see exactly what each version contains. Without it we have to open Travis, find the “cron” build, open it, look for the version in the log, and get the commit from the header. 

Plus I might also be able to attach the built extension to each tag/release, so people who might need it don’t have to download and build the source.

**Comment by bfred-it** [comment]
Great! This seems to work correctly for `hotfix` tags. Now we wait for `cron`

**Comment by bfred-it** [comment]
#966 would help here too

**Comment by bfred-it** [comment]
`cron` also worked (and my regular commit was correctly skipped)



However I noticed that the same commit can be tagged twice. I opened a new issue

**Pull request merged**
