### PR TITLE
Shorten version number

### LINKED ISSUE #595: Versioning, deployment improvements
I'll preface by saying that the current setup (deploy every push to master) works well for me and I **prefer it** over manually creating tags/releases.

I do however have two wishes:

- [x] limit to one release per day
- [ ] shorter version numbers (`17.7.8` instead of `17.7.8.1317`)

Travis recently added a daily cronjob feature which we could use to implement daily deployment, but [it runs regardless of changes](https://github.com/travis-ci/beta-features/issues/1#issuecomment-285280591).

These changes are possible but we need two pieces:

- something that stops Travis as soon as it sees no new commits **since the last build** (which might not be exactly 24 hours before)
- something that stores the previous version in Travis' cache ([seems possible](https://docs.travis-ci.com/user/caching/#Arbitrary-directories)) as `y.m.d` and automatically bumps it to `y.m.d.1` if multiple builds happen in the same day

Ideas? Have you seen such packages? Know how to do this?

### PR DESCRIPTION
**Pull request by bfred-it**
Closes #595 
```
From 17.8.20.834
to   17.8.20
```
Travis has been behaving well and deployments happening in the middle of UTC day, so same-day deployments are far from possible — even if that does happen we only lose a day anyway.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Wouldn't this prevent us from doing manual urgent bug fix releases? (If it already had done a manual release that day)

**Comment by bfred-it** [comment]
It would, the [code in #595](https://github.com/sindresorhus/refined-github/issues/595#issuecomment-314630122) would solve that issue. But then I thought... when would it ever be necessary to ship _Refined GitHub_ **now** instead of **within 24 hours**?

**Comment by sindresorhus** [comment]
If some changes on GitHub caused Refined GitHub to totally break, we would want to ship a fix right away. Could easily happen as we're playing on someone else's lawn.

**Comment by bfred-it** [comment]
Understandable, but #675 totally broke the extension and it's been gone unfixed for 20 hours. 😜

**Comment by sindresorhus** [comment]
@bfred-it I did not know about that: https://github.com/sindresorhus/refined-github/issues/675#issuecomment-324538136

Can you message me on Twitter if you notice before me next time? And I'll fix it right away.

**Comment by bfred-it** [comment]
Ok, this now addresses your concern and closes #595 :)

**Comment by sindresorhus** [comment]
Shouldn't `17.8.29.1451` follow semver and be `17.8.29+1451`? (Build metadata)

**Comment by bfred-it** [comment]
Chrome doesn't follow semver, it only allows numbers: https://developer.chrome.com/extensions/manifest/version

**Comment by bfred-it** [comment]
It looks like I hit a roadblock though. I have to store the cache somewhere else because travis only retrieves at `before_build` and stores `after_build`, which happens before the deployment script saves the version.

Do you know of a free REST service that allows to store small data?

**Comment by sindresorhus** [comment]
Is that overkill just to get a slightly shorter version number that probably no one will even see?

**Comment by sindresorhus** [comment]
Is that overkill just to get a slightly shorter version number that probably no one will even see?

**Comment by bfred-it** [comment]
Except everyone sees it twice on the homepage 😛

**Comment by sindresorhus** [comment]
So let us just drop those badges. I don't see the point of them, to be honest. Alternatively, we could move them into a `maintaining.md` file just for us. Example: https://github.com/avajs/ava/blob/master/maintaining.md What do you think?

**Comment by jdreesen** [comment]
I find them useful to check whats the last release (I think it appears on the chrome store almost instantly?) and if has already been approved on AMO. Thus, when something doesn't work (but AMO lags behind once again) I can check if the bug has already been fixed (and just didn't reach me yet) before I'm creating an issue.

**Comment by sindresorhus** [comment]
You could also check this in a `maintaining.md` file. It's not essential for most users.

**Comment by jdreesen** [comment]
Sure, I could, no problem. Just please don't remove them entirely :)

**Comment by bfred-it** [comment]
I'd rather have them there, it's always one-click away to check if both versions have been published and they don't bother me that much 😁

**Comment by sindresorhus** [comment]
workflow

**Pull request closed without merging**
