### PR TITLE
Hide `link-to-file-in-file-history` where not needed

### LINKED ISSUE #2024: `link-to-file-in-file-history` redirects to 404
The icon should not show up when on the branch's commits page for example: https://github.com/sindresorhus/refined-github/commits/master, as it just redirects to a 404 page.

@HardikModha

### PR DESCRIPTION
**Pull request by dotconnor**
https://github.com/sindresorhus/refined-github/commits/master No longer has button
https://github.com/sindresorhus/refined-github/commits/master/readme.md keeps the button

Fixes #2024

### CODE REVIEW

**Comment by bfred-it** [comment]
The condition above was meant to do this, so you can replace it

**Comment by dotconnor** [comment]
@bfred-it I'm sorry can you explain?

**Comment by Abraham6754** [comment]
Ok

**Comment by bfred-it** [comment]
I mean the condition on line 17 was supposed to do what you’re trying to do now (disable the feature on branch Commits page), but it doesn’t work, so you can drop it.

**Comment by bfred-it** [comment]
Thanks @dotconnor 🧧

**Pull request merged**
