### PR TITLE
fix diff header file name

### LINKED ISSUE #264: Filename in diff header not showing after recent GitHub update
```
diffheader.js:29 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined`
```

It looks like the `.diff-toolbar-filename + .right` selector that we're using to calculate one of the offsets doesn't resolve to an element in the DOM anymore.

Will try to take a look tomorrow evening when I have some free time if no one addresses it sooner.

### PR DESCRIPTION
**Pull request by jacobbearden**
closes #264

### CODE REVIEW

**Comment by hkdobrev** [comment]
@jacobbearden 👍  It works for me! However the trimming of the filename when it's too long is not happening. Any ideas?

**Comment by jacobbearden** [comment]
@hkdobrev Could you link me a diff where this is the case?

**Comment by hkdobrev** [comment]
@jacobbearden I've initially tested this in a private repo, but I was just able to find a public example. Scroll to the last file here: https://github.com/composer/composer/pull/5559/files The file path is too long, it's not trimmed and it puts the diff options and review drop down on a new line and breaks the layout.

I think we haven't revisited this since GitHub added the new review tools and changed the position of the diff options buttons. It's possible that we should adjust how we detect the maximum pixels available.

If you think we should create a new issue for that I'll be happy to merge and try to resolve the trimming in a new issue.

**Comment by jacobbearden** [comment]
@hkdobrev Should be fixed now :+1:

**Comment by jacobbearden** [comment]
Strange, those test errors don't come up when I run `npm test` on my machine.

image

**Comment by hkdobrev** [comment]
@jacobbearden Thanks! I've just tried it locally and all the tests pass for me as well. So I went back to the latest Travis CI build on `master` which was green and restarted and it failed now https://travis-ci.org/sindresorhus/refined-github/builds/171051717 So it seems it's something about Travis CI or something it installs. @sindresorhus Do you have any ideas?

**Comment by sindresorhus** [comment]
Thank you @jacobbearden :)

**Comment by sindresorhus** [comment]
I fixed the XO lint issue in master.

**Comment by jacobbearden** [comment]
My pleasure :smile:

**Pull request merged**
