### PR TITLE
Darken the background shade when you react

### PR DESCRIPTION
**Pull request by busches**
Alternate solution to issue #239 as proposed by @jacobbearden 

I'm not one for colors and like what @jacobbearden picked.

### CODE REVIEW

**Comment by sindresorhus** [comment]
The color doesn't work. It's too close to the gray border, which makes it look blurry. I honestly don't see the problem of #239. I think the existing color is more than clear enough, so I'm -0 on this.

**Comment by paulmolluzzo** [comment]
Yeah, I'm not super keen on this color. I'd personally want something brighter. How about `#c9f1ff` or to match the color when you comment we can do `#f1f8ff`

**Comment by busches** [comment]
Updated to use `#c9f1ff`.

**Comment by jgierer12** [comment]
I'm with @sindresorhus, I don't see a problem with the current color. I don't like the bright blue at all, I think it's way too attention-grabbing.

**Comment by busches** [comment]
I'm not super passionate about this, so closing since no one really agrees that we need the change or the color it should change to.

**Pull request closed without merging**
