### PR TITLE
Add `pr-parent-commits` feature

### LINKED ISSUE #2331: Show parent commits from the pull request view of a commit
When a commit is seen in the context of a pull request, its parents are not shown:
- single parent:
`https://github.com/sindresorhus/refined-github/pull/1939/commits/8dbef0104b19aee380e0bd17492c1402bd818ab5`
- two parents:
`https://github.com/chinese-poetry/chinese-poetry/pull/123/commits/5aeb8445648373432ff049f0aab5761f360c7555`

:warning: Edit, put these links between backticks to avoid Github rewriting them.

When the same commit is seen outside its pull request, its parents are shown: 
Screenshot from 2019-08-14 17-40-20
- single parent: https://github.com/sindresorhus/refined-github/commit/8dbef0104b19aee380e0bd17492c1402bd818ab5
- two parents: https://github.com/chinese-poetry/chinese-poetry/commit/5aeb8445648373432ff049f0aab5761f360c7555

If this info is available, it could be useful to add it to the pull request view, too.

### PR DESCRIPTION
**Pull request by yakov116**
1. LINKED ISSUES:
   Closes #2331

2. TEST URLS:
   [`6cec95f` (#3623)](https://github.com/sindresorhus/refined-github/pull/3623/commits/6cec95ff0a992eae1692f00df84b770aec4cab82)

3. SCREENSHOT:
image

@fregante feel free to close if its not accepted

### CODE REVIEW

**Comment by fregante** [comment]
I knew this day would come 😃 
I still think that it’s only a page away, but given that it’s very specifically shown only on PRCommit I think it’d be ok. I’m just not a fan of how long it is

**Comment by yakov116** [comment]
> I knew this day would come 😃

Yeah I was linting my branches 🤣 

> I’m just not a fan of how long it is

The feature size?

> I still think that it’s only a page away,

I also agree but I wrote the code already...

No need to merge it we can close it and its issue.

**Comment by fregante** [comment]
Paging Khun @sindresorhus

**Comment by yakov116** [comment]
Thought it over I am 👎 on this. Close the issue and the PR?

**Comment by GregJunkaTR** [comment]
Lack of such basic features is the main reason why I am sticking with Bitbucket for now :-)

**Comment by amiramix** [comment]
Lack of such basic features is the main reason why I am sticking with Bitbucket for now :-)

**Pull request closed without merging**
