### PR TITLE
Restore `parse-backticts` on `isPulse`

### PR DESCRIPTION
**Pull request by yakov116**
Restored `isDashboard` "help wanted" event titles

And resorted the list

### CODE REVIEW

**Comment by kidonng** [comment]
Reference: https://github.com/sindresorhus/refined-github/pull/3290#discussion_r456923720

**Comment by fregante** [comment]
> And resorted the list

Resorted how? Doesn't seem necessary, it's a long messy list regardless

**Comment by yakov116** [comment]
I  grouped the pages in some kind of order

**Comment by fregante** [comment]
🤷‍♂️

**Pull request merged**
