### PR TITLE
Rename add-readme-buttons to hide-readme-buttons

### LINKED ISSUE #1459: Rename the `add-readme-buttons` feature to `hide-readme-header`
Since GitHub now adds the edit button natively: https://blog.github.com/changelog/2018-07-24-button-to-edit-a-repositorys-readme-from-the-repository-root/

We can simplify the implementation and only hide the header.

// @notlmn

### PR DESCRIPTION
**Pull request by notlmn**
Closes #1459

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by sindresorhus** [comment]
I think we should reduce the opacity until you hover, like before. We can keep it gray like now instead of blue like it used to be.


Before this PR:
screen shot 2018-08-03 at 15 03 15

After:

screen shot 2018-08-03 at 15 03 19

**Comment by notlmn** [comment]
The readme button is faded by default and on hover changes color and full opacity.

**Comment by sindresorhus** [comment]
Looks good :)

**Pull request merged**
