### PR TITLE
Add link to latest release in readme

### LINKED ISSUE #288: Link to the readme of the latest version in the main readme
Often the readme you land on when you go to a repo is in `master` and might contain unreleased features. Would be useful to have a quick link to the readme of the latest version.

### PR DESCRIPTION
**Pull request by jgierer12**
Fixes #288.

Only works if using semver since the tags are sorted alphabetically 😕 - perhaps it would be better to make an AJAX call to the API?

Screenshot: Readme buttons

### CODE REVIEW

**Comment by jgierer12** [comment]
Taking this repo as an example, when a new feature gets added to the README but hasn't made it into a release yet, people reading the README might wonder why that feature "doesn't work". With this button they can view the README at the state of the latest release.
Maybe we should make it more obvious (not hidden behind an icon), so they immediately see that the README has been updated since the latest release. We'd certainly need an API call for that to work though.

**Comment by sindresorhus** [comment]
I think this makes sense. Most projects use master as the development branch and new features might be in the readme before they're out in a release.

**Comment by paulmolluzzo** [comment]
I see the point then, thanks for more info. I don't have a strong opinion about this one.

I'm not sure how to resolve the issue @jgeirer12 pointed out when a project doesn't use semver.

**Comment by hkdobrev** [comment]
Big 👍 on this feature!

On the order of tags - I don't think GitHub is sorting them alphabetically. GitHub is sorting them either based on date or based on semver. If it was sorting them alphabetically, then 1.10 would be before 1.16.

However if a project supports two major branches and have 1.13 created after 2.0.1. Then we'd take the 1.13 release if GitHub is sorting them by creation date. The selection from tags selector works only if GitHub is doing some semver ordering (which they may do).

Otherwise we may create a request to the releases page where GitHub marks which the latest release (if the project is using GitHub releases and not just tags) and also pre-releases are not considered as latest which we won't exclude otherwise.

So as much as I'd like to have this feature, it's not as straightforward as I'd like unless we have some support from GitHub.

**Comment by sindresorhus** [comment]
GitHub has no sense of semver, it sorts tags by date.

**Comment by hkdobrev** [comment]
I've labelled as "under discussion" since not really sure if we've decided on implementation which works for us.

So for now without API calls we can do one of those:

- a. Use the latest tag by date and add some short note to the link saying it's the latest by date. This would work for the majority of the repos as most people are not supporting multiple major/minor branches.
- b. Add some semver parsing library so we can use the last semver tag. It's more complex, but semver would make sense I think for most users of the extension and would fix some problems with a.

Could you please vote on these with emoji?

a. 🎉 Launch sooner
b. ❤️ Launch with semver support

**Comment by sindresorhus** [comment]
If we're going to do this, we should do it properly. Many projects backport bug fixes to older versions, like Electron: https://github.com/electron/electron/tags (Notice the v1.3.15). I've made a module to make this easier: https://github.com/sindresorhus/latest-semver

Here's a browserified version we can bundle directly: https://gist.github.com/sindresorhus/ae3a8d9275bae19c9f3cfa22c77b8251 Just use it as a global `latestSemver()`.

**Comment by jgierer12** [comment]
> I've made a module to make this easier: https://github.com/sindresorhus/latest-semver
Here's a browserified version we can bundle directly

Thanks! Could you also make a browserified version of https://github.com/sindresorhus/semver-regex? I need that seperately since I want to get the full branch name of the latest release instead of the "cleaned" name that `latest-semver` returns

**Comment by sindresorhus** [comment]
Sure, here you go:

```js
(function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.semverRegex=f()}})(function(){var define,module,exports;return function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s}({1:[function(require,module,exports){"use strict";module.exports=function(){return/\bv?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z\-]+(?:\.[\da-z\-]+)*)?(?:\+[\da-z\-]+(?:\.[\da-z\-]+)*)?\b/gi}},{}]},{},[1])(1)});
```

Call it with `semverRegex().test('something')`.

**Comment by sindresorhus** [comment]
Here is `to-semver` browserified: https://gist.github.com/sindresorhus/c6ebcc0075fc08189a1197a953c3bfa9

You can use it as `toSemver(['v0.1.0', 'v1.0.0'])`.

---

For reference, the script I'm using:

```
browserify --standalone=toSemver . | uglifyjs > browser.js
```

Make sure you have https://www.npmjs.com/package/uglify-es installed, and not normal Uglify.

**Comment by jgierer12** [comment]
@sindresorhus Thank you, I think that's the last one I'll need 😅

**Comment by sindresorhus** [comment]
I can't wait for us to be able to use ES2015 modules.

**Comment by sindresorhus** [comment]
I think the button is a tiny bit too close to the edit button.

---

> View this file at 1.16.1

Maybe: `View the latest tagged version (1.16.1) of this file` or something similar.

**Comment by hkdobrev** [comment]
@sindresorhus @jgierer12 👏 This is awesome! Thanks!

When browsing projects with this I've noticed I'd prefer the link to the latest release to be somewhere to the top. Some projects have a big list of files and folders in the root and the readme is pushed down a lot. Having that button visibly accessible as soon as you open the repo page would be more useful in my opinion. I think just to the right of the branch selector would be best. That's not to say the link from the readme should be removed, though.

What do you think? Could we put this above the repo file browser on the left side, to the right of the branch/tag selector?

image

**Comment by jgierer12** [comment]
> Could we put this above the repo file browser on the left side, to the right of the branch/tag selector?

That's a great idea, but I think we should use another icon for that. Maybe [`book`](https://octicons.github.com/icon/book/)? That might be misleading though since it's also used for the wiki

> Maybe: `View the latest tagged version (1.16.1) of this file` or something similar.

I tried to keep it short and in line with GitHub's native tooltips, but I agree we should make it clear that it's the latest release.

**Comment by hkdobrev** [comment]
> Maybe: View the latest tagged version (1.16.1) of this file or something similar and shorter.

This got me thinking... We can actually add such link to every blob in a repo quite easily. We can have it in readme on the main page of the repo when the file header is not visible, but on blob pages we can have it either next to the branch selector or in the file header with the other buttons.

**Comment by jgierer12** [comment]
> We can actually add such link to every blob in a repo quite easily

👍 for putting it next to the branch selector

**Comment by sindresorhus** [comment]
> 👍 for putting it next to the branch selector

👍

**Comment by jgierer12** [comment]
LGTM and leave https://github.com/sindresorhus/refined-github/pull/395#issuecomment-301189407 for a separate PR

**Comment by bfred-it** [comment]
Merge?

**Comment by sindresorhus** [comment]
@jgierer12 Can you fix the merge conflict?

@bfred-it Feel free to fix the merge conflict and merge right away if you want.

**Pull request merged**
