### PR TITLE
fix error where extra spaces where added when accepting a suggestion

### LINKED ISSUE #162: Extra spaces in comments because of using TAB
This is a side effect of #117 I believe (pretty close to positive).

To use the available autocomplete when inserting a @ mention or emoji, you type <kbd>@</kbd>, <kbd>TAB</kbd> or <kbd>:</kbd>, <kbd>TAB</kbd>. This winds up adding extra spaces to the end of the comment. You don't really notice until you try to quickly get to the end of the text/line with <kbd>⌘</kbd><kbd>→</kbd>.

I have a sneaking suspicion that other keyboard events are adding spacing too, but I can't replicate it.

### PR DESCRIPTION
**Pull request by blackjid**
fix #162

### CODE REVIEW

**Comment by paulmolluzzo** [comment]
Does this account for command/alt/ctrl tab scenarios?

**Comment by paulmolluzzo** [comment]
Command, control, and shift tab seem to be working as expected (not tabbing the content). Autocomplete is also not adding spaces.

However, I found another issue: The spacing being generated is inconsistent.

If the last character is a period, tab adds 3 spaces. If it's a comma, it adds 2. if the last character is a space it adds 4. These rules hold true past new lines. IDK if this is a bug worth fixing or not, but unlike my editor, I can't see invisibles so even with this functionality I'm using the spacebar for alignment mostly.

**Comment by DrewML** [comment]
@paulmolluzzo Yeah, I noticed this when it first got merged in. I think the issue though is even more general than that: I can replicate the bug with any characters, not just `.` or `,`.

Looks like the culprit is `const indentSize = (size - el.selectionEnd % size) || size;`. I *think* that's there to try and help you out (if you have indented 2 spaces already, only add 2 more to create the full indent). If that's what that line is truly meant to do, I don't think it's necessary.

@blackjid Thoughts?

**Comment by blackjid** [comment]
> Looks like the culprit is const indentSize = (size - el.selectionEnd % size) || size;. I think that's there to try and help you out
hey @DrewML that's exactly what that line tries to do. I think that is the way most text editors behave



> However, I found another issue: The spacing being generated is inconsistent.

@paulmolluzzo you are right, I just found why the behaviour is inconsistent. It math it's being done using the whole text insted of just the current line. So it depends on what you have written before. For the first line it always work well.. I'll try to find the time to add that fix to this PR

**Comment by DrewML** [comment]
> hey @DrewML that's exactly what that line tries to do. I think that is the way most text editors behave

@blackjid That's funny - my editor does do that, but I never noticed until you pointed it out :laughing:

**Comment by sindresorhus** [comment]
@blackjid Any chance you can finish this up?

**Comment by blackjid** [comment]
yes, I will, but I need some time..

**Comment by paulmolluzzo** [comment]
@blackjid Any update on this? This bug is buggin' me.

**Comment by DrewML** [comment]
@blackjid Feel free to let us know if you're not going to be able to address it soon, and one of us can jump in and write a fix.

**Comment by blackjid** [comment]
Hi guys, 

I was working on this, making great progress when I found this in google. http://jakiestfu.github.io/Behave.js

It's a library that adds the functionality we were talking here, and a few more awesome additions.

I integrated it in this PR #192. Give it a try and let me know what do you think

**Comment by DrewML** [comment]
@blackjid Based on some of the open issues with that library, I think it might be better to just proceed with the minimal fix that this PR would address. Are you still interested in doing that?

**Comment by paulmolluzzo** [comment]
OK, I'm willing to accept and merge this PR as is and consider it a fix.

@blackjid did solve the extra spaces when tabbing to autocomplete. The extra issue I brought up in the PR is still there and can be broken out into a separate issue to resolve later.

Any thoughts@sindresorhus @DrewML @hkdobrev?

**Comment by sindresorhus** [comment]
Agreed

**Pull request closed without merging**
