### PR TITLE
Remove “collapse files in a pull request diff” feature

### PR DESCRIPTION
**Pull request by sindresorhus**
It was implemented by GitHub.

### CODE REVIEW

**Comment by sindresorhus** [comment]
@jgierer12 They did: https://gist.github.com/Razorsharpy/68f6085eee02c65a20cc826049d1c78f/revisions // fyi @benoror

**Comment by jgierer12** [comment]
Yes, but only the revisions. #391 also added support for collapsing files on the "Code" tab (https://gist.github.com/Razorsharpy/68f6085eee02c65a20cc826049d1c78f/)

**Comment by sindresorhus** [comment]
> also added support for collapsing files on the "Code" tab 

What's the point of having it on the Code tab? This feature is mostly just useful for collapsing files you've already reviewed in a diff or that you want to skip.

**Comment by jgierer12** [comment]
I guess so, just wanted to point out that we'll lose that feature.
@benoror what do you think about this?

**Comment by hkdobrev** [comment]
:+1: from me. I wanted to suggest this as well, but was concerned with the open PR about collapse all buttons.

**Comment by benoror** [comment]
> Seems like they didn't implement it for Gist files (#391) 😕

They must have changed the underlying markup recently, since it stopped working for my gist files.

> What's the point of having it on the Code tab? This feature is mostly just useful for collapsing files you've already reviewed in a diff or that you want to skip

> I guess so, just wanted to point out that we'll lose that feature.
> @benoror what do you think about this?

My original use-case: I need to collapse a multi-file gist in the Code tab, as I use it for other things besides code (mostly as a usecanvas.com replacement)

**Comment by hkdobrev** [comment]
As the next enhancement on top of GitHub implementation, I'd like to see keyboard navigation for next/previous file in a diff (<kbd>j</kbd>/<kbd>k</kbd>) and collapse toggle keyboard shortcut (<kbd>space</kbd>?).

**Comment by hkdobrev** [comment]
@benoror Probably open a new issue to discuss collapsing files when not looking at a diff. Personally, I'd be against it as I won't use it and don't want to provide potentially confusing alterations to something which GitHub is already supporting.

**Comment by hkdobrev** [comment]
@sindresorhus Could you create a new `cleanup` label for things such as this? Thanks!

**Comment by sindresorhus** [comment]
Done

**Pull request merged**
