### PR TITLE
Remove additional pane whitespace on dash.

### PR DESCRIPTION
**Pull request by samccone**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you elaborate on what this fixes? I saw no changes when applying this.

**Comment by samccone** [comment]
#### Before

screen shot 2016-02-15 at 11 58 57 am

#### After

screen shot 2016-02-15 at 11 59 05 am

**Comment by sindresorhus** [comment]
Hmm, weird. This extension should remove the "Repositories you contribute to" box: https://github.com/sindresorhus/refined-github/blob/735933c01165e4f706b6a8193035928d59761e7b/extension/content.css#L14-L17

Any idea why it doesn't? Do you have other CSS selectors for it than me?

**Comment by samccone** [comment]
screen shot 2016-02-15 at 12 03 59 pm


:)

**Comment by samccone** [comment]
Looks like we will want to always hide the js-notice

**Comment by sindresorhus** [comment]
> Looks like we will want to always hide the js-notice

Would you be able to do a PR on that? I don't have the notice, so hard to test...

**Comment by sindresorhus** [comment]
Never mind. Doing it.

**Pull request closed without merging**
