### PR TITLE
Fix console errors

### LINKED ISSUE #3845: `comments-time-machine-links`: Cannot read property 'attributes' of null
When opening some github PR page (it could reproduce for many PR links), below error shows up in the F12 console window. The top frame in below stack is listed as the last line in below code snippet.

❌ Refined GitHub → comments-time-machine-links → TypeError: Cannot read property 'attributes' of null
    at init (refined-github.js:5062)
    at runFeature (refined-github.js:2116)
    at setupPageLoad (refined-github.js:2124)
    at refined-github.js:2157 

```js
    }), source_features.add("comments-time-machine-links", {
      include: [ hasComments ],
      init: function() {
        const comments = select_dom.all('\n\t\t:not(.js-new-comment-form):not([id^="pullrequestreview"]) > .timeline-comment:not(.rgh-time-machine-links),\n\t\t.review-comment > .previewable-edit:not(.is-pending):not(.rgh-time-machine-links)\n\t');
        for (const comment of comments) {
          const timestamp = select_dom("relative-time", comment).attributes.datetime.value;
```

### PR DESCRIPTION
**Pull request by yakov116**
- Fix console error in `comments-time-machine-links` - Test on any issue/pr fixes #3845
- Fix console error with `linkify-issues` on gists - Test on https://gist.github.com/yakov116
	After the change to `getCurrentRepo()` getRepo can be undefined

- Fix some empty repo errors
https://github.com/yakov116/fluffy-bassoon

### CODE REVIEW

**Comment by fregante** [comment]
If it has errors on gists, it’s because it shouldn’t run on gists

**Comment by yakov116** [comment]
Hmm I am not by a  computer this second. But I think it is supposed to run. What is the comment `https://github.com/sindresorhus/refined-github/issues/1305` referring to?

**Comment by fregante** [comment]
It's `linkify_urls_in_code`, not linkifyIssues. Issue references like `#123` on gists don't make sense. To be honest even references like `user/repo#123` are popular enough to support gists at all for that feature.

**Comment by yakov116** [comment]
ok will look into it

**Review by fregante — APPROVED** [review]

**Pull request merged**
