### PR TITLE
Change style of `emphasize-draft-pr-label`

### PR DESCRIPTION
**Pull request by fregante**
Closes https://github.com/sindresorhus/refined-github/issues/2450

The original problem was that the contrast between green and gray was poor. I think this solution increases the contrast without making Draft PRs look bigger.

## Normally

normal

## Before

before

## After

after

# Test

https://github.com/sindresorhus/refined-github/pulls
https://github.com/WordPress/gutenberg/pulls

### CODE REVIEW

**Comment by tooomm** [comment]
I like the outlined style a lot. 👍 
Maybe little less shadow if it's still readable as it also stresses things a bit?

Idea: Did you also try the usual green color from PR's over grey?

**Comment by fregante** [comment]
Yeah my initial idea was to add a solid outline instead but this looked ok. 

You mean a green shadow/outline? Doesn’t sound bad

**Comment by sindresorhus** [comment]
Good idea, but the shadow is too weak. Hard to see the icon.

**Comment by tooomm** [comment]
>Yeah my initial idea was to add a solid outline instead but this looked ok.

Solid outline could also work. And deals with @sindresorhus's concern.
Could you post a picture, please?

>You mean a green shadow/outline? Doesn’t sound bad

Exactly.

<br>

>Good idea, but the shadow is too weak. Hard to see the icon.

I even feel like the shadow stresses the icon in some way as it pops out from the background in comparison to the solid ones.
Would need to see a comparison to judge if grey/green and outlined with/without shadow work better.

**Comment by fregante** [comment]
Outline would be best, but there's no way to do that in CSS. I'd have to recreate the icon with the outline and embed the whole new SVG. Anyone wants to take a crack at creating the style in Illustrator/Sketch/etc?

**Comment by sindresorhus** [comment]
Stroke:

Screenshot 2020-02-01 at 01 05 47

```css
the-icon {
	stroke: rgba(0, 0, 0, 0.8);
	stroke-width: 0.2px;
}
```

**Comment by sindresorhus** [comment]
Yours with stronger shadow looks pretty good though:

Screenshot 2020-02-01 at 01 11 59

```css
filter: drop-shadow(rgb(0, 0, 0) 0px 0px 0.7px);
```

**Comment by fregante** [comment]
> Looks pretty bad...

Yeah, because the stroke is applied _on_ the border (half inside, half outside).

**Pull request merged**
