### PR TITLE
Improve logging of enabled features

### PR DESCRIPTION
**Pull request by sindresorhus**
This also adds a logger we can use for other things too.

screen shot 2017-12-17 at 11 43 52

### CODE REVIEW

**Comment by bfred-it** [comment]
Console.group is meant to be used for sync code: open, log, log, log, close. 

In this case unrelated logging might be trapped in our group, especially if we open it up for use to any part of the extension.

**Comment by sindresorhus** [comment]
It’s only a problem if we use `console.log` instead of `logger.log`, which we won’t. Otherwise it will be correctly split up.

**Comment by bfred-it** [comment]
I’m talking about logging done by other extensions

**Comment by sindresorhus** [comment]
@bfred-it I could monkey-patch `console.log` and handle it. Then it will just be split up. Still better than no grouping:

screen shot 2017-12-17 at 19 40 16

**Comment by ramlmn** [comment]
- I agree that monkey-patching `console.log` is better than no grouping, but what if some other extension did the same (monkey-patched `console.log` for themselves)?

- We can do something else like **store and flush** logs, but we don't know when to flush the logs.
  ``` js
  class Logger {
  	constructor() {
  		this.logs = [];
  	}
  
  	log(...messages) {
  		this.logs.push(messages);
  	}
  
  	flush() {
  		console.group(this.group);
  		this.logs.map(message => console.log(...message));
  		console.groupEnd();
  
  		this.logs = [];
  	}
  }
  ```

**Comment by bfred-it** [comment]
Can’t monkey patch, extensions are run in a safe environment, same reason why we can’t access a jQuery loaded on a site.

**Comment by bfred-it** [comment]
Also, all solutions here make the logging lose the context/line number. That's ok for features, not so much for other logging.

**Comment by sindresorhus** [comment]
Yeah, I'm gonna close it. Not worth the trouble. I do think we should prefix each of the feature logs with the prefix: `Enabled feature: ` so it's totally clear what it's about though.

**Pull request closed without merging**
