### PR TITLE
Linkify dashboard feed events issue strings

### LINKED ISSUE #1354: Feature Request: In the activity feed make PR numbers link to the PR
For example, in the picture below I'd like `#333` to link to PR-333 in that repo so that I can quickly check the PR to see what changes were merged in:

image

### PR DESCRIPTION
**Pull request by connorbrathwaite**
really enjoy this extension, so to begin contributing i've attempted a potential implementation of #1354. 

all feedback is welcome and appreciated!
 
- pic: image

Fixes #1354

### CODE REVIEW

**Comment by bfred-it** [comment]
Thanks for the PR! I think this can just be part of the existing `linkify-issues` feature.

**Comment by connorbrathwaite** [comment]
makes sense, will make some propositions in another commit soon as i can spare a moment to tidy this up :)

**Comment by sindresorhus** [comment]
Can you add it to the readme? To here: https://github.com/sindresorhus/refined-github#added-features

**Comment by sindresorhus** [comment]
I don't have any news feed items with commits with issue mentions. Can you do a couple of commits to https://github.com/sindresorhus/playground with issues mentions in the title so I can test this PR?

**Comment by sindresorhus** [comment]
I got an issue title in my feed now. This doesn't seem to work. The link goes to `https://issues/8`.

Here's the HTML of the news feed item:

```html
<div class="dashboard-rollup-item Box p-3 mt-2">
    <span>4 commits to</span>
    <a class="branch-name" data-hydro-click="{&quot;event_type&quot;:&quot;news_feed.event.click&quot;,&quot;payload&quot;:{&quot;event&quot;:{&quot;repo_id&quot;:51763138,&quot;actor_id&quot;:1913805,&quot;public&quot;:true,&quot;type&quot;:&quot;PushEvent&quot;,&quot;target_id&quot;:null,&quot;id&quot;:8204654989,&quot;additional_details_shown&quot;:false,&quot;grouped&quot;:false},&quot;event_group&quot;:null,&quot;org_id&quot;:null,&quot;target_type&quot;:&quot;event&quot;,&quot;user_id&quot;:170270,&quot;action_target&quot;:&quot;branch&quot;,&quot;client_id&quot;:&quot;599635782.1524079388&quot;,&quot;originating_request_id&quot;:&quot;E4EB:2C94:9476E0:D12776:5B8CEDF4&quot;,&quot;originating_url&quot;:&quot;https://github.com/dashboard-feed&quot;}}" data-hydro-click-hmac="71db23a4d1e4a94b18f57f4185b484e73b23b8703cb431e8f4f2dd32b8caee0a" data-ga-click="News feed, event click, Event click type:PushEvent target:branch" href="/SamVerschueren/vscode-ava/tree/master">master</a>

    <div class="commits ">
      <ul class="pt-1">
          <li class="d-flex flex-items-baseline m-0">
            <span title="sindresorhus">
              <a class="d-inline-block" data-hovercard-user-id="170270" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="/sindresorhus" aria-describedby="hovercard-aria-description"><img class="mr-1" src="https://avatars3.githubusercontent.com/u/170270?s=32&amp;v=4" width="16" height="16" alt="@sindresorhus"></a>
            </span>
            <code><a class="mr-1" data-hydro-click="{&quot;event_type&quot;:&quot;news_feed.event.click&quot;,&quot;payload&quot;:{&quot;event&quot;:{&quot;repo_id&quot;:51763138,&quot;actor_id&quot;:1913805,&quot;public&quot;:true,&quot;type&quot;:&quot;PushEvent&quot;,&quot;target_id&quot;:null,&quot;id&quot;:8204654989,&quot;additional_details_shown&quot;:false,&quot;grouped&quot;:false},&quot;event_group&quot;:null,&quot;org_id&quot;:null,&quot;target_type&quot;:&quot;event&quot;,&quot;user_id&quot;:170270,&quot;action_target&quot;:&quot;sha&quot;,&quot;client_id&quot;:&quot;599635782.1524079388&quot;,&quot;originating_request_id&quot;:&quot;E4EB:2C94:9476E0:D12776:5B8CEDF4&quot;,&quot;originating_url&quot;:&quot;https://github.com/dashboard-feed&quot;}}" data-hydro-click-hmac="124073c0a3bf668c7a329482d3c14d38c10f307e5e17ba7b5870ac28e3da6fe9" data-ga-click="News feed, event click, Event click type:PushEvent target:sha" href="/SamVerschueren/vscode-ava/commit/5060186f183560d04fb8f367dc31e8ff5003ab86">5060186</a></code>
            <div class="dashboard-break-word lh-condensed">
              <blockquote>
                Update snippets for latest AVA version (#8)
              </blockquote>
            </div>
          </li>
          <li class="d-flex flex-items-baseline m-0">
            <span title="SamVerschueren">
              <a class="d-inline-block" data-hovercard-user-id="1913805" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="/SamVerschueren" aria-describedby="hovercard-aria-description"><img class="mr-1" src="https://avatars0.githubusercontent.com/u/1913805?s=32&amp;v=4" width="16" height="16" alt="@SamVerschueren"></a>
            </span>
            <code><a class="mr-1" data-hydro-click="{&quot;event_type&quot;:&quot;news_feed.event.click&quot;,&quot;payload&quot;:{&quot;event&quot;:{&quot;repo_id&quot;:51763138,&quot;actor_id&quot;:1913805,&quot;public&quot;:true,&quot;type&quot;:&quot;PushEvent&quot;,&quot;target_id&quot;:null,&quot;id&quot;:8204654989,&quot;additional_details_shown&quot;:false,&quot;grouped&quot;:false},&quot;event_group&quot;:null,&quot;org_id&quot;:null,&quot;target_type&quot;:&quot;event&quot;,&quot;user_id&quot;:170270,&quot;action_target&quot;:&quot;sha&quot;,&quot;client_id&quot;:&quot;599635782.1524079388&quot;,&quot;originating_request_id&quot;:&quot;E4EB:2C94:9476E0:D12776:5B8CEDF4&quot;,&quot;originating_url&quot;:&quot;https://github.com/dashboard-feed&quot;}}" data-hydro-click-hmac="124073c0a3bf668c7a329482d3c14d38c10f307e5e17ba7b5870ac28e3da6fe9" data-ga-click="News feed, event click, Event click type:PushEvent target:sha" href="/SamVerschueren/vscode-ava/commit/2a76813c520c51cb5648f676af47523c64fb69c5">2a76813</a></code>
            <div class="dashboard-break-word lh-condensed">
              <blockquote>
                0.6.0
              </blockquote>
            </div>
          </li>

          <li class="f6 mt-2">
            <a class="link-gray" data-hydro-click="{&quot;event_type&quot;:&quot;news_feed.event.click&quot;,&quot;payload&quot;:{&quot;event&quot;:{&quot;repo_id&quot;:51763138,&quot;actor_id&quot;:1913805,&quot;public&quot;:true,&quot;type&quot;:&quot;PushEvent&quot;,&quot;target_id&quot;:null,&quot;id&quot;:8204654989,&quot;additional_details_shown&quot;:false,&quot;grouped&quot;:false},&quot;event_group&quot;:null,&quot;org_id&quot;:null,&quot;target_type&quot;:&quot;event&quot;,&quot;user_id&quot;:170270,&quot;action_target&quot;:&quot;comparison&quot;,&quot;client_id&quot;:&quot;599635782.1524079388&quot;,&quot;originating_request_id&quot;:&quot;E4EB:2C94:9476E0:D12776:5B8CEDF4&quot;,&quot;originating_url&quot;:&quot;https://github.com/dashboard-feed&quot;}}" data-hydro-click-hmac="28632c84dc5010f9edc7867fc065e5784aba3108845c28c7fce069dcc36f2f87" data-ga-click="News feed, event click, Event click type:PushEvent target:comparison" href="/SamVerschueren/vscode-ava/compare/8fc3f68738...2a76813c52">
              2 more commits »
</a>          </li>

      </ul>
    </div>
</div>
```

**Comment by lukehefson** [comment]
Hey folks! Apologies for the short notice – it was a very quick ship for the [Papercuts](https://blog.github.com/2018-08-28-announcing-paper-cuts/) team 😅  – but we just shipped this "natively" for github.com!

**Comment by sindresorhus** [comment]
@lukehefson Yay. Thanks for letting us know :)

**Pull request closed without merging**
