### PR TITLE
Make `forked-to`'s cache case-insensitive

### LINKED ISSUE #2909: `forked-to` only works on some repositories
Out of 31 source repos of the forks I have on my account, only on 3 of them (funnily, refined-github is one of them) `forked-to` seems to work.
Example repo where it doesn't work: https://github.com/Cog-Creators/Red-DiscordBot
Screenshot:
image

### PR DESCRIPTION
**Pull request by jack1142**
Fixes #2909

### CODE REVIEW

**Comment by fregante** [comment]
I think we should change the original function, so it matches `getRepoURL()`

https://github.com/sindresorhus/refined-github/blob/4b8056ab2d53a9a7ba20130a38f06dec0813fc98/source/libs/utils.ts#L93

**Comment by jack1142** [comment]
I was thinking about that but I noticed that one of functions using it is user-facing:
https://github.com/sindresorhus/refined-github/blob/6c46766237ccbf8a8c23ba07aca1e48a11a71b4b/source/features/show-open-prs-of-forks.tsx#L77

I can change it but what should I do about this occurrence?

**Comment by fregante** [comment]
You're right, it's not always safe

**Comment by fregante** [comment]
Thank you for the fix!

**Pull request merged**
