### PR TITLE
Show more than three Avatars for Reactions

### LINKED ISSUE #240: Show more than three Avatars for Reactions?
I kinda think it should just show as many as possible, only truncating when we run out of space.

Right now we are leaving a whole bunch of unused whitespace to the right of the reactions.

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes #240

Testable on https://github.com/babel/babel/pull/3646

> more than 3 avatars

Still limited and compressed when they don't fit:

> lots of avatars

Since this is now in JS, _limited_ avatars won't be loaded at all (contrary to what happened before)

### CODE REVIEW

**Comment by bfred-it** [comment]
Also fixes this bug (selector was broken and was hiding more avatars than necessary):

**Comment by bfred-it** [comment]
Loading 460x460 images bothered me, so thanks to this we load 40x40 or 20x20 images: https://stackoverflow.com/a/36380674/288906

**Comment by sindresorhus** [comment]
Looks good. Another issue to test it with: https://github.com/facebook/react/issues/10191

**Comment by bfred-it** [comment]
Excellent testbed. I already found a line that wraps:

screen shot 2017-07-27 at 17 58 39

Also this thread on hover https://github.com/facebook/react/issues/8854

screen shot 2017-07-27 at 18 05 30

**Pull request merged**
