### PR TITLE
Fix `update-pr-from-base-branch` duplication

### LINKED ISSUE #3927: Text from `update-pr-from-base-branch` is duplicated
image
image

I can't really send links since only maintainers and PR authors can update the base branch, but it seems to happen on any PR I can update the base branch on.

### PR DESCRIPTION
**Pull request by yakov116**
1. LINKED ISSUES:
   Fixes #3927 

2. TEST URLS:
   https://github.com/sindresorhus/refined-github/pull/3847 (this needed 800)
https://github.com/sindresorhus/refined-github/pull/3922

3. SCREENSHOT:
   None

I went with debounce over select observer. My thinking was that this is the only issue.

### CODE REVIEW

**Comment by fregante** [comment]
Debounce delays the first API call by 800ms. Can you look into why the API call isn’t being cached? What event(s) is calling this function 3 times?

**Comment by yakov116** [comment]
Looks like there are a few events that are happening. I could not figure them all out... So select-observer it is.

**Comment by fregante** [comment]
Can the observer’s selector be made more specific so we don’t have to use stillLoading? It should observe the final element that we need, it’s called once it’s found. No other listener should call addButton

**Comment by yakov116** [comment]
> Can the observer’s selector be made more specific so we don’t have to use stillLoading?

I think it could will check later tonight

**Comment by fregante** [comment]
Might be worth looking for a selector that also works on failing PRs https://github.com/sindresorhus/refined-github/issues/3699

**Comment by fregante** [comment]
I got an idea

**Pull request closed without merging**
