### PR TITLE
Update patch diff links selector

### PR DESCRIPTION
**Pull request by bfred-it**
It looks like GH change the class name

### CODE REVIEW

**Comment by paulmolluzzo** [comment]
@bfred-it You'll be able to test `addDeleteForkLink()` for #448 now. Once it's merged you should see the "Delete Branch" link on this PR.

**Comment by bfred-it** [comment]
screen shot 2017-05-30 at 10 17 37

I see this with and without RGH

**Comment by jgierer12** [comment]
`addDeleteForkLink()` should add a button to delete the entire forked repo, instead of just the branch

**Comment by bfred-it** [comment]
Yep but I don't see it with `master` either, that's why I was asking for someone else to verify :/

**Pull request merged**
