### PR TITLE
Fix adding patch and diff links to commit pages

### LINKED ISSUE #1080: patch/diff commit links feature broken
Example: https://github.com/sindresorhus/refined-github/commit/09041df0cba07b115bd0de437540bda271e6efb7

```
Uncaught (in promise) TypeError: Cannot read property 'append' of null
    at add_patch_diff_links (add-patch-diff-links.js:16)
    at enableFeature (utils.js:29)
    at <anonymous>
```

### PR DESCRIPTION
**Pull request by ramlmn**
Fixes and closes #1080 (again!).

Test links:
* https://github.com/sindresorhus/refined-github/commit/09041df0cba07b115bd0de437540bda271e6efb7
* https://github.com/sindresorhus/refined-github/pull/1119/commits/0f51dfe30eb36e60369a188786d88b6e421f1543

### CODE REVIEW

**Comment by ramlmn** [comment]
I can't spell `patch` 😜 🤦‍♂️.

**Comment by hkdobrev** [comment]
Strangely the patch/diff links for me work on these pages without applying the fix.

**Comment by ramlmn** [comment]
Strange!
```
https://github.com/sindresorhus/refined-github/pull/1119/commits/0f51dfe30eb36e60369a188786d88b6e421f1543
```
gets converted to
```
https://github.com/sindresorhus/refined-github/commit/0f51dfe30eb36e60369a188786d88b6e421f1543
```
automatically by GitHub.

@hkdobrev the issue is on the pull-commit page, not on the direct-commit page!

**Comment by bfred-it** [comment]
> Strange!

Yep, it's a GitHub bug: https://github.com/sindresorhus/refined-github/issues/1053

I'm gonna report it. Please do the same!

**Comment by bfred-it** [comment]
Thanks Ram :)

**Pull request merged**
