### PR TITLE
Meta: Fix options pop up width in Chrome

### LINKED ISSUE #933: Clicking the extension icon shows a narrow version of the options page
screen shot 2017-12-29 at 22 43 17

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes #933

### CODE REVIEW

**Comment by sindresorhus** [comment]
Let's make it 400px. That the `min-width` set by Chrome in the extensions page.

**Comment by bfred-it** [comment]
Doesn't sound right

screen shot 2017-12-30 at 10 15 54

**Comment by bfred-it** [comment]
But it doesn't hurt :+1:

**Comment by sindresorhus** [comment]
screen shot 2017-12-30 at 12 58 24 2

**Comment by bfred-it** [comment]
`.overlay .page` `!=` `iframe body`, entirely different context.

**Pull request merged**
