### PR TITLE
Rename `collapse-markdown-sections` to `collapse-wiki-sections`

### PR DESCRIPTION
**Pull request by fregante**
The feature is problematic https://github.com/sindresorhus/refined-github/issues/4144
And not that useful anymore thanks to the native TOC https://github.com/sindresorhus/refined-github/issues/4244

### CODE REVIEW

**Review by yakov116 — APPROVED** [review]
LGTM

**Comment by yakov116** [comment]
add "implemented by github"? lable?

**Comment by fregante** [comment]
No, we still have the feature and GitHub did not implement it

**Comment by yakov116** [comment]
Migration?

**Comment by fregante** [comment]
We don't need to migrate every feature, especially when the changes are substantial or if it had serious (now resolved) issues that brought people to disable it.

**Pull request merged**
