### PR TITLE
Fix "Trending" menu item when displayed in navigation accordion

### PR DESCRIPTION
**Pull request by Kocal**
**Before:**
capture d ecran de 2018-08-20 07-41-34

capture d ecran de 2018-08-20 07-37-56

**After:**

capture d ecran de 2018-08-20 07-43-40

capture d ecran de 2018-08-20 07-44-04

### CODE REVIEW

**Comment by sindresorhus** [comment]
Where can I test this? I've never seen the accordion menu on desktop before.

**Comment by Kocal** [comment]
Navigate to homepage and resize your window to a certain width

**Comment by sindresorhus** [comment]
Nope, not seeing it. I assume you're in the new dashboard beta?

**Comment by Kocal** [comment]
Yep

**Comment by Kocal** [comment]
Hum, maybe it broke something in the old dashboard. 🤔

**Comment by sindresorhus** [comment]
I'm gonna hold this until the new dashboard is out of beta. They might change things around before it's final.

**Comment by bfred-it** [comment]
The [Trending page](https://github.com/trending) itself has been responsive for a while, you can see it there.

**Pull request merged**
