### PR TITLE
Hide dashboard activity cards

### LINKED ISSUE #896: Make the ”repository starred” event more compact
Currently GitHub shows a preview of the repository on your dashboard whenever someone has starred it.
repositories

I’d suggest simplifying it so dashboard would be super compact as it used to be.

I would suggest some approaches on how to handle this:

1. Hide those previews completely.
1. Add a link to expand the event with a preview.

WDYT?

### PR DESCRIPTION
**Pull request by jgierer12**
Fixes #896 

Before | After
-|-
Before | After

### CODE REVIEW

**Comment by jgierer12** [comment]
I just noticed that label activities now have no link to the issue that was labeled, so I restored the card for those. Should we leave it like that or extract the issue link via JS and put it somewhere else so it visually matches the other activities?

Screenshot

**Comment by hkdobrev** [comment]
I think putting labels have no place in the home feed 😬

**Comment by jgierer12** [comment]
It's just `help wanted` and `good first issue` labels though so we decided to keep them in #744

**Comment by hkdobrev** [comment]
@jgierer12 I was actually wondering whether GitHub has done that and I thought I was imagining things. Thanks for the pointer to that discussion!

**Comment by sindresorhus** [comment]
It's slightly annoying that the preview shows when you just hover over the item. I think it should show only when you hover over the actual link to the repo, and maybe with a delay of 200 ms, so it doesn't show when you just drag the mouse downwards.

**Comment by tanmayrajani** [comment]
Would this conflict with [GitHub Hovercard](https://github.com/Justineo/github-hovercard)?

**Comment by jgierer12** [comment]
> I think it should show only when you hover over the actual link to the repo

That's impossible with CSS only, at least until the [`:has()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) spec gets implemented.



> With a delay of 200 ms, so it doesn't show when you just drag the mouse downwards

👍

**Comment by bfred-it** [comment]
What do you say? It felt a bit flat without it. The box shadow matches GitHub's overlays.
  
with box shadow

**Comment by sindresorhus** [comment]
@bfred-it Looks great!

:shipit: when you've added it to "new features" in the readme.

**Comment by jgierer12** [comment]
@bfred-it 3c1028957b52810e93ffa49274afd06359eebe27 caused the label activity cards to get hidden again. Was that intended? See https://github.com/sindresorhus/refined-github/pull/899#issuecomment-353599933

**Comment by jgierer12** [comment]
@sindresorhus You might want to update the 'Dashboard cleanup' gif in the readme, it still shows the old dashboard

**Comment by bfred-it** [comment]
It wasn’t intended. Will fix tomorrow probably ☺️

**Comment by bfred-it** [comment]
@jgierer12 I don't have any "help wanted" events in my feed so I made this change blindly by looking at 8f73f3f

Does it work? If not, can you add a Help Wanted label to one of your repos?

**Comment by tanmayrajani** [comment]
@bfred-it you can check your feed, I added 'help wanted' to an issue on NPG..

**Comment by bfred-it** [comment]
Thank you! It works :D Merging

**Comment by bfred-it** [comment]
hmm you know what. I think the cards are actually more useful than what we show now. Like my original [GitHub Clean Feed](https://github.com/bfred-it/github-clean-feed) did, I'd rather focus on the repo being acted on, rather than the people. Having 10 identical events for "X starred user/repo" is not that useful and it looks cluttered.

GitHub kinda got this right in their [dashboard/discover](https://github.com/dashboard/discover) page but uses whatever unknown algorithm to pick the repos. 

I'd rather see something like this instead:

screen shot 2017-12-28 at 03 07 45

It's more data, less repetition ("X starred same-user/same-repo")

**Pull request merged**
