### PR TITLE
Add search filter for "Everything commented by you"

### LINKED ISSUE #389: Search filter for "Everything commented by you"
I use the search input a lot, and pretty much every day I see myself typing: "commenter:leocaseiro" which is my login.

I was wondering what you guys think if we add a filter that fills that up on "Filters" that populates our login on the search.

Eq: 
screen shot 2017-04-28 at 5 18 55 pm

### PR DESCRIPTION
**Pull request by busches**
Fixes #389

This adds a new search filter on issues/PR pages with the text of
'Everything commented by you' with the filter of 'is:open
commenter:<username>'

### CODE REVIEW

**Comment by sindresorhus** [comment]
Looks pretty good.

You need to make sure it doesn't already exist. Sometimes it can cause duplicates because of caching. To reproduce, go to https://github.com/avajs/ava/issues, choose "Everything commented by you", click on any of the issues, click the back button in the browser, the filter list will now have a duplicate "Everything commented by you". See how this was solved in https://github.com/sindresorhus/refined-github/pull/376#issuecomment-296263549

**Comment by busches** [comment]
Thanks, I didn't check that condition. I've fixed the issue, please let me know what you think. I can also add it to the initial README if you like.

**Comment by sindresorhus** [comment]
>  I can also add it to the initial README if you like.

👍 With a screenshot

**Comment by busches** [comment]
README updated with the screenshot from the issue, as it worked quite well.

**Comment by paulmolluzzo** [comment]
Thanks @busches! This is great! 👏 👏 👏

**Comment by leocaseiro** [comment]
Thanks guys for the nice work 😄

**Pull request merged**
