### PR TITLE
Fix text formatting for name of post editor

### PR DESCRIPTION
**Pull request by arkon**
This fixes a small bug where showing the full name of an edited issue/PR post would show a stray dash at the end like:

> WanderMax commented 5 hours ago • edited by arkon Eugene Cheung -

See https://github.com/kabouzeid/Phonograph/issues/195 for an example.

### CODE REVIEW

**Comment by bfred-it** [comment]
I'm wondering if we need the dash at all.

**Comment by jgierer12** [comment]
> I'm wondering if we need the dash at all.

I would keep some sort of separator as the name is styled like the rest of the comment details. But making it a `•` too would be nice.

**Comment by jgierer12** [comment]
Perhaps we shouldn't show the real name at all for edits?

**Comment by sindresorhus** [comment]
I think the dash looks the best. And I think we should still show the real name. It's always useful, even for edits.

**Comment by arkon** [comment]
I think the dash works best since `•` is already used as a separator between the regular content and the edited timestamp. I do find having the real name there to be useful as well.

**Comment by jgierer12** [comment]
> I think the dash works best since `•` is already used as a separator between the regular content and the edited timestamp

That's why I wanted to change it in the first place, because it doesn't really make any sense to have different styles for the separators. But I guess I'd be fine with keeping it a dash. Still think 

> **jgierer12** Jonas Gierer • commented 5 hours ago • edited by arkon Eugene Cheung

looks better than 

> **jgierer12** Jonas Gierer - commented 5 hours ago • edited by arkon Eugene Cheung

---

BTW, we should style either the username or the real name differently on edits to distinguish them. e.g.

> **jgierer12** Jonas Gierer • commented 5 hours ago • edited by arkon *Eugene Cheung*

or

> **jgierer12** Jonas Gierer • commented 5 hours ago • edited by **arkon** Eugene Cheung

**Comment by arkon** [comment]
I think in terms of maintaining the flow of the original phrasing (i.e. "jgierer12 commented 5 hours ago"), it would actually just make more sense to show the real name within brackets. It doesn't _quite_ make sense when the name and the rest of the sentence are separated.

**Comment by jgierer12** [comment]
Since this is not really related to the PR anymore, I suggest merging it and continuing the discussion in a separate issue

**Pull request merged**
