### PR TITLE
Meta: Add git hooks

### LINKED ISSUE #512: Add Git hooks
I often forget to run `npm run build` after checking out a PR branch. Would be useful to set up some shared Git hooks for running `npm install` and `npm run build` on Git changes, like updated master or other checked out branches.

Maybe using https://github.com/typicode/husky

### PR DESCRIPTION
**Pull request by jgierer12**
Fixes #512 

Using https://github.com/ta2edchimp/opt-cli so you can opt in/out of specific hooks using a `.opt-in`/`.opt-out` file. Not sure about which defaults to use there yet.

### CODE REVIEW

**Comment by hkdobrev** [comment]
👍 I really like the approach with `opt-cli`. I was looking for something similar recently. Will try to use them and comment on the defaults this weekend!

**Comment by sindresorhus** [comment]
Why should we add the ability to opt out? Isn't the whole point of adding this so that we'll ensure we follow the conventions?

**Comment by hkdobrev** [comment]
@sindresorhus The CI build should enforce that. Local tools should not be the thing doing the enforcing. Anyone could use `--no-verify` or don't have the latest tools installed.

**Comment by sindresorhus** [comment]
@hkdobrev You have linting disabled, you do a PR, CI fails because of linting, you have to go back, fix, then wait for CI again. The point is to catch things early.

**Comment by bfred-it** [comment]
I don't think I'd use this, it slows down committing 😄  but I was thinking of a plainer solution:

```sh
rm .git/hooks/pre-commit
```

**Comment by jgierer12** [comment]
If you already have e.g. an editor plugin for the linter there's little sense in running it again before commits. And the 'install on checkout' hook would be pretty annoying for people like me with bad internet 😅 

Husky activates the hooks on install so I think you'd have to run `rm .git/hooks/pre-commit` after every `npm install`. The `opt-cli` approach also makes it possible to enable/disable specific tasks, so you could configure it to `npm run build` on checkout but not `npm install`

**Comment by sindresorhus** [comment]
> If you already have e.g. an editor plugin for the linter there's little sense in running it again before commits.

You might have something that doesn't pass linting just for prototyping. Then when you push, you forgot to fix the code style. That has happened to me many times.

> And the 'install on checkout' hook would be pretty annoying for people like me with bad internet

Why would you check it out if you don't intend to work on the code? And regardless, you can just Ctrl+C. It's not like you would checkout this repo often.

**Comment by sindresorhus** [comment]
I'm not going to stand in the way of this if people think it makes sense. For me, it just feels like a lot of boilerplate for very little gain.

**Comment by bfred-it** [comment]
Any chances of merging this?

**Comment by sindresorhus** [comment]
@bfred-it I still don't see the point of the `opt-cli` mess, but feel free to merge this if you want it.

**Comment by bfred-it** [comment]
I don't personally need the pre-commit, I'm just bothered by the stalled PR 😅

**Comment by jgierer12** [comment]
Closing this for now if both of you don't need it.

**Pull request closed without merging**
