### PR TITLE
replace indent function with codemirror.js

### PR DESCRIPTION
**Pull request by blackjid**
Super simple initial version of codemirror integration. So you can test it.
I really apreciate feedback..

I think using code mirror is awesome... and it works very well.

I have some doubds though..

1. Codemirror has a ton of options... we could discuss which options makes sense to enable
2. I'm initializing codemirror on the `.comment-form-textarea` textareas on `focusin`. I did it this way 
because if I change tabs for example in a pull request, it pjax to load the other page and the
`DOMContentLoaded` event is not fired. 

  As a workaround I could use the `pjax:success` event. Any other idea or aproach?? I 
  really would like to have the `textareas` initialized on page load.

### CODE REVIEW

**Comment by blackjid** [comment]
Ok, I just find out some stuff I should improve

- [ ] Github mentions and issues suggestions
- [ ] Clear codemirror content con comment sumit

**Comment by DrewML** [comment]
Thanks for starting this! I hadn't thought about the mentions/suggestions use-case, but getting that working will be super critical.

**Comment by jamestalmage** [comment]
Also, no soft wraps.

**Comment by DrewML** [comment]
We'll also want to make sure to not regress [this](https://github.com/sindresorhus/refined-github/pull/155) functionality

**Comment by DrewML** [comment]
I _really_ want this feature, but (after looking into it a bit more) it looks like we'll likely have to roll our own replacement for the auto-suggester, which doesn't really sound super fun (or maintainable). We'd still be breaking things like the "Saved Replies" feature, and 3rd party extensions that expect a specific `textarea` (GifHub is an example).

As an alternative, what about if we add a tab next to `Preview` that is a code editor? Example would be:
image

I'm thinking that `Code View` and `Write` would both keep their contents in sync. We'd then just need to hide the `Saved Replies` button when you're in the `Code View` (this pattern is already followed by GitHub in the `Preview` tab).

**Comment by paulmolluzzo** [comment]
Um, I kind of just want to be able to tab in a code fence and move on. I don't _need_ an IDE to write comments.

#162 is still open, so maybe we can just squash that (through a fix or revert) and then discuss this further without having a known bug out there.

Thoughts?

// @sindresorhus @blackjid

**Comment by blackjid** [comment]
@paulmolluzzo I agree, I will continue the ongoing work on https://github.com/sindresorhus/refined-github/pull/164

**Comment by DrewML** [comment]
I really do like the idea of having some Markdown syntax highlighting + tabbing support, but it's definitely a bit too opinionated of a want to include in this extension.

I started up a [small extension](https://github.com/DrewML/OctoEdit) for this behavior specifically. I'm going to close this specific PR since we know we don't want to include `CodeMirror` in this extension

**Pull request closed without merging**
