### PR TITLE
Move recently-pushed branches to the side

### LINKED ISSUE #851: Avoid jump caused by recently pushed branches
This is generally useful, but sometimes you can't send a PR _right now_ so it'll keep pushing your content down about a second after page load, messing with your clicks. Perhaps we can make this less intrusive?

screen shot 2017-12-08 at 17 56 47

### PR DESCRIPTION
**Pull request by bfred-it**
Closes #851 

fade in

Here's how it looks with more than one branch:

3 branches

Not great, considering it hides other content. Possible solutions:

- `x` button to close it
- only show one branch until the user hovers it (if there's more than one it can still show that info)

### CODE REVIEW

**Comment by bfred-it** [comment]
Smaller time, shorter branch-name:

screen shot

**Comment by jgierer12** [comment]
> only show one branch until the user hovers it (if there's more than one it can still show that info)

👍 

Then we should also reverse the order (move the most recently pushed one to the top)

**Comment by hkdobrev** [comment]
I think handling well just a single branch is good enough :) :shipit:

**Comment by bfred-it** [comment]
# Regular

Bottom border highlights that there's more



# Hover

**Comment by bfred-it** [comment]
`show-recently-pushed-branches` actually only adds that banner to some pages (I think `isIssueList`). Feel free to add a `/* */` header explaining this to that file :D 

The feature of this PR is CSS-based and can't be disabled.

**Comment by borekb** [comment]
Thanks, understood, disabling the "feature" but keeping the styles is actually a perfect fit for me.

---

As a complete side note, I was thinking that maybe it would be nice if features were implemented by adding some CSS classes to DOM via feature's javascript, and then CSS in `content.css` was targeting them, not the default ones. That would make feature disabling clean and complete.

At the same time, I'm super-happy that feature disablability is in Refined GitHub in the first place. Last time I tried to use it (sometime last year I think) there were too many decisions that actually made the experience worse for me. The new system is both simple and goes a very long way towards customizability, so I'm happy overall.

**Comment by bfred-it** [comment]
Refer to https://github.com/sindresorhus/refined-github/pull/988#issuecomment-357531152

**Pull request merged**
