### PR TITLE
Load more news until the screen is full

### LINKED ISSUE #256: trigger infinite scroll if not enough dashboard data is loaded
sometimes my dashboard looks like this:
refined-github-fail

In such cases I'd have to click on the `More` button manually. I'd love to see a feature triggers the load functionality one more time if not enough content for the whole page can be displayed.

### PR DESCRIPTION
**Pull request by bfred-it**
- Automatically start loading new content if the button is visible, without scrolling
- Keep loading new content until the button is no longer visible
- If GH's JS was slow to load, clicking the button would trigger a full-page reload because of the non-ajax form submission. _No more!_

Fixes #256

~~Firefox 55+ because of IntersectionObserver. It'll land in September, IIRC.~~ Edit: semi-ponyfill added.

Demo (using [GitHub Clean Feed](https://github.com/bfred-it/github-clean-feed) to hide most content)

demo

### CODE REVIEW

**Comment by sindresorhus** [comment]
Yay. I've been wanting this for a long time. Would it be possible to load two extra pages? That way the next page is already loaded when you scroll down.

**Comment by sindresorhus** [comment]
> We can pick a px value (500px?) to have it ready a bit earlier.

👍

**Comment by bfred-it** [comment]
Done. Merge as you please.

**Comment by sindresorhus** [comment]
It stopped working for me after https://github.com/sindresorhus/refined-github/pull/505/commits/2a955f948170c40e0496d1a535ff726d3d326267. https://github.com/sindresorhus/refined-github/pull/505/commits/55b677c979e88370c193ca28e84f7272c7858b99 works fine.

screen shot 2017-06-19 at 12 07 23

Nothing happens when I scroll.

**Comment by bfred-it** [comment]
I think the issue was 7000a26

It works now

**Comment by sindresorhus** [comment]
Yup, works perfectly now.

**Pull request merged**
