### PR TITLE
Extend `copy-on-y` to more pages

### LINKED ISSUE #4290: `copy-on-y` should be enabled on blame, PRs, etc
1. Go to https://github.com/sindresorhus/refined-github/blame/main/source/features/copy-on-y.tsx or https://github.com/sindresorhus/refined-github/pull/4348/files
2. Press the Y key
3. The URL changes but it's not copied

We should enable the feature on blame pages and any other page where the shortcut works, like isCommit I think

### PR DESCRIPTION
**Pull request by yakov116**
Closes #4290

Try it on
```
https://github.com/sindresorhus/refined-github/blob/main/contributing.md
https://github.com/sindresorhus/refined-github/blame/main/contributing.md
https://github.com/sindresorhus/refined-github/commits/21.5.19
https://github.com/sindresorhus/refined-github/tree/main/source
https://github.com/yakov116/refined-github/compare/upstream...sindresorhus:extend-the-y
```

### CODE REVIEW

**Comment by fregante** [comment]
As #4349 said: 

> Help wanted finding **where else this feature should be enabled**

**Comment by yakov116** [comment]
I dont see anywhere else. I can double check again.

**Comment by fregante** [comment]
Can you add the test URLs for the new detections?

**Comment by yakov116** [comment]
Shoot I had them all and I forgot to add it! Will try later today.

**Comment by yakov116** [comment]
Added

**Pull request merged**
