### PR TITLE
Load more feed items with form submit instead of click

### LINKED ISSUE #19: Account switcher closes itself immediately after click
1. Open https://github.com in a new tab.
2. Click the account switcher quickly.

Expected: The account switcher opens and it stays open.
Actual: The account switcher opens and closes itself immediately. It fixes itself after you hold down your mouse for longer when clicking or after a few times of clicking it.

I'm on Chrome dev channel on Mac OS.
Chrome Version 50.0.2652.0 dev (64-bit)

### PR DESCRIPTION
**Pull request by hkdobrev**
Fixes #19.

Actually clicking the More button while the account switcher is open causes it to hide itself.

### CODE REVIEW

**Comment by paulmolluzzo** [comment]
I have a couple bugs here:
1. `const isDashboard = path === '/';` is too precise. https://github.com/dashboard/ and https://github.com/dashboard/index/2 count too
2. Submitting the form is a "real" submission and cause a full page change to the next page in your paginated notifications (also incurs the previous issue since it doesn't do anything on https://github.com/dashboard/index/2)
3. Submitting the form over and over doesn't work anyway. It keeps interrupting itself, so the page stalls out.

I don't think there's a way around using `click()` because that mimics user behavior enough to fool the existing event listener on the form, which is using `.preventDefault()` and AJAX to load in place.

My suggestion is to basically create an infinite scroll. Bind `more()` to page scroll and go back to using `click()`. This solves the UX issues too: You see everything when you scroll, and if you scroll far enough that organization switcher is out of sight so you can't click it only to have it close on you.

Thoughts?

**Comment by sindresorhus** [comment]
1. Users would never manually go to https://github.com/dashboard/index/2 though.

**Comment by paulmolluzzo** [comment]
> Users would never manually go to https://github.com/dashboard/index/2 though.

True, nor do I know how to get to ~/dashboard manually. I do think it should accept ~/dashboard as being `isDashboard` at least.

**Comment by paulmolluzzo** [comment]
@hkdobrev if you want, I can do a fix for this that uses the infinite scroll idea I suggested. Up to you.

**Pull request closed without merging**
