### PR TITLE
Add link to default branch

### LINKED ISSUE #1029: Add button to see the latest version of file/folder
You ended up on a file in a random revision:

> random revision

How do you get to `master`?

> bunch of branches

Oh god.

What if... ?

> goto HEAD (better icon needed, perhaps)

However finding HEAD is not always easy. We can literally use `HEAD` in the link, but that would not enable the edit/delete buttons. Example: https://github.com/sindresorhus/refined-github/blob/HEAD/source/content.js

Only folders seem to have this piece of information available on the page, so we might at least provide a link on these pages:

HEAD info on directories

### PR DESCRIPTION
**Pull request by bfred-it**
Closes #1029

# Icon

Edit: check out the comment below https://github.com/sindresorhus/refined-github/pull/1115#issuecomment-368288291

I couldn't find a relevant icon for `default` or `HEAD`, so I'm using the merge icon as `upstream`. Can you suggest a better one from here? https://octicons.github.com/

demo

# Test

The default branch is detected thanks to this information that only appears in folder views on branches.

branchinfo

## No icon

https://github.com/sindresorhus/refined-github (already default branch)
https://github.com/sindresorhus/refined-github/tree/master (already default branch)
https://github.com/sindresorhus/refined-github/blob/webpack-4/license (files aren't supported)
https://github.com/sindresorhus/refined-github/tree/1.20.1 (tags aren't supported)

## With icon

https://github.com/sindresorhus/refined-github/tree/webpack-4 (branch root)
https://github.com/sindresorhus/refined-github/tree/webpack-4/media (branch folder)

### CODE REVIEW

**Comment by hkdobrev** [comment]
Probably the house icon as in go back to home, the default view.

**Comment by bfred-it** [comment]
I thought about that but “home” feels like the root, but it could just be a sub folder of a different branch, still not “home”

**Comment by hkdobrev** [comment]
Well, yeah, but at the same, there are two big problems with the current icon:

It does not represent upstream. This is the icon for merging from the GitHub Flow (it's on my T-shirt 😂).
Even if there was an icon for upstream, it doesn't relate to changing the branch.

An alternative icon would be the commit icon as it's closest to "branch".

I would actually suggest just putting `HEAD` there instead of an icon.

**Comment by bfred-it** [comment]
> An alternative icon would be the commit icon as it's closest to "branch".

Yeah that wouldn't be bad. An alternative perhaps would be a `left` or `up` arrow, kinda like "go back to main". I think `HEAD` is actually just whatever you're looking at now, you're always on `HEAD`

**Comment by bfred-it** [comment]
screen shot 2018-02-25 at 13 55 35

How about a simple _back_ chevron?

**Comment by hkdobrev** [comment]
When looking at the upstream repository `refs/remotes/origin/HEAD` would be the main branch, not the upstream branch of your currently checked out branch locally.

---

:+1: for the chevron as well. However, it would move the branch selector from its default position when present if it's on the left side.

**Comment by bfred-it** [comment]
> it would move the branch selector from its default position when present if it's on the left side.

True, but I think it's not a big deal since the branch selector is very wide and the movement is of about 30px. What do you say? I think it's less nice on the right side pointing back to the current branch.

**Comment by bfred-it** [comment]
Temporary caching in 4bc8bdb enables it on files as well :) 

files

**Comment by bfred-it** [comment]
screen shot for readme

**Comment by shroudedcode** [comment]
When I'm on a forked repository and hover over the button a tooltip suggesting that it would link to the origin's respective branch appears. However, the link doesn't lead there. It leads to the branch on the current repository (often the same page).

```html
<a
  class="btn btn-sm tooltipped tooltipped-ne BtnGroup-item"
  href="/shroudedcode/refined-github"
  aria-label="Visit the default branch (sindresorhus:master)"
> ... </a>
```

That's confusing and not what's supposed to happen, *right*?

**Comment by bfred-it** [comment]
It’s-a-bug and I got you pal https://github.com/sindresorhus/refined-github/pull/1132

**Pull request merged**
