### PR TITLE
Fix `z-index` bug caused by `sticky-discussion-sidebar`

### LINKED ISSUE #2576: `z-index` problem when modal is opened in issue detail page
Hi,

I found a bug in issue detail page. Some elements appeared on the modal backdrop when the modal is opened.

I tested on Chrome(v78.0.3904.108) and Microsoft Edge Dev(v79.0.287.3).

**Sample Url**
`https://github.com/sindresorhus/refined-github/issues/1137`

**Screenshot**
image

### PR DESCRIPTION
**Pull request by yohanneshabte**
Closes #2576

# Test

https://github.com/sindresorhus/refined-github/issues/1137
**Check by opening the customize notifications menu on the right side**
#### Before
before
#### After
after

### CODE REVIEW

**Comment by fregante** [comment]
I'll be testing this PR for a few days

**Comment by yohanneshabte** [comment]
Okay thank you! I appreciate the quick response. Sorry for the mistake with the previous PR. I forgot to get the latest version first.

**Comment by fregante** [comment]
No worries Yohannes! Thank you for fixing bugs!

**Comment by yohanneshabte** [comment]
hi @fregante I have pushed a hot-fix for the particular problem with issue #2601. But instead of fixing these one element at a time, I wanted to ask you if there's an underlying cause for the z-index(where some backdrops appear to have a default z-index value of 1). I can't verify where the value change is coming from in the first place. Thanks!

**Comment by fregante** [comment]
I don't remember which rule exactly, but `sticky-discussion-sidebar` being sticky probably wraps the notification's overlay's `z-index` to the sidebar's stacking context, so it's only ever as high as the sidebar.

I honestly don't know why any of these elements in the discussion have any `z-index` at all. The value we should set is probably `z-index: auto`

**Comment by fregante** [comment]
I'll merge this for now. It seems to be working alright. Hopefully no new bugs. Thank you for the PR!

**Comment by fregante** [comment]
I found that the selector is too broad. `[class*='TimelineItem']` includes a lot of items that don't need `z-index: 0` at all, and adding it causes them to go over other features, like `quick-mention`'s tooltip:



I had to undo this PR for now, I hope to see a more specific selector in a new PR.

**Pull request merged**
