### PR TITLE
Avoid shortening of linkified code

### LINKED ISSUE #789: Replacing URLs with links in PR diff view creates confusion
Not sure if this is a bug or a feature but GitHub Redefined changed the `https://example.com/` into a `example.com` link on PR diff, which created a great amount of confusion when I was referencing the lack of `https` and trailing slash, linking to the line, which turned out to have both of these things, just not visible on my machine.

And if that is a feature, could we a) maybe disable it for diff's b) make it configurable?

Thanks!

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes #789

### CODE REVIEW

**Comment by Mange** [comment]
This is still happening for me in the latest version of the Firefox extension. Is this fix not shipped yet, or is it a regression?

**Comment by bfred-it** [comment]
Regression, if you're using the version from AMO and not a locally-installed one.

Can you post a link where you're seeing the issue + screenshot?

**Comment by Mange** [comment]
Cannot reproduce on a public repo. Maybe Firefox didn't update automatically before or something...

Sorry for raising the alarm. :sweat_smile:

**Comment by bfred-it** [comment]
No worries, it was actually a regression and it was fixed a few days after your report. #1145 Thank you!

**Pull request merged**
