### PR TITLE
Restore and extend url linkifier

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes https://github.com/sindresorhus/refined-github/issues/695 (oldest bug open)
Fixes https://github.com/sindresorhus/refined-github/issues/1499

Thanks to https://github.com/bfred-it/zip-text-nodes. Comments welcome on this package and its name too

# Test

URLs in diffs
https://github.com/Homebrew/homebrew-core/pull/18015/files

URLs in regular files
[/source/features/copy-markdown.js@`3f5fc48`#L45](
https://github.com/sindresorhus/refined-github/blob/3f5fc489e417d4f4a14da5ea423775e9ca9246fd/source/features/copy-markdown.js#L45)

URLs in PR files
https://github.com/sindresorhus/refined-github/pull/546/files#diff-36280fbf56b6409696e3d46d6b30118fR51

URLs in embedded code
https://github.com/sindresorhus/refined-github/blob/3f5fc489e417d4f4a14da5ea423775e9ca9246fd/source/features/copy-markdown.js#L45

Issue reference in file

[/source/features/sort-issues-by-update-time.tsx@`2ade9a8`#L18](
https://github.com/sindresorhus/refined-github/blob/2ade9a84b1894c7879fab9d3e2d045e876f941a6/source/features/sort-issues-by-update-time.tsx#L18)

Issue reference in embedded code

https://github.com/sindresorhus/refined-github/blob/2ade9a84b1894c7879fab9d3e2d045e876f941a6/source/features/sort-issues-by-update-time.tsx#L18

### CODE REVIEW

**Comment by sindresorhus** [comment]
Weird, I'm not getting anything linkified when running this PR locally.

**Comment by bfred-it** [comment]
Did you run npm install?

**Comment by sindresorhus** [comment]
Yup. I tried checking out the branch fresh, reinstalled node_modules, and then reloaded the extension. This is not linkified: https://github.com/sindresorhus/refined-github/pull/546/files#diff-36280fbf56b6409696e3d46d6b30118fR51

**Comment by bfred-it** [comment]
Classic! 

I had extracted the `for` loop from a function and left it with `return`. c746caf It works now.

**Comment by sindresorhus** [comment]
Still doesn't work for me.

**Comment by bfred-it** [comment]
The push must have failed. Flaky internet

**Pull request merged**
