### PR TITLE
Adjust `latest-tag-button`'s size

### PR DESCRIPTION
**Pull request by kidonng**
From https://github.com/sindresorhus/refined-github/pull/3353#issuecomment-659260733

Before: 

After:

### CODE REVIEW

**Comment by fregante** [comment]
The smaller size was on purpose

**Comment by kidonng** [comment]
This class exists (or more precisely, is added) in the feature's first commit (https://github.com/sindresorhus/refined-github/pull/1049/files#diff-041e2c7f28122df0efbf5dbb6ee3c2adR22), in which I don't see any reason except matching GitHub's style.

**Comment by fregante** [comment]
https://github.com/sindresorhus/refined-github/pull/3221 by @FloEdelmann, in the very first post

**Comment by kidonng** [comment]
Missed that one. But that PR is made when design update is in progress, do you still think it looks fine with different button size?

image
image

image
image

**Comment by fregante** [comment]
> do you still think it looks fine with different button size?

I do; you can see how the buttons also become wider and the space on that line might be limited already

**Comment by kidonng** [comment]
I will override it with the following style:

```css
/* https://github.com/sindresorhus/refined-github/pull/3356 */
#branch-select-menu ~ .btn,
#branch-select-menu + .BtnGroup .btn,
#branch-select-menu ~ .flex-self-center .btn {
  padding: 5px 16px;
  font-size: 14px;
}

#branch-select-menu ~ .btn .octicon,
#branch-select-menu + .BtnGroup .octicon,
#branch-select-menu ~ .flex-self-center .octicon {
  vertical-align: text-bottom;
}
```

**Pull request closed without merging**
