### PR TITLE
Move Issue/PR labels below the title

### LINKED ISSUE #523: Right-aligned issue labels
Right-aligned issue labels would improve visual grepping as they would be horizontally aligned, unlike the staggered pattern we have now.

github-issue-labels

The proposed placement would be to the left of where the Assignee is, regardless of if there is any. Milestones and Author appear on the line below so do not interfere with this proposition. 

github-issue-labels-right-aligned

When the labels no longer fit due to issue title length, they should appear on a new line as the current behaviour on GitHub, just right-aligned from the same point as in the above image.

Cheers for the awesome extension everyone!

### PR DESCRIPTION
**Pull request by bfred-it**
Replaces and closes #551
Closes #523

# Issues

issues

# PRs

PRs

### CODE REVIEW

**Comment by bfred-it** [comment]
Related: on mobile they are below the details line, perhaps we can match that.

**Comment by sindresorhus** [comment]
I'm not against it, but will definitely take some getting used to.

Maybe we could reduce the font-size by one pixel and reduce the padding slightly so the labels are not fighting with the title for attention as much.

**Comment by bfred-it** [comment]
smaller labels

**Comment by bfred-it** [comment]
This might be better:

labels below details


Also matches mobile:

mobile

**Comment by sindresorhus** [comment]
That looks much better.

**Comment by lukaszklis** [comment]
Looks awesome!

**Comment by hkdobrev** [comment]
Should we just match mobile in every way? Similar to Refined Twitter and Refined Wikipedia, the mobile interface is much more clear. I'm not saying to remove the extra information the desktop has, but probably work on the whitespace, link styles etc.

**Comment by bfred-it** [comment]
@hkdobrev sure if you have specific suggestions it's best to make a PR to visualize them.

I'd be wary of matching GH's mobile 1:1 since it's actually just outdated.

**Comment by sindresorhus** [comment]
@bfred-it Can you add it to the feature section in the readme?

**Comment by bfred-it** [comment]
Clean screenshot:

refined github lower labels

**Comment by jmeas** [comment]
Does anyone else find that this change makes it more difficult to skim a long list of issues? The colors distract from the issue title, which is usually what I'm looking for.

Maybe it's something I just need to get used to, but I figured I'd leave a comment in case others felt similarly.

**Comment by fregante** [comment]
@jamesplease If you still feel that way you can now disable the feature #2872

**Pull request merged**
