### PR TITLE
Remove your repositories link in dropdown

### LINKED ISSUE #1446: GitHub now has a Your Repositories link in your profile dropdown
https://blog.github.com/changelog/2018-07-25-access-your-repositories-straight-from-the-profile-dropdown/

### PR DESCRIPTION
**Pull request by vinkla**
This has been implemented by GitHub. Fixes #1446.

### CODE REVIEW

**Comment by yakov116** [comment]
All these should have migration added to them See #1330

**Comment by vinkla** [comment]
Okay, I'll look into adding migrations. Should we solve this by simply copy/paste the line below but with other feature names?
https://github.com/sindresorhus/refined-github/blob/a953ed4948e4dd5a73fc94413a1368b4b1c3665a/source/background.js#L17

**Comment by sindresorhus** [comment]
> Should we implement the migrations by simply copy/pasting the line below and update the feature names?

👍

**Comment by vinkla** [comment]
I've pushed a migration update.

**Pull request merged**
