### PR TITLE
Remove "issue suggestions" feature

### LINKED ISSUE #1610: Remove "related issues" feature
See https://blog.github.com/changelog/2018-11-05-related-issues/

### PR DESCRIPTION
**Pull request by nesl247**
Issue suggestions were added by GitHub here: https://blog.github.com/changelog/2018-11-05-related-issues/

Closes #1610 

I did not test this out, but I didn't see anything else when searching the codebase.

### CODE REVIEW

**Comment by busches** [comment]
You need to add a line similiar to this, https://github.com/sindresorhus/refined-github/commit/ba34c09eaac05d54d5ff837edd4fbf504378a9a3#diff-614c534aa9d039a36795fbe15928c31cR18, to remove it from anyone who has it disabled.

**Comment by nesl247** [comment]
Oops, thanks.

**Comment by sindresorhus** [comment]
Travis is failing: https://travis-ci.org/sindresorhus/refined-github/builds/451596970?utm_source=github_status&utm_medium=notification

**Comment by sindresorhus** [comment]
👌

**Pull request merged**
