### PR TITLE
Add `useful-forks` feature

### LINKED ISSUE #3682: Add a link to `useful-forks`
The forks list page should have a button/link to a service that lists useful forks for the current project.

Feature location: https://github.com/sindresorhus/refined-github/network/members
Button URL: https://useful-forks.github.io?repository=sindresorhus/refined-github

This is a super easy feature, it just needs to create a link and position it somewhere on that page.

The button URL hasn't been implemented by https://github.com/useful-forks yet.

---

_Simplified request from https://github.com/sindresorhus/refined-github/issues/3638_

### PR DESCRIPTION
**Pull request by payne911**
1. LINKED ISSUES:
   fixes #3682

2. TEST URLS:
   * https://github.com/payne911/PieMenu/network
   * https://github.com/payne911/PieMenu/network/members

3. SCREENSHOT:
   image

   image

### CODE REVIEW

**Comment by payne911** [comment]
I wasn't sure about what I should do with the `package-lock.json` file, though.

**Comment by yakov116** [comment]
> I wasn't sure about what I should do with the `package-lock.json` file, though.

Don't commit it

**Comment by payne911** [comment]
> Don't commit it

How do you suggest I remove that file from the PR ?

**Comment by yakov116** [comment]
I think
```git
git restore --source main~1 package-lock.json
```

**Comment by payne911** [comment]
`git restore` isn't a command.

I tried `git checkout origin/master -- package-lock.json`, but the generated diff modified the entire file.

I don't want to push a diff on that file, I want my modification to be removed from this PR.

**Comment by yakov116** [comment]
Why did you close? What version of git are you on?

**Comment by payne911** [comment]
> Why did you close? What version of git are you on?

I tried to fix this, but ended up screwing up and pointing to one commit too far back in the history when doing a soft reset. At that point, due to my limited knowledge of git, I thought it'd be much easier to start a new PR from a new branch with the cherry picked changes I needed.

See #3955

**Pull request closed without merging**
