### PR TITLE
Add GitHub Issue Link Status to readme

### LINKED ISSUE #202: Show status of linked-to PR/Issue
If there is a link to another issue/PR, I should somehow be able to identify it's status (green/red/purple color coding, or inline a badge).

### PR DESCRIPTION
**Pull request by bfred-it**
Closes #202 

screenshot

### CODE REVIEW

**Comment by bfred-it** [comment]
Thank you!

**Comment by bfred-it** [comment]
@hkdobrev you're missing out though! It's a game changer for me (but I may be biased)

screen shot 2017-12-20 at 16 04 28
screen shot 2017-12-20 at 16 04 23

**Comment by hkdobrev** [comment]
I'd like to not see the icons. Or to see them only in the GitHub tooltip showing the title. I'd think more about it and post on the repo.

**Comment by bfred-it** [comment]
Options were considered. For now they can be hidden with `.ILS svg {display: none}`

**Pull request merged**
