### PR TITLE
Drop `show-followers-you-know` feature

### LINKED ISSUE #3345: `show-followers-you-know` no longer works
https://github.com/sindresorhus/refined-github/blob/d4e158776dca70a0bd339872a5b005bf5382aceb/source/features/show-followers-you-know.tsx#L10

That url no longer works

### PR DESCRIPTION
**Pull request by yakov116**
1. LINKED ISSUES:
   Closes #3345 

2. TEST URLS:
 None

3. SCREENSHOT:
None

Not sure if/how this should be put in "Previously part of Refined GitHub"

### CODE REVIEW

**Comment by notlmn** [comment]
Are we still adding migrations for dropped features?

**Comment by yakov116** [comment]
> Are we still adding migrations for dropped features?

What kind of migration?

**Comment by fregante** [comment]
@notlmn they're dropped automatically by the `removeUnused` migration

**Review by fregante — APPROVED** [review]

**Comment by notlmn** [comment]
> @notlmn they're dropped automatically by the `removeUnused` migration

Oh, totally forgot about this 😀

**Pull request merged**
