### PR TITLE
Fix #352 - Hide duplicate header on issues page

### LINKED ISSUE #352: duplicated #js-repo-pjax-container for empty project on Issues Page
Something is happening on the issues page for empty projects.

To reproduce this behaviour, follow these steps:

1. Create a new repository without readme
2. Go to Issues page

screen shot 2017-02-08 at 12 42 52 pm

### PR DESCRIPTION
**Pull request by paulmolluzzo**
Fixed #352.

This makes the `isEmpty` test a boolean instead of a `0`.

### CODE REVIEW

**Comment by paulmolluzzo** [comment]
My bad! :frowning_face: 

The first attempt actually reversed the logic, so that's way wrong. :man_facepalming: 

Instead I changed the selector we're looking for in the returned `document` to `.js-git-clone-help-container`. This seems to be the element that is present if you still haven't pushed anything to the repo.

You can test this here: https://github.com/paulmolluzzo/testing/issues. If you checkout the PR branch and then `console.log(isEmpty)` that page will log a `1`. This repo should log a `0`.

If someone has other input it's welcome. I'm guessing there are some other scenarios I'm not addressing.

**Comment by sindresorhus** [comment]
I still get the duplicate header on https://github.com/paulmolluzzo/testing/issues

**Comment by paulmolluzzo** [comment]
> I still get the duplicate header on https://github.com/paulmolluzzo/testing/issues

@sindresorhus Fixed. I used an incognito window to reproduce that scenario.

**Comment by sindresorhus** [comment]
👍

**Comment by leocaseiro** [comment]
Thanks!

**Pull request merged**
