### PR TITLE
Differentiate merge commits from regular commits

### LINKED ISSUE #94: Make merge commits less noisy
This looks very noisy:

screen shot 2016-03-22 at 21 15 18

Maybe we can fade it out or something? Any other suggestions?

### PR DESCRIPTION
**Pull request by hkdobrev**
Closes #94

@sindresorhus I've made this PR to close #94, but seeing this live I am not sure I need/want this. Merge commits are important to see in the commits list marking a point when something was merged (or released if a web app is deployed when pushed to master).

Faded out merge commits in commit list

### CODE REVIEW

**Comment by sindresorhus** [comment]
Sure, that's why we're not removing them, but instead making them less visible to reduce the noise.

@paulmolluzzo Thoughts?

**Comment by paulmolluzzo** [comment]
This looks pretty good. If I nitpick I'd make the `opacity` on the avatars `0.8`, but not a deal breaker.

I think merges are critical to see, and the way @hkdobrev did it doesn't take them out of the picture entirely or make them _too_ hard to find. I think this is a good balance. If I end up hating it I'll just use a different version locally anyway :smile:.

**Comment by sindresorhus** [comment]
I'm open to other suggestions too. I just don't want merge commits to be there when looking for a commit. It's also weird that merge commits are not decorated differently by GitHub somehow.

-

Just a quick braindump to start a conversation:

screen shot 2016-03-24 at 21 38 36

**Comment by paulmolluzzo** [comment]
What if we append the merge icon to the left of the row? Or replace the avatar with the icon?

### Default but put the merge icon in the back and overlay avatar:
avatar-over-icon

### Keep all of @hkdobrev's opacity/color chages, put the merge icon in the back, overlay avatar, shift it over 10px right to seem "nested":
avatar-over-icon-padded-opacity

**Comment by sindresorhus** [comment]
I like! 😬

Would it make sense to reduce the font size too? As it's more of a "connector" than a real commit.

**Comment by hkdobrev** [comment]
I don't like nesting it as it seems it is nested below the commit above, which is far from the truth.

I really like the merge icon with the avatar!

I'd suggest not using the fading colours just the merge icon and not nesting at all. I can live with reducing font size as well.

**Comment by paulmolluzzo** [comment]
> I'd suggest not using the fading colours just the merge icon and not nesting at all. I can live with reducing font size as well.

Works for me.

**Comment by hkdobrev** [comment]
I've updated with using the same style as committer-author avatar style GitHub uses (even took advantage of their CSS) as @paulmolluzzo suggested. Let me know if you think I should remove the font-size change as well.

**Comment by paulmolluzzo** [comment]
This looks good to me. :+1:

**Comment by sindresorhus** [comment]
If we're going to change the font size, I think we should do it on the other text in the merge commit too. Like author and date.

**Comment by hkdobrev** [comment]
@sindresorhus Hmm, it seems I've mixed that up when rebasing. I'll fix that.

**Comment by hkdobrev** [comment]
Updated.

**Comment by sindresorhus** [comment]
Woot 🎉 Nice work on this @hkdobrev :)

**Pull request closed without merging**
