### PR TITLE
Add `esc-to-deselect-line` feature

### PR DESCRIPTION
**Pull request by bfred-it**
Closes https://github.com/sindresorhus/refined-github/issues/1590

# Test

[source/options.html#L1-L2](https://github.com/sindresorhus/refined-github/blob/a759d4346e5ac4a98c9fdb2734cdae625de0f309/source/options.html#L1-L2)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Shouldn't it work on PR diffs too?

Example: https://github.com/sindresorhus/refined-github/pull/1878/files#diff-7bb46402a79dd0637618b43751bcc733R66

**Comment by bfred-it** [comment]
Indeed. Currently it only checks for `#L` but that is `#diff-`

**Comment by sindresorhus** [comment]
You can detect it though. Notice how line selections ends in `R23` where 23 is the line number, while file selections don't.

**Comment by tomirons** [comment]
This doesn't work on Chrome for MacOS 74.0.3729.169. I tried viewing a commit and a specific file, neither of them worked.

Any tips for Mac users?

**Comment by bfred-it** [comment]
It works for me in Firefox and Chrome.

1. Visit https://github.com/sindresorhus/refined-github/blob/a759d4346e5ac4a98c9fdb2734cdae625de0f309/source/options.html#L1-L2
2. Press ESC
3. Notice the 2 selected lines becoming unselected

**Comment by tomirons** [comment]
Unfortunately that still doesn't work. I even tried key combinations like _cmd + esc_, _option + esc_, _control + esc_, and _fn + esc_.

**Comment by afolarin** [comment]
`Esc` not working for me on Chrome 
`Google Chrome	78.0.3904.70 (Official Build) (64-bit)`

**Comment by fregante** [comment]
Looks like a bug, can you open an issue?

**Pull request merged**
