### PR TITLE
hug-circles: init

### PR DESCRIPTION
**Pull request by Kreyren**
**WARNING:** The master branch doesn't build for me and i wasn't motivated enough to resolve it so this is a blind code.

<details>
<summary>Build log</summary>

```console
kreyren@leonid:~/Repositories/refined-github$ npm install
npm WARN eslint-config-xo@0.30.0 requires a peer of eslint@>=7 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-xo-react@0.23.0 requires a peer of eslint@>=6 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-xo-typescript@0.31.0 requires a peer of eslint@>=6.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-ava@10.3.0 requires a peer of eslint@^6.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-unicorn@20.1.0 requires a peer of eslint@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-template-visitor@2.0.0 requires a peer of eslint@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/addons-linter/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 1917 packages in 13.815s

130 packages are looking for funding
  run `npm fund` for details

found 5 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
kreyren@leonid:~/Repositories/refined-github$ npm run watch

> @ watch /home/kreyren/Repositories/refined-github
> run-p watch:* --continue-on-error


> @ watch:typescript /home/kreyren/Repositories/refined-github
> tsc --noEmit --watch --preserveWatchOutput


> @ watch:webpack /home/kreyren/Repositories/refined-github
> webpack --mode=development --watch

[12:59:42 AM] Starting compilation in watch mode...


/home/kreyren/Repositories/refined-github/webpack.config.ts:51
entry: Object.fromEntries([
               ^
TypeError: Object.fromEntries is not a function
    at Object.<anonymous> (/home/kreyren/Repositories/refined-github/webpack.config.ts:51:16)
    at Module._compile (/home/kreyren/Repositories/refined-github/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module.m._compile (/home/kreyren/Repositories/refined-github/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/kreyren/Repositories/refined-github/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/kreyren/Repositories/refined-github/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/home/kreyren/Repositories/refined-github/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/home/kreyren/Repositories/refined-github/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /home/kreyren/Repositories/refined-github/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/kreyren/Repositories/refined-github/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at yargs.parse (/home/kreyren/Repositories/refined-github/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/home/kreyren/Repositories/refined-github/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/kreyren/Repositories/refined-github/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/kreyren/Repositories/refined-github/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/kreyren/Repositories/refined-github/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch:webpack: `webpack --mode=development --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ watch:webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kreyren/.npm/_logs/2020-06-29T22_59_47_133Z-debug.log
[12:59:54 AM] Found 0 errors. Watching for file changes.
```

</details>

### CODE REVIEW

**Comment by Kreyren** [comment]
Made a fast graphics for this

hug-circles

**Comment by busches** [comment]
We generally don't go against the design without a reason, other than we like the old way. This is fine as a custom rule you apply in your CSS.

**Comment by Kreyren** [comment]
@busches custom rules may get overwhelming and this way it's easier to manage with clear development abstract.

Or like it can be opt-in feature..

**Comment by notlmn** [comment]
> Or like it can be opt-in feature..

From https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606765382:

> ## 2\. It makes sense as a default for everyone.
> 
> "Disabled by default" means most people don't need it, so it doesn't belong to Refined GitHub. In that case, it's best to keep it as a standalone userscript or extension.

**Pull request closed without merging**
