### PR TITLE
Use full width of the page

### LINKED ISSUE #1171: Fill up the width of the page
Today when looking at files, GitHub limits the width to 980px. My screen is wide and there's lots of wasted space, which is annoying when I have files with long lines.

Current:
Current

Suggested:
Suggested

### PR DESCRIPTION
**Pull request by adamzr**
Fixes #1171

### CODE REVIEW

**Comment by sindresorhus** [comment]
Sorry, this is way too opinionated for Refined GitHub and it doesn't look very good either. Fill up the extra space by having two windows side-by-side ;)

Check out:
- https://github.com/xthexder/wide-github
- https://github.com/sqren/github-widescreen
- https://github.com/mdo/github-wide

**Comment by bfred-it** [comment]
> way too opinionated for Refined GitHub

😅

**Comment by busches** [comment]
I thought this sounded amazing, then I tried it and I had to uninstall it. I'll side with Sindre.

**Comment by adamzr** [comment]
No problem. Thanks for considering it.

And thanks @sindresorhus for those other options, I'll try them.

Maybe 90% is not the right width for everyone, but I still think there are better width options than the one they chose. Maybe we could create multiple media queries for different size screens and choose a reasonable size for each width?

**Comment by sindresorhus** [comment]
I think what GitHub has now is a good width. Whitespace can be important for usability. You don't always need to fill every empty space. And margins are important for readability. Reading text on something wider than 1000px becomes uncomfortable. They do use the full width when it matters, for diffs and merge conflict resolving.

**Comment by sindresorhus** [comment]
@bfred-it Would it make sense for us to just provide a text box in the settings where people can add their own CSS? Yes, they could use Stylish/etc, but it might be too much just to tweak a couple of things.

**Comment by bfred-it** [comment]
Closing for unpopularity. 

@sindresorhus 👌

**Comment by andybergon** [comment]
You can use [`github-wide css`](https://github.com/mdo/github-wide/blob/master/github-wide.css) in the `refined-github` CSS box. 

I agree that it is pretty ugly to have a so stretched UI but just making that enabled by a button and not by default can be interesting as sometimes you have to read a code with lines longer than 120 characters.

**Comment by jtagcat** [comment]
Necro

To add to the list of alternatives, https://github.com/fabiocchetti/wide-github

On a Thinkpad X230, with a small screen (and HD screens, FHD mod available). In this context, this is accessibility. It's a bit uglier, but more usable.

Does ref gh only add features, that are defaulted to enabled, or is there room for disabled-by-default changes as well?

Why not 'just use' the other user scripts and add-ons? Trust,… that it doesn't change over time. Without inspecting, initial risk is lower as well. Meaningless performance arguments (when running god damn too many add-ons) could be made as well.

**Comment by yakov116** [comment]
> Does ref gh only add features, that are defaulted to enabled, or is there room for disabled-by-default changes as well?

No see https://github.com/sindresorhus/refined-github/issues/2960

**Pull request closed without merging**
