### PR TITLE
replace indent function with bahave.js

### PR DESCRIPTION
**Pull request by blackjid**
Adds [Behave.js](http://jakiestfu.github.io/Behave.js) library to add ide like features in the comments textareas.

Some of the issues discussed in #164 don't apply to this implementation.
It supports fencing, so the added functionality only works inside ``` fences.
Also has unindent with shift tab, auto close (), {}, [], and some other extra features...

As it only functions inside the fencing, at the end of your comment you can just do tab + enter to send the message, as usual.

### CODE REVIEW

**Comment by DrewML** [comment]
I like the idea a lot, and I would personally benefit from this, but I'm pretty concerned about the lack of tests that exist for that library. We don't necessarily have a huge guarantee that it's going to work well in all scenarios for everyone, and the comment area is a really important thing for us not to break.

Not necessarily saying we shouldn't do it, but bringing it up for discussion.

**Comment by sindresorhus** [comment]
I'm a bit concerned about this: https://github.com/jakiestfu/Behave.js/issues/11

**Comment by DrewML** [comment]
This one might be a problem as well: https://github.com/jakiestfu/Behave.js/issues/18

**Comment by jamestalmage** [comment]
Have you considered https://codemirror.net/ instead?

**Comment by DrewML** [comment]
@jamestalmage Nice! I didn't realize CodeMirror had a markdown mode. I'm personally in favor of trying it out.

**Comment by jamestalmage** [comment]
Even has GFM: https://codemirror.net/mode/gfm/index.html

**Comment by blackjid** [comment]
Hey I added some initial codemirror implementation in https://github.com/sindresorhus/refined-github/pull/197

**Comment by blackjid** [comment]
I think we all agree that this is not the way to go. Right?

**Pull request closed without merging**
