### PR TITLE
Add a task list feature for PR code review

### PR DESCRIPTION
**Pull request by ahmadassaf**
This idea came to me when I wanted to address the comments of some other PR I have here ( I will get to it @bfred-it :)). Sometimes one can have lots of comments and wants to tackle those in some sort of priority that one decide. This PR adds a task-list kind of behaviour by:

 - Adds a little check mark next to the comment header
 - Clicking on the check mark will mark the task as "completed" and the comment body will collapse
 - You can re-open the task by clicking on the check mark again
 - The task list persists and is stored in the localStorage
 - The approach to make sure the cache works well by creating a unique hash for each task that included the comment url (which will contain in its turn the repo owner, repo name, filename and a commit hash) and I append to that the PR number and an index for the comment as you might have multiple comments on the same file for the same commit hash in the same PR)

clzx4xeh3i

### Caveats (need help in those)
 - The task list will appear also in PRs that the user did not open. This can be done easily by getting the username of the person who opened the PR and comparing it to the current username. I can implement that but asking of best practice here to get the current username.
 - When there are mot comments that will be ajaxed in they will not have the checkmark added. I have tried with various `observeEl` but with no luck

ejwrm8vcbw

### CODE REVIEW

**Comment by ahmadassaf** [comment]
ah thanks @bfred-it ... need to add this to my `.gitignore`

**Comment by bfred-it** [comment]
I don't think this is particularly useful nor it should be part of RGH. Outdated comments are automatically collapsed once you push your commits.

In addition, GitHub has its own comment resolution; in fact I thought this PR was this feature: https://github.com/sindresorhus/refined-github/issues/1268

**Comment by ahmadassaf** [comment]
I will look into #1268. This is different @bfred-it. This is not a comment but a code review comment that you cannot resolve (or at least as a contributor I cannot). I personally find it useful when I was trying to address all of the comments you added to one of my PRs I was lost to what I already fixed and what I still did not. So if i look into those comments as a task list then I was able to easily track the progress like that.

**Comment by bfred-it** [comment]
> If you look into the code, this ignores outdated comments .. only for new ones that are still active.

Yeah, active comments can be closed by pushing code

**Comment by ahmadassaf** [comment]
exactly .. so since you dont want to push code for every little fix, this can manage the flow. Again, if this is not seen as a useful thing will be happy to keep it in my local fork

**Comment by tallen1983** [comment]
FWIW this type of feature is present in a lot of code review tools (Gerrit for example). Comments could be just a comment, or it could be a suggestion, or it could be a bug. All 3 of them are treated exactly the same in GitHub which is super annoying. Why assume every comment is a bug? Lets say there are 25 comments on a PR but only 10 of them are things I need to fix/change. After pushing my fixes I now need to go through at least 15 uncollapsed comments to make sure none of them needed changes. Another annoyance is that the change to fix a comment might come a line or two before/after the actual comment. Then the comment doesn't collapse because that line didn't change. Again, I now have to inspect the review to make sure I did actually fix it. After 2-3 review cycles on a PR this can get tiresome.
Gerrit and other tools do this much nicer in that the reviewer can mark things as bugs or not. The author can then see the list of bugs that need addressed and very easily knock them off one-by-one. Gerrit even warns you if you try to submit something with bugs still open.

**Comment by bfred-it** [comment]
> Comments could be just a comment, or it could be a suggestion, or it could be a bug. All 3 of them are treated exactly the same in GitHub which is super annoying

Not if you actually use reviews. Reviews can be left by anyone and can be marked as resolved by maintainers.

**Comment by bfred-it** [comment]
> so since you dont want to push code for every little fix

Why wouldn't you want to do that? I suggest: 

1. Read all reviews in order
2. Fix or respond to each as you go
3. Push what you have

At the end of this pass, what you fixed will automatically collapse and everything else stays open while the discussion continues. Once the reviewer considers it _done_ they will be able to cancel the review or approve it.

Hiding an _open_ comment just on your end doesn't solve it if the reviewer still thinks it needs work.

**Comment by lizzyu4ia** [comment]
You guys have my brain going in a billion directions at this point. I'm a beginner... I think its a great idea. Instead of arguing about codes can someone plz just guide me upon where to begin? Pretty please I cant even seem to create a domain on the hub...followed all orders...Simplicities at Kellahs....

**Comment by lizzyu4ia** [comment]
P.s. I'm not a bug...just learning...also it seems as though all or most of my java or jsan are deleted and it coukd be a huge problem? Im not sure...no cached data..  .

**Comment by refack** [comment]
FTR GitHub now has ["Resolve Conversation"](https://help.github.com/articles/about-pull-request-reviews/#resolving-conversations) which pretty much solves this use-case.

**Comment by ahmadassaf** [comment]
> FTR as of [2018-8-31](https://blog.github.com/changelog/2018-08-31-resolvable-conversations/) GitHub has ["Resolve Conversation"](https://help.github.com/articles/about-pull-request-reviews/#resolving-conversations) which pretty much solves this use-case.

at least I know there was a merit for the idea :) Thank for the pointer @refack

**Pull request closed without merging**
