### PR TITLE
Add `.prettierignore` file to disable "prettier on save" feature of every editor

### PR DESCRIPTION
**Pull request by darkred**
Re https://github.com/sindresorhus/refined-github/issues/4008#issuecomment-894761663 :

> * [ ]  Add `.prettierignore` file to disable "prettier on save" feature of every editor: [prettier.io/docs/en/ignore.html](https://prettier.io/docs/en/ignore.html)
>
> The content would probably be just `*.*` but it needs to be tested

## Test URLs
N/A

## Screenshot
N/A

## Notes for reviewers

I tested it as follows:
Installed Prettier package globally (`npm install -g prettier`), and installed [Prettier - Code Formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) extension.
Then I set Prettier as 'Default Formatter' and 'Format on Save' (below are the respective VSCode settings):
```
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
```

Then I opened various RG files (.ts, .tsx, .json) in any path depth, and just pressed save:
with the addition of `.prettierignore` the files are are no longer formatted by Prettier on save.

&nbsp;
Also:
- `.prettierignore` uses [gitignore syntax](https://git-scm.com/docs/gitignore#_pattern_format)
- Related StackOverflow answer regarding `**`: [Gitignore double star pattern does not work](https://stackoverflow.com/a/30333570)

### CODE REVIEW

**Comment by fregante** [comment]
@sindresorhus I asked for this change because I don't want to keep commenting "disable prettier plz"

**Review by fregante — APPROVED** [review]
@darkred thanks for testing it and documenting that

**Review by sindresorhus — APPROVED** [review]

**Comment by yakov116** [comment]
@fregante this needs a meta title

**Comment by fregante** [comment]
I literally opened the merge box and I was about to merge as is 😂

**Pull request merged**
