### PR TITLE
Add watch:chrome

### PR DESCRIPTION
**Pull request by yakov116**
web-ext added this option.

@fregante is there a simple way to set a secret-key to add the api key. Otherwise its a pain since every time you relaunch you need to set api key again
<!--

Thanks for contributing! 🍄

1. LINKED ISSUES:
   Does this PR close/fix an existing issue? Write something like `Closes #10`

2. TEST URLS:
   Add some test URLs

3. SCREENSHOT:
   Add a screenshot here if your PR makes visual changes

### CODE REVIEW

**Comment by fregante** [comment]
> Otherwise its a pain

Yep, that's why I don't use these scripts. The alternative is to use the flag to reuse your current profile instead of creating a new one, but it doesn't work reliably

**Comment by yakov116** [comment]
>but it doesn't work reliably

Only works if you shut chrome entirely. any way to set the api key via a script?

**Comment by yakov116** [comment]
>but it doesn't work reliably

Only works if you shut chrome entirely. any way to set the api key via a script?

**Comment by fregante** [comment]
> any way to set the api key via a script?

Not that I know of

**Comment by yakov116** [comment]
Going to close this then. I see no value.

**Pull request closed without merging**
