### PR TITLE
Hide PR/Issue rename events

### PR DESCRIPTION
**Pull request by bfred-it**
While we wait for #615, perhaps we can agree that the "title rename" events are just noise.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Sometimes it can be useful though when the direction of a PR changes. But you're right, most often it's just noise.

**Comment by sindresorhus** [comment]
I'm ok with this. Can you fix the merge conflict and merge?

**Comment by anntzer** [comment]
Could this be made configurable?  Sometimes (e.g.) it turns out that the issue of the OP is actually revealing an underlying "unrelated" bug, in which case the original title is relevant to go with the original post, even though the issue may have been related to the underlying bug.

**Comment by sindresorhus** [comment]
@anntzer Yes, I've encountered that too, but very rarely. We only make things configurable as a last resort, but I think this will be fixed when we (or someone) implements https://github.com/sindresorhus/refined-github/issues/615.

**Comment by vanniktech** [comment]
It would be nice to have some indicator showing that the Issue / PR title has been renamed as you still might want to see what the initial name was and also that it has changed.

**Comment by aspiers** [comment]
Unfortunately this feature is a problem for me - I really need to see the renames in the majority of cases.  It also violates the Principle of Least Surprise, leading to #1471.

**Comment by yakov116** [comment]
as @jdreesen replied in the other issue:

>You can show them again by adding this as Custom CSS in the plugin options:

```css
.discussion-item-renamed {
    display: block !important;
}
```

**Pull request merged**
