### PR TITLE
Meta: Update dependencies and simplify build

### PR DESCRIPTION
**Pull request by fregante**
- Update Webpack to v5 (+ loaders)
- Replace `ts-loader` with [`esbuild-loader`](https://github.com/privatenumber/esbuild-loader) to save a couple of seconds of build time
- Keep static files to `./distribution` instead of using Webpack to copy them (reduces config)
- Drop old unused dependencies
- Lint `DefinePlugin` 

Overall, the config file is 46 lines shorter (-27%) :cake:

Next, maybe:

- [ ] Update dependencies again later to avoid some deprecation notices
- [x] Find out why it still takes 11 seconds to build. Edit: it appears to wait idly for a few seconds for no reason:

👆 made with https://webpack.js.org/plugins/profiling-plugin/

### CODE REVIEW

**Comment by yakov116** [comment]
🎉

**Comment by yakov116** [comment]
Is this TODO fixable?

https://github.com/sindresorhus/refined-github/blob/a121cc8b54c1fa984659f6a0e61f1e0ea89ff348/tsconfig.json#L4

**Comment by fregante** [comment]
> Is this TODO fixable?

Indeed. This also saves a lot of bytes 😛 

```
           options.js ⏤  30.9 kB (-21 B)
    refined-github.js ⏤  98.9 kB (-648 B)
```

**Comment by yakov116** [comment]
The build size should be much smaller now

**Comment by yakov116** [comment]
https://github.com/fregante/delegate-it/releases/tag/v2.0.1

**Comment by fregante** [comment]
> is this not part of this pr

It's unrelated to the build. It can be done separately. Not urgent either 😄

**Comment by yakov116** [comment]
Resolve conflicts stopped working
https://github.com/sindresorhus/refined-github/pull/3596/conflicts

**Comment by fregante** [comment]
Heh, I thought about testing it and then forgot while I was looking for conflicts. Fixed in the latest commit

**Comment by yakov116** [comment]
`[webpack-cli] SyntaxError: Unexpected token '.'`

I am unable to build 😢 not sure whats wrong!

**Comment by fregante** [comment]
GitHub Actions passed. Npm install and use node 14

**Comment by yakov116** [comment]
> use node 14

That worked thanks

**Pull request merged**
