### PR TITLE
Remove `hide useless comments` From Pr's

### LINKED ISSUE #1543: Do not hide PR reviews verdict (hide-useless-comments)
It seems the new `hide-useless-comments` feature is too gourmand as it also hides the PR review verdict completely when it has only a reaction comment.

capture d ecran 2018-09-20 a 18 18 12

<hr>

capture d ecran 2018-09-20 a 18 18 20

Should the PR verdict still be visible by only hiding the comment below ?

Thanks !

### PR DESCRIPTION
**Pull request by yakov116**
Closes #1543 
As per https://github.com/sindresorhus/refined-github/issues/1543#issuecomment-423378536

### CODE REVIEW

**Comment by bfred-it** [comment]
I think @hkdobrev mentioned that PRs get useless comments too so it shouldn’t be disabled that.

**Comment by Annastaciahubbard** [comment]
There was not a conflict with this base

**Comment by Annastaciahubbard** [comment]
I see, I am good with that – merge this one.   Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by bfred-it** [comment]
@sindreshorhus @bushes

**Comment by mobilutz** [comment]
Yes, please merge this. It also hides PR approval comments with only +1 or similar ...
Thanks for the awesome plugin!!!

**Comment by yakov116** [comment]
@hkdobrev can you merge this?

**Comment by busches** [comment]
Thanks for the PR, there was a lot of feedback on this!

**Pull request merged**
