### PR TITLE
used input type="password" for personalToken

### PR DESCRIPTION
**Pull request by trivikr**
# Test
* Confirmed that `npm build` is successful and tested unpacked extension in browser
* `npm test` is successful

# Screenshots
* Before 
input-type-text
* After 
input-type-password

### CODE REVIEW

**Comment by yakov116** [comment]
@trivikr 	see #1374 and https://github.com/sindresorhus/refined-github/commit/a60638ad250c067e9f5753e3e82906a44eb6099b
It gives a false sense of security (since its plain text)

However the size show be made to 40% now

**Comment by bfred-it** [comment]
As @yakov116 said, but thanks for the PR 🙂

**Comment by bfred-it** [comment]
@trivikr if that's your real token in the screenshot I suggest changing it because the missing characters are easily guessable

**Comment by trivikr** [comment]
@bfred-it I'd created and destroyed a token just for the screenshot

**Pull request closed without merging**
