### PR TITLE
Allow selecting files bottom to top in  `batch-mark-files-as-viewed`

### LINKED ISSUE #3549: `batch-mark-files-as-viewed` only works in one direction
1. Visit https://github.com/sindresorhus/refined-github/pull/3540/files
2. Click "Viewed" on the 1st file
3. Shift-click "Viewed" on the 3rd file

This works, 3 files are selected.

4. Remove all "Viewed" marks
4. Click "Viewed" on the **3rd file**
4. Shift-click "Viewed" on the **1st file**

This doesn't work. Only 1 or 2 files are selected, not 3 as expected.

Whoever wrote this feature was a real dummy. Let me see who did...

```
$ git blame source/features/batch-mark-files-as-viewed.tsx
Fregante (4):
      Add `batch-mark-files-as-viewed` feature (#3007)
      Extract page-detect.ts into `github-url-detection` (#3062)
      Lint (#3072)
      Meta: Reorganize utility functions (#3110)
                                                                    `.--`           
                                                                .ohNMMMMMNh/        
                                                             `/hNMMMMMMMMMMMd`      
                                                                  .dMMMMMMMMMy      
                                                                   ommNmmMMMMs      
                                                           ``   `+yNMMMMMMMMM/      
                                         Always has been    . .ohdNyyNMMNNmMM/      
                                                            -oyhMMmNmddddhso:-      
                                                            `/mMMmNdNMMMMMMMMMmyyys/
                                                              ohdNMMMMMMMMMMMMM/  /M
                              .+sys/`             .`          `+NMMMNmmNNNmNMMdNomMM
                             /dMMMMMN`      /oyddNMh.        .dMMMMMdshdmdmNMh/dMMMM
     Wait, it's all me?       `NMNMMm       :/:/yomMMhosssssymNMMMMMMMMMMMMMMMN+NNMM
                            `+mmMMMMo           sdMNMMmMMMMMMmNMMMMMMMMMMMMMMMh-MMMM
                            +Mdmmdy+/.          `+:.//sddNMMMmMMMMMMMMMMMMMMMMdsNMMM
                            /MMMMMhhyo+h`                  `NmMMMMMMmNMMMMMMMmmosMMM
                           +MMMMMd+/mhMMN-                 mmMMMMMMMMMMMNNMMMMMhmMMM
                          :mMNNMd-/ohNMMN/                 :MMmNNMMMNMMMMNNNMMMhhMMM
                          sMMMMMd``-hMMMM`                 :MMMMNNMMMMMMMMMMMMMy`NMM
                          dMMMMN:  .-MMMm                  :MMMMMMMmMMMMMMMMMMN. hMM
                          mMMMMh`   .MMMy                  -MMMMMMMMMMMMMMMMMMy  sMM
                         -MMMMd.    .MMMo                  `MMMMMMm+mMMMMMMMMM+  /MM
                        `NMMNd+/     NMN.                   mMMMMMMMMMMMMMMMNd:   mM
                        hMMNdoN.     -+`                    yMMMMMMMMMMMMMMMMN-   :d
                       :NMNydMs                             .NMMNmMMMMMMMMMMyd.    -

### PR DESCRIPTION
**Pull request by esakki-selvaraj**
Thanks for contributing! 🍄

1. LINKED ISSUES:
   Closes #3549 

2. TEST URLS:
   https://github.com/sindresorhus/refined-github/pull/3540/files

3. SCREENSHOT:
   No Screenshots

### CODE REVIEW

**Comment by fregante** [comment]
Thank you for the PR. Please undo all unrelated changes and don’t use Prettier or any auto- 
formatter for this project, we only use XO.

**Comment by esakki-selvaraj** [comment]
test url??

**Comment by fregante** [comment]
I see what’s going on, the indexes need to be sorted before being passed to .slice

This can be done without any conditions:

```js
 const selectedFiles = files.slice(...[
 	files.indexOf(previousFile) + 1,
 	files.indexOf(thisFile) + 1
].sort());
```

**Comment by fregante** [comment]
The test URL is where you’re making sure that this PR works. In this case you should link to any PR that has more than 2 files.

**Comment by esakki-selvaraj** [comment]
so can I include the same url you posted in the issue ?

**Comment by yakov116** [comment]
@esakki-selvaraj lint is failing. Can you run `xo --fix`

**Comment by esakki-selvaraj** [comment]
@yakov116 sure

**Comment by esakki-selvaraj** [comment]
`xo --fix`

**Comment by yakov116** [comment]
Command line.

You may need to install `xo` globally.  `npm I - g xo`

Or maybe can you try `npm run lint`?

**Comment by esakki-selvaraj** [comment]
I'll try it

**Comment by esakki-selvaraj** [comment]
Error: No files matching the pattern "'source/**/*.css'" were found.
    at E:\git-clone\refined-github\node_modules\stylelint\lib\standalone.js:208:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ lint:css: `stylelint 'source/**/*.css'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ lint:css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2020-09-15T12_46_37_866Z-debug.log

  source\helpers\post-form.ts:9:3
  ‼    9:3   Unexpected todo comment: TODO: drop `as` after....                                   no-warning-comments

  source\features\submit-review-as-single-comment.tsx:50:2
  ‼   50:2   Unexpected todo comment: TODO: this is wrong. `target` is a....                      no-warning-comments

  source\features\repo-age.tsx:84:2
  ‼   84:2   Unexpected todo comment: TODO: simplify selector after....                           no-warning-comments

  source\features\remove-label-faster.tsx:37:1
  ‼   37:1   Unexpected todo comment: TODO: set variable via JSX and inline....                   no-warning-comments

  source\features\highest-rated-comment.tsx:88:3
  ‼   88:3   Unexpected todo comment: TODO: update DOM to match other....                         no-warning-comments

  source\github-helpers\search-query.ts:58:2
  ‼   58:2   Unexpected todo comment: TODO: add support for values with....                       no-warning-comments

  source\github-helpers\index.ts:102:8
  ‼  102:8   Function preventPrCommitLinkLoss has too many parameters (5). Maximum allowed is 4.  max-params

  source\features\batch-mark-files-as-viewed.tsx:29:39
  ×   29:39  Require compare argument.                                                            @typescript-eslint/require-array-sort-compare

  7 warnings
  1 error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ lint:js: `xo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ lint:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2020-09-15T12_46_47_509Z-debug.log
ERROR: "lint:js" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ lint: `run-p lint:* --continue-on-error`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2020-09-15T12_46_47_571Z-debug.log

**Comment by yakov116** [comment]
It fixed one.
However there is still one error must be fixed manually.

`source\features\batch-mark-files-as-viewed.tsx:29:39
× 29:39 Require compare argument. @typescript-eslint/require-array-sort-compare`

**Comment by esakki-selvaraj** [comment]
@yakov116 done!!!

**Comment by fregante** [comment]
Thank you @esakki-selvaraj 🎂

**Pull request merged**
