### PR TITLE
Don't `list-prs-for-file` while you're editing the same PR

### LINKED ISSUE #3934: `list-prs-for-file` warns you while you're editing the same PR
1. Open a PR
2. Edit one of its file
3. End up on a page like: https://github.com/fregante/ghat/edit/update-existing/lib.js?pr=%2Ffregante%2Fghat%2Fpull%2F22

Note: It contains a `pr` parameter that points to the PR 22.

`list-prs-for-file` shows this message… but you're currently editing _that PR,_ so there's nothing to worry about.

Screen Shot 4

The current PR should be excluded from the list when possible (if the `pr` parameter appears in the URL)

### PR DESCRIPTION
**Pull request by yakov116**
1. LINKED ISSUES:
   Fixes #3934

2. TEST URLS:
   https://github.com/sindresorhus/refined-github/edit/drop-web-ext/contributing.md?pr=%2Fsindresorhus%2Frefined-github%2Fpull%2F3933

3. SCREENSHOT:
   None

### CODE REVIEW

**Comment by fregante** [comment]
Try again. Use URLSearchParameters like we always do and just exclude it from the array. The feature should still show any other PR open for the file. 

> The current PR should be excluded from the list

**Review by fregante — APPROVED** [review]

**Comment by yakov116** [comment]
@fregante did you test with multiple PR's? I left it a draft since I did not test it **yet**.

**Comment by yakov116** [comment]
Title good?

**Comment by yakov116** [comment]
Thanks for being going slow on me. I am so busy at work yet I miss OS so much I try to do it in the little free time I have lately.

Can't wait for march when things calm down. (My busiest season is from November to March)

**Pull request merged**
