### PR TITLE
Change page-detect to be URL-based

### LINKED ISSUE #783: Uncaught (in promise) TypeError: Cannot read property 'after' of undefined
When loading any page in settings

```
more-dropdown.js:16 Uncaught (in promise) TypeError: Cannot read property 'after' of undefined
    at more_dropdown (more-dropdown.js:16)
    at safely (utils.js:10)
    at github_injection_default (content.js:557)
    at gitHubInjection (index.js:13)
    at onDomReady (content.js:555)
    at <anonymous>
more_dropdown @ more-dropdown.js:16
safely @ utils.js:10
github_injection_default @ content.js:557
gitHubInjection @ index.js:13
onDomReady @ content.js:555
async function (async)
onDomReady @ content.js:514
init @ content.js:511
__webpack_require__.URL.URL @ content.js:638
__webpack_require__ @ bootstrap fc446b7fa65d86637335:19
(anonymous) @ bootstrap fc446b7fa65d86637335:62
(anonymous) @ bootstrap fc446b7fa65d86637335:62
09:55:17.833 add-releases-tab.js:42 Uncaught (in promise) TypeError: Cannot read property 'before' of null
    at add_releases_tab (add-releases-tab.js:42)
    at safely (utils.js:10)
    at github_injection_default (content.js:558)
    at gitHubInjection (index.js:13)
    at onDomReady (content.js:555)
    at <anonymous>
```

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes #783 (among others)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you include the reasoning for this?

**Comment by bfred-it** [comment]
From https://github.com/sindresorhus/refined-github/issues/761#issuecomment-340307775

> On that note, perhaps we should strive to keep page detections as URL based. Most features test for elements on the page before proceeding, so at that point just skip the duplicate dom query.

This would make `page-detect` more like the router you mentioned. Also only URL-based checks are currently testable.

**Comment by busches** [comment]
Let me know when you're ready for this to start testing and I'll give it a smoke run through GHE.

**Comment by bfred-it** [comment]
Yep it’s ready! There’s only one `select` in there and that’s going to be removed by #768

**Comment by bfred-it** [comment]
a3887da fixes #783

**Comment by busches** [comment]
Looks good on GHE, I did find an unrelated bug that I'll open an issue for.

**Comment by bfred-it** [comment]
Considering these changes are all covered by tests (old and new ones), I hope it will be merged soon to fix some `isRepo`-related bugs.

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by sindresorhus** [comment]
🙌

**Comment by bfred-it** [comment]
@sindresorhus should we extract this? I think it's mature enough and other extensions can benefit from it.

It'd need a bundler to support extensions not complex enough to justify having one. Bundler example: e.g. https://github.com/bfred-it/webext-dynamic-content-scripts/blob/master/package.json#L30-L46

**Comment by sindresorhus** [comment]
Yeah, sure.

**Pull request merged**
