### PR TITLE
GifHub is non-functional abandonware

### PR DESCRIPTION
**Pull request by bfred-it**
https://github.com/DrewML/GifHub/issues/21

### CODE REVIEW

**Comment by sindresorhus** [comment]
Lol. I didn't see the label. We should really have a way for labels to disable the merge button.

**Comment by bfred-it** [comment]
I have this https://github.com/sanemat/do-not-merge-wip-for-github

But since you're here already, the label was just to make sure #1148 is merged before the next release, which happens only if we merge new commits.

**Comment by sindresorhus** [comment]
What do you think about adding something like that to Refined GitHub? It would be easy to add and have a bigger impact.

**Comment by bfred-it** [comment]
I’m not a fan of merging extensions that ready exist 😅

**Comment by shroudedcode** [comment]
> I’m not a fan of merging extensions that ready exist

@bfred-it I can see quite a few benefits in merging these single-feature extensions into Refined GitHub:

1. We can bring their feature(s) to a larger user base (as already mentioned by Sindre).
2. We can make sure that the features don't clash with other features.
3. We actively maintain Refined GitHub. Most smaller extensions are abandoned.

**Comment by bfred-it** [comment]
Yeah, we don’t want to actively maintain hundreds of features no one cares about though, especially if they are already available and listed in our related extensions. If people don’t install them, they don’t care enough to have them.

**Comment by pavelloz** [comment]
Or they are like me and don't like to have a lot of extensions with a lot of authors - both security and OCD plays role when deciding if an extension is worth installing ;)

**Comment by bfred-it** [comment]
You can’t honestly request a handful of people to maintain all your favorite features because of your OCD. 🙂

At some point Sindre and I will reduce activity on Refined GitHub and you’ll lose them all on one swoop.

**Pull request merged**
