### PR TITLE
Improve shortcut help

### LINKED ISSUE #579: Add Refined GitHub shortcuts to the shortcuts help
We are adding additional keyboard shortcuts, but the shortcuts modal which pops up when you press <kbd>?</kbd> does not list them.

I think adding shortcuts should always include documenting them as it would increase visibility and therefore usage.

Key characteristics of a good keyboard shortcut:
- it's intuitive
- it's discoverable

### PR DESCRIPTION
**Pull request by shroudedcode**
An attempt to improve the shortcut help that can be opened by pressing <kbd>?</kbd>.

* All shortcut groups are now shown.
* Relevant shortcut groups have a higher opacity.
* "Projects"-related groups are removed entirely unless the user is on a projects page.
* Refined GitHub shortcuts are included (which closes #579) and marked with a small purple circle.
* `<kbd>` tags containing multiple keys are split up for consistency.

---

## API

There's a little API for other features to register their shortcuts:

```js
import {registerShortcut} from './improve-shortcut-help';

const group = 'site';
const hotkey = 'g t';
const description = 'Go to Trending';

registerShortcut(group, hotkey, description);
```

* `group`: the [ID of the group](https://github.com/shroudedcode/refined-github/blob/ee2cc184a59548a63964b73db095a7bc2ef07904/source/features/improve-shortcut-help.js#L6-L20) that the shortcut should be added to
* `hotkey`: a string with spaces separating the keys
* `description`: what the shortcut does, should use the same kind of wording that is used by GitHub

### CODE REVIEW

**Comment by shroudedcode** [comment]
Added a little indicator to the shortcuts added by Refined GitHub. I used a circle in the RGH color because I wasn't able to get the icon to look recognizable at that small size.

**Comment by bfred-it** [comment]
Nice! I like the circle + tooltip. Perhaps we should use `tooltipped-nw` because if they're on the right-hand column they might be outside the viewport.

Also this is feeling a bit tight:

**Comment by bfred-it** [comment]
We can merge this as soon as a screenshot is added to the readme.

**Comment by shroudedcode** [comment]
@bfred-it Now it's the other way around (see #1101) ... [there are linter errors on Travis CI](https://travis-ci.org/sindresorhus/refined-github/builds/349507675#L3623) but not on my machine after I made exactly zero changes to the CSS.

I thought it was maybe caused by an updated dependency (`^`) so I `rm -rf`-ed my `node_modules` (to be sure) and reinstalled all of them. Still, no linter errors. What's the problem this time? :confused:

**Comment by bfred-it** [comment]
No worries, it’s unrelated to this PR

**Pull request merged**
