### PR TITLE
Enable `shift-tab` to unindent comment fields

### PR DESCRIPTION
**Pull request by fregante**
Closes https://github.com/sindresorhus/refined-github/issues/2490

Finally I completed https://github.com/fregante/indent-textarea/pull/6 so `tab-to-indent` now also includes `shift-tab` support (as well as a `tab` behavior that matches editors more closely)

Have a look and see if it behaves correctly. I modeled it after VS Code. Sublime Text seems to **add** a `tab` with `shift-tab` if no text is selected. Weird.

### CODE REVIEW

**Comment by sindresorhus** [comment]
The behavior when just with whitespace is weird:


It skips going back to the start of the second line.

**Comment by fregante** [comment]
Good catch! This is one of those edge cases I was hoping to find before merging. 

```ts
// `|` is the cursor
undindent('\n|\t')

	expected: '\n|'
	actual: '|\n'
```

**Comment by fregante** [comment]
This is harder than I thought.

Anyway.

`unindent` or `outdent`? VSCode seems to use [`outdent`](https://github.com/microsoft/vscode/blob/4ebf8ee0b153e0420eed6950cdb9c33f95120162/src/vs/editor/common/commands/shiftCommand.ts) but elsewhere I found `unindent`

**Comment by fregante** [comment]
This should be fixed now.

**Pull request merged**
