### PR TITLE
Move `update-pr-from-base-branch` to a more reliable position

### PR DESCRIPTION
**Pull request by fregante**
Fixes https://github.com/sindresorhus/refined-github/issues/3927
Fixes https://github.com/sindresorhus/refined-github/issues/3699

I noticed that the mergeability [box](https://user-images.githubusercontent.com/1402241/106494253-cd204380-647f-11eb-90aa-df05213f8a38.png) [varies](https://user-images.githubusercontent.com/1402241/106494275-d27d8e00-647f-11eb-848d-d73280c5fad9.png) [a](https://user-images.githubusercontent.com/1402241/106494261-cf829d80-647f-11eb-831b-2a0d3d4d1878.png) [lot](https://user-images.githubusercontent.com/1402241/106494266-d0b3ca80-647f-11eb-977e-8e3576c3941e.png) and it's a pain to cover all the cases reliably. So I just moved the action next to the text that tells _we can update it by pushing,_ which makes sense. Also it helps that this text doesn't change that often.

The only drawback is that it wraps more often than it did before, pushing the box lower by 20px.

Screen Shot 10

cc @yakov116

### CODE REVIEW

**Comment by yakov116** [comment]
Brilliant! Cleaner Code, Much better. I like the look too! 🎉

**Comment by fregante** [comment]
> Cleaner Code, Much better

Yeah most of the code there was duplicate or just no longer working.

**Comment by yakov116** [comment]
Can we do `update the PR branch`?

**Comment by fregante** [comment]
Good point, I tried shortening it but it's not super clear. I restored the previous text.

And… merged just in time! 21.2.1 coming!

**Comment by yakov116** [comment]
image

**Comment by fregante** [comment]
It should have, the time was correctly parsed by GitHub too.

Screen Shot 1

I'm guessing:

- they had some problems right when it was supposed to run
- it will run delayed
- their backend failed to parse the date correctly

I'll deploy manually now either way

**Comment by fregante** [comment]
Oh shoot, just in time.

Screen Shot 2

**Comment by busches** [comment]
Any reason it's still referred to as a `button` when it's just text now?

**Comment by fregante** [comment]
What would you call it? It's not a link, it doesn't like anywhere.

**Pull request merged**
